srtcore/group.cpp, srtcore/group.h
The function `sendBackup_CheckParallelLinks` was doing two quite independent things:
- Retrying sending a packet in case not a single send operation has succeeded, but there are active links. Also blocking the `srt_sendmsg2` in blocking mode, and signalling an error in non-blocking mode.
- Silencing redundant active links if the main link is stable.
1. The first logic is now moved to `sendBackup_RetryWaitBlocked`,
2. The second logic is now moved to `sendBackup_SilenceRedundantLinks`
=> Splitting sendBackup_CheckParallelLinks(..)

docs/API-functions.md, docs/API.md, srtcore/queue.cpp, test/test_connection_timeout.cpp, test/test_enforced_encryption.cpp
Proper fix for #1736.
This reverses a change that was done in order to properly update groups when a caller socket has failed to connect. There was added a request to perform close-alike things (with setting flags and releasing thread-related resources) that caused the socket to be actually prematurely closed. This caused inability to properly deliver closure information to the caller callback and possibly too early execution of the GC on that socket that deleted the socket before it could be properly reported in the receiver queue thread.
This PR also contains reversal of the changes in the tests that were failing because of this problem.
Changes from #1736 could be also incorporated here as a sanity check.
=> [core] Fixed too early closed caller socket in background.

CMakeLists.txt
CMake version 3.0 introduced the VERSION option of the `project()` command to specify a project version as well as the name.
CMake version 3.19.3 warns when the policy is not set and uses OLD behavior.
See [CMP0048](https://cmake.org/cmake/help/latest/policy/CMP0048.html).
```shell
CMake Warning (dev) at CMakeLists.txt:15 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
CMAKE_PROJECT_VERSION
CMAKE_PROJECT_VERSION_MAJOR
CMAKE_PROJECT_VERSION_MINOR
CMAKE_PROJECT_VERSION_PATCH
```
This PR uses the new policy for CMake Versions above 3.0.
=> [build] Fixed CMake CMP0048 policy restriction

apps/apputil.cpp, apps/apputil.hpp, apps/srt-live-transmit.cpp, docs/srt-live-transmit.md, testing/srt-test-live.cpp
Replaces #1551 
This introduces the stats table, which contains the category-shortname labeling for json and longname (usually same as the field name in CBytePerfMon) for csv format.
The both json and csv formatters now use the statements from the table instead of manually crafted headers, labels and values.
=> [apps] Refactored stats tables with universal printers

apps/apputil.cpp, apps/apputil.hpp
Added virtual destructor for abstract struct SrtStatData.
A build warning after #1743.
```
/c++/v1/memory:2368:5: warning: delete called on 'SrtStatData' that is abstract but has non-virtual destructor
[-Wdelete-abstract-non-virtual-dtor]
delete __ptr;
^
/c++/v1/memory:2623:7: note: in instantiation of member function 'std::__1::default_delete<SrtStatData>::operator()'
requested here
__ptr_.second()(__tmp);
^
/c++/v1/memory:2577:19: note: in instantiation of member function 'std::__1::unique_ptr<SrtStatData,
std::__1::default_delete<SrtStatData> >::reset' requested here
~unique_ptr() { reset(); }
^
/c++/v1/memory:1936:64: note: in instantiation of member function 'std::__1::unique_ptr<SrtStatData,
std::__1::default_delete<SrtStatData> >::~unique_ptr' requested here …
```
=> [apps] Fix virtual destructor for abstract struct SrtStatData

test/test_sync.cpp
This adds a 1/1000 of the original time as tolerance as to when the time can elapse earlier (that is, the given time isn't the exact minimum time expected to wait).
=> [test] Added 1%% tolerance for long waiting time

srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp
Extracting some minor refactoring from a feature branch with runtime link stability threshold.
When a member link is activated, according to the new naming its state is "fresh activated", and it is in the "activation phase".
Therefore `CUDT::m_tsTmpActiveSince` is renamed to `m_tsFreshActivation`.
=> [core] Minor: renamed CUDT m_tsTmpActiveSince to m_tsFreshActivation

srtcore/core.cpp, srtcore/group.cpp, srtcore/group.h
This PR mainly moves the part responsible for collecting alive links and polling them for read-readiness into a separate function, called from `CUDTGroup::recv(..)`.
=> [core] Bonding: refactoring receiving function

apps/apputil.cpp, apps/apputil.hpp
Added printing timepoint (time when the stats was printed) for the json format.
=> Added timepoint printing in json format

apps/srt-file-transmit.cpp
Fixes #1764 
The problem: In `DoDownload` the application was incorrectly reacting on `SRTS_BROKEN` state by stopping reading too prematurely, while there were still data to extract, causing randomly cut files.
=> [apps] Fix too premature stopped reading in srt-file-transmit

testing/srt-test-live.cpp, testing/testmedia.cpp, testing/testmedia.hpp
This changes the way how Control-C and SIGINT handling is done by simply setting a flag and checking the flag often during transmission and the interrupt does a gently exit.
=> [testapp] Fixed hangup when exitting on interrupt

srtcore/group.cpp
TSBPD thread of a group member might not yet trigger epoll read-ready event, while it is potentially ready.
If another member signals read-readiness ahead of the current position it will result in a packet drop by a group.
This PR changes the logic of a group waiting for read-readiness.
When a notification is received, not only notified sockets are added to the reading list, but also those not notified, but with receiver buffer ready to read.
Fixes #1755 
Fixes: #1757 (likely the same reason, tests show no losses when switching back)
=> [core] Fixed packet drop when reading from members

docs/APISocketOptions.md, srtcore/core.cpp
Fixes #1747 
Fixed description on options restrictions:
1. "Binding" renamed to "Restrict", as it describes restrictions on setting an option
2. Introduced "pre-bind" for options that must not be altered after binding
3. Fixed SRTO_BINDTODEVICE that should be restricted as pre-bind.
There's a problem here though. Only some selected options should not be altered after binding, as binding applies some very specific settings that must be applied before and these settings apply to the binding process itself. ONLY those options should be "pre-bind", all others that are connection-restricted, should be "pre". Fixing this should be done also in the code so that it's connected state, not open state checked in the option setting procedure.
=> Fixed documentation on option restrictions

.travis.yml, apps/srt-file-transmit.cpp
SonarCould no longer supports Java versions below 11. Thus out Travis CI is failing at the moment.
This PR upgrades the Linux disttro used in Travis to Xenial, which has Java 11 by default.
Unfortunately, there are some issues with C++11 threads in MinGW build, but we only have them in unit tests now.
These unit tests are not run for MinGW build anyway, therefore it is pretty safe to exclude them from the build for MinGW.
And there is also a small fix for `srt-file-transmit` that allows building this app under MinGW and partially addresses issue #177.
- [SonarCloud end of pre Java 11 support](https://sonarcloud.io/documentation/appendices/end-of-support/)
- [Travis SonarCloud integration guide](https://docs.travis-ci.com/user/sonarcloud/)
=> [build] Using xenial dist in Travis with Java 11

srtcore/group.cpp
Added log message in case a packet is dropped due to a kangaroo link.
Somewhere related to this code block:
```c++
if (seqdiff > 1)
{
HLOGC(grlog.Debug,
log << "@" << id << " %" << mctrl.pktseq << " #" << mctrl.msgno << " AHEAD base=%"
<< m_RcvBaseSeqNo);
p->packet.assign(buf, buf + stat);
p->mctrl = mctrl;
break; // Don't read from that socket anymore.
}
```
Fixes #1760
=> [core] Added group receiver drop log warning

CMakeLists.txt, docs/APISocketOptions.md, srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp
The existing option `SRTO_GROUPSTABTIMEO` sets a timeout for the last response time of a group member link.
The same value is used for all member links.
An optimal timeout value depends on the network conditions (RTT, loss rate), and can be calculated at runtime.
This PR replaces the usage of  `SRTO_GROUPSTABTIMEO`  with a dynamic link stability timeout calculated at runtime.
When an idle or newly connected link is activated, it first transits to an "activation phase" and stays there for `SRTO_PEERLATENCY + 50ms` with the minimum allowed value of 60 ms, and the maximum allowed value of `SRTO_PEERIDLETIMEO`.
It is expected that at the start of sending RTT, RTTVar and link stability are not yet known. Therefore a link needs to stay active for this period to judge if it is stable or not. …
=> Runtime link stability timeout for main/backup

srtcore/group.cpp
A more safe and straightforward fix of the issue with timestamping packets for bonding, compared to #1767.
Use `srctime` for all member links, instead of using the `srctime` value set by the first member link which has successfully sent a packet.
The source time of a packet is stored as the number of microseconds since the SRT internal clock epoch.
However internal clock accuracy might be higher than 1 μs (e.g. 1 ns).
Therefore, the value returned in `MSG_CTRL::src_time` may have a lower accuracy compared to the actual time point used to timestamp a packet.
In the case of group sender, in particular, this may result in 1 μs timestamp difference of the same packet, sent over several links. The first link will use internal clock accuracy, while other links will have a μs accuracy of the …
=> [core] Fixed bonding packet timestamping

srtcore/srt.h
The warning can be triggered when srt.h is included by other project.
=> [core] Fix warning and workaround ABI compatibility due to ENABLE_EXPERIMENTAL_BONDING

srtcore/api.cpp
There was a lacking initialization of `m_stats.tsLastSampleTime` that should be the "alleged previous sample time", which caused that the interval-based statistics for the very first probe looked ridiculous. This field was correctly initialized to 0, so there was no undefined behavior, but the time interval counted against this and the time when sampling was done was time since epoch.
This fix sets the current time to this value in two places:
- in case when the group was just connected (not connected before, and first-ever connection has been established)
- in case when the group was about to return from the `srt_accept` call
This should mimic the similar initialization done in `CUDT::clearData` that is called just after "opening".
=> [core] Fixed pre-initialization of the last sample time for groups

srtcore/sync.h
The 'limits' header must be included explicitly.
=> Fix build with GCC 11

srtcore/group.cpp
One of the member links can provide a packet ahead of the current position after another link has provided a valid packet.
This AHEAD packet is saved in group's buffer. However, the payload of the packet was incorrect, as it was read to a buffer different from the one being saved.
Fixes #1799
Already have the one to deliver.
```c++
if (output_size)
{
// We have already the data, so this must fall on the floor
char lostbuf[SRT_LIVE_MAX_PLSIZE];
stat = ps->core().receiveMessage((lostbuf), SRT_LIVE_MAX_PLSIZE, (mctrl), CUDTUnited::ERH_RETURN);
```
Here `buf` is different from `lostbuf` where the packet was read to.
```c++
if (seqdiff > 1)
{
HLOGC(grlog.Debug,
log << "@" << id << " %" << mctrl.pktseq << " #" << mctrl.msgno << " AHEAD base=%"
<< m_RcvBaseSeqNo);
p->packet.assign(buf, buf + …
```
=> [core] Fixed group rcv buffering of ignored packet

srtcore/api.cpp, srtcore/api.h, srtcore/handshake.cpp
Changes:
1. Removed check if socket ID provided in the handshake fits in some range. This check is useless, sockets are allowed to have any value, even value in the group range if used against pre-1.4.2 version. Just not 0 (although this is a special value used in the handshake).
2. Definition of MAX_SOCKET_VAL fixed to be the same as SOCKGROUP_MASK, that is 0x40000000. 1 << 29 was wrong (0x20000000).
3. Fixed formula for translating random value into a random socket ID value. The old formula didn't take into account, though little probable, theoretically possible case when `rand()` returns exactly `RAND_MAX`.
=> [core] Fixed wrong max socket ID value formula

srtcore/core.cpp, srtcore/group.cpp, test/test_bonding.cpp
Two things were missing:
1. Initialization of group statistics;
2. Update of pktSentUnique in the Main/Backup sending.
=> Fixed SRT group stats: initialization and send stats for backup 

apps/socketoptions.hpp, srtcore/core.cpp
Fixes #1821 
(tested with a group connection using drifttracer option set for a member)
=> [core][apps] Fixed restrictions for options and replication in the app array

srtcore/socketconfig.h, test/test_utilities.cpp
BUG: When setting a string with shorter size than the one that exists, characters past the alleged size may remain from previous one.
Also added UT for StringStorage type.
=> Fixed bug: wrong size setting for StringStorage. Added UT.

srtcore/api.cpp, srtcore/channel.cpp, srtcore/congctl.h, srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp, srtcore/filelist.maf, srtcore/group.cpp, srtcore/packetfilter.cpp, srtcore/queue.cpp, srtcore/socketconfig.h
`CSrtConfig`, `CSrtMuxerConfig` and others as of now are structures.
They allow public access to their members. Members currently have `m_` prefix, which is intended to identify private members.
**Changes:**
```c++
const char* pcUDPRcvBufSize() const;
```
=> Removed 'm_' prefix in socket config structs

srtcore/epoll.cpp, srtcore/epoll.h, srtcore/group.cpp
The problem detected by thread sanitizer: The calls to `m_SndEPolldesc->watch_empty()` is done without locking, while all operations on epoll require a lock on `CEPoll::m_EPollLock`.
Changes:
* Made whole CEPollDesc class private with exclusive access for CEPoll. This is to ensure that the CEPollDesc class isn't used "privately" by any other part of the code.
* Added an access function `CEPoll::empty` to return information about having no subscribers, with appropriate locking.
=> [BUG][core] Unguarded access to epolldesc from group sender code

srtcore/core.cpp
more detailed informations: 
1. user call receive/receivemessage(about line number:6482)
2. after read/receive, if rcvbuffer is empty, will set SRT_EPOLL_IN event to false
3. but if we do not do some lock work here, will cause some sync problems between threads:
(1) user thread: call receive/receivemessage
(2) user thread: read data
(3) user thread: no data in rcvbuffer, set SRT_EPOLL_IN event to false
(4) receive thread: receive data and set SRT_EPOLL_IN to true
(5) user thread: set SRT_EPOLL_IN to false
4. so , m_RecvLock must be used here to protect epoll event
=> fix epoll event loss problem 

srtcore/core.cpp, srtcore/group.cpp
The problem: `ackMessage` was called without locking a group from the handler of UMSG_ACK, which might cause wrong timing for update of the field holding this last message number updated from ACK.
=> [core] Fixed: lock around ackmessage

docs/APISocketOptions.md
Also fixed a typo.
A follow up for #1791
=> [docs] Moved SRTO_MININPUTBW in alphabetic order

srtcore/sync.h
The latest pthreads for Windows does not define `PTW32_VERSION` macro. Looks like it was remamed to `__PTW32_VERSION`.
This PR adds an additional condition check to see if `__PTW32_VERSION` is defined.
- vcpkgversion 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
- pthreads:x64-windows                               3.0.0-6          pthreads for windows
Version: 3.0.0-6
Homepage: https://sourceware.org/pub/pthreads-win32/
Description: pthreads for windows
Fixes #1815
=> [core] Fixed Windows build with latest pthreads

CMakeLists.txt
Before the fix (cmake version 3.10.2):
```shell
-- APP: test-srt: using default C++ standard
CMake Warning (dev) at /usr/share/cmake/Modules/GoogleTest.cmake:254 (if):
Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
--help-policy CMP0057" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
IN_LIST will be interpreted as an operator when the policy is set to NEW.
Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
CMakeLists.txt:1227 (gtest_add_tests)
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Error at /usr/share/cmake/Modules/GoogleTest.cmake:254 (if):
if given arguments:
"test-srt" "IN_LIST" "allKeywords"
Unknown arguments specified
Call Stack …
```
=> [build] Fixed build break with latest GTest

srtcore/core.cpp
After reconnection, the values of RTT and bandwidth are restored from the cache. RTTVar remains the default one which is 50 ms (half of the initial RTT = 100 ms).
```c++
CInfoBlock ib;
ib.m_iIPversion = peer.family();
CInfoBlock::convert(peer, ib.m_piIP);
if (m_pCache->lookup(&ib) >= 0)
{
m_iRTT       = ib.m_iRTT;
m_iBandwidth = ib.m_iBandwidth;
}
```
With the current fix, the value of RTTVar is set to `RTT (from cache) / 2` after reconnection.
Fixes partially #1769, see the [following comment](https://github.com/haivision/srt/issues/1769#issuecomment-775213157).
The fix can be tested with the help of `srt-xtransmit` application (`develop/bonding` branch) and Connection Bonding (Main/Backup) feature of SRT. It is required to emulate the breakage of the main link when it's deleted from the …
=> [core] Restoring RTTVar from cached RTT after reconnection

srtcore/core.cpp
This removes the condition that disallows the group HS extension to be larger than required. This blocks adding new fields to this extension in the future.
=> [core] Removed condition that blocks extending group HS extension in future

docs/APISocketOptions.md, srtcore/core.cpp, srtcore/socketconfig.h, test/test_socket_options.cpp
The problem:
The STREAMID (like all other string-type extensions) if it was set the length 509-512 (which is still legal), was rejected during setting of the config string because the length was taken as 512.
The string is passed in 4-byte chunks, which is then padded with zeros if the number of characters is not aligned to 4. The length to set the string was however calculated as the size of the extension data (which are 128 for the given sizes) multiplied by size of the field (4), which resulted to always 512, which exceeds the allowed size.
As the size of the actual string should be up to the first 0, the length should be taken directly by `strlen` because the length calculated out of `blocklen` may include the padding zeros, which makes the size wrong.
Additionally fixed bug in …
=> [core] Fixed incorrect setting streamid in internal config in HS (last 4 characters)

docs/API-functions.md
As per the information that only IN event should be tested for listner-accept-ready, it turns out that the information about that for the user was not exactly precisely provided. Hence this updates this information.
=> [docs] Updated and fixed blocking and error information

srtcore/api.cpp, srtcore/api.h, srtcore/core.cpp
The call to `syncWithSocket` was done incorrectly and in addition the latency updated with the handshake was modified simultaneously while being read on the receiver worker thread that was about to establish the connection. In effect, the latency being used to set into the group data could be either the latency before or after negotiation depending on luck.
This PR makes two fixes:
1. The call to `syncWithSocket` in the connection API function handler is removed. This was not working in blocking mode (as per reason above), and in non-blocking it wasn't even executed. Instead this synchro is made at the time when the group is being set the peer ID at the first time, which is a good enough criterion to check if this is the very first connecting socket, and - as being executed as a part of …
=> [core] Fixed incorrect group data sync on first connected socket

apps/apputil.hpp, testing/testmedia.cpp
Fixed #1872
1. Incorrect handling of the "again" situation after setting 1s timeout so that a check for interrupt can happen. This was resulting in phantom zero packets because the -1 result from `srt_recvmsg2` was not correctly handled.
2. Also added a timeout for UDP reading so that it can be correctly interrupted.
=> [devel] Fixed wrong handling of no transmission in the test apps

srtcore/api.cpp, srtcore/core.cpp
=> [core] Added restrictions on pktseq/msgno fields in srt_sendmsg2 call

srtcore/core.cpp
Removed the lock for CUDTSocket::m_ControlLock that breaks the ordering against m_ConnectionLock (which may lead to a deadlock, which was also experienced in some tests). This lock is likely not necessary provided that m_GlobControlLock is also applied.
=> [core] Removed unnecessary lock that could cause a deadlock

srtcore/core.cpp, srtcore/core.h, srtcore/window.cpp, srtcore/window.h
(1) - This PR provides extended logs for negative or zero RTT estimate on the receiver side, former "IPE: ACK node overwritten message". See issue #253 for details.
The logs are now splitted into two cases:
- When the record about ACK is not found in the buffer,
- When the RTT estimate obtained by the receiver based on ACK/ACKACK pair is negative or zero.
This check happens upon ACKACK reception by the receiver.
The logs format is the following:
```
12:40:38.677155/SRT:RcvQ:w1*E:SRT.in: @577838857:IPE: The record about ACK is not found, RTT estimate at the receiver side can not be calculated (ACK number: 113, last ACK sent: 115, oldest ACK record: not yet available, RTT (EWMA): 21052)
```
```
12:40:38.677194/SRT:RcvQ:w1*E:SRT.in: @577838857:IPE: RTT estimate obtained by the receiver is …
```
=> [core] Extended logs for negative or zero RTT estimate on the receiver side

docs/API/API-socket-options.md, srtcore/socketconfig.h
Fixes #1898
Problem: 32 is to be the minimum allowed value for `SRTO_FC`, so a maximum out of 32 and the given one should be used.
Also the constant should use MIN, not MAX, as this is the minimum allowed value.
Documentation: the unit for SRTO_FC is packet, so it should be fixed that this is the maximum number of PACKETS that can be sent without acknowledgement.
=> [core] Fixed wrong limitation on SRTO_FC option. Fixed documentation.

docs/API-functions.md
The method of calling the connect callback for a successful connection as an alternative to epoll has been removed. This doesn't work and was intentionally removed from the early code; can be restored in the future as long as sensibly implemented.
=> [doc] Removed misleading information about connect callback in successful connection

srtcore/epoll.cpp, srtcore/epoll.h, srtcore/group.cpp
Two minor fixes in this Pr (in separate commits):
1. Made `CEpoll::m_EPollLock` mutable. `CEpoll::empty(..)` now has a const qualifier.
2. `sendBackup`: use logical OR instead of bitwise
Closes #1847
=> Made CEpoll::m_EPollLock mutable

srtcore/api.cpp, srtcore/api.h, srtcore/core.cpp, srtcore/filelist.maf, srtcore/group.cpp, srtcore/group.h, srtcore/group_common.cpp, srtcore/group_common.h
Minor refactoring, extracted from PR #1857. Will be used in the updated main/backup code.
`CUDTGroup::SocketData` is moved to a separate file `group_common.h` under `srt::groups` namespace.
=> [core] SocketData moved to group_common.h (REFAX)

srtcore/common.h
If C++11 is available, SRT_STATIC_ASSERT  maps to `static_assert`. Otherwise empty macro.
Extracting from #1857.
=> [core] Added SRT_STATIC_ASSERT macro

srtcore/packetfilter.h
`bool ParseFilterConfig()` 3 parameter version is called in `srtcore/socketconfig.h:1072`, but there is no prototype defined for it. This causes build failures with toolchains that do not auto-create an `int ParseFilterConfig()` for calls to undefined functions. This could also cause ABI issues if `sizeof(bool) != sizeof(int)` causing potential memory access violations.
=> Build Fix.

docs/API/API-socket-options.md, srtcore/socketconfig.h
1. The minimum allowed value of `SRTO_FC` socket option is 32.
This PR makes `srt_setsockopt` to set the `SRT_EINVPARAM` and return `SRT_ERROR` if the lower value is supplied.
Previous SRT versions (v1.4.2 and below) return `SRT_SUCCESS`, but reset `SRTO_FC` to 32.
2. Documentation for `SRTO_FC` is improved.
3. Fix: `SRTO_MINVERSION` is also readable.
4. Fix: SRTO_MINVERSION default value is 1.0.0
=> SRTO_FC socket option: minimum allowed value is 32

srtcore/core.cpp, srtcore/core.h
Minor refactoring of `CUDT::processCtrl(..)` function:
- moved code to processCtrlAckAck
- moved code to processCtrlHS
- moved code to processCtrlDropReq
- moved code to processCtrlShutdown
- moved code to processCtrlUserDefined
=> Moved some code from processCtrl to dedicated functions

docs/API/API-socket-options.md, srtcore/core.cpp, srtcore/core.h, srtcore/socketconfig.h
This PR fixes/changes:
- Rejecting negative values (as not allowed).
- Handling zero value properly (as the default). Previously setting `SRTO_KMREFRESHRATE=0` was changing `SRTO_KMPREANNOUNCE=0x7fffffff`.
- `SRTO_KMREFRESHRATE` and `SRTO_KMPREANNOUNCE` and not readable (as was already stated in the docs).
- Updated docs: described the default 0 value meaning.
The default values of both `SRTO_KMREFRESHRATE` and `SRTO_KMPREANNOUNCE` is zero. It is treated as:
- `SRTO_KMREFRESHRATE = 0x1000000`
- `SRTO_KMPREANNOUNCE= 0x1000`
`if (km_preanno > (kmref - 1) / 2)`
=> [core] Fixed SRTO_KM* options setting.

.travis.yml
Due to recent build failures on 10.2 because `openssl` package is no longer found. 😕
=> [build] Updated Travis OSX to 11.1

test/test_ipv6.cpp
On some platforms _S is defined as a macro as reported by @ethouris  in #1917.
Closes #1917.
Also fixed two minor conversion type warnings.
=> [tests] Removed "" _S function.

scripts/FindMbedTLS.cmake
The warning message:
"The package name passed to `find_package_handle_standard_args` (Libmbedtls)
does not match the name of the calling package (MbedTLS).  This can lead to
problems in calling code that expects `find_package` result variables
(e.g., `_FOUND`) to follow a certain pattern."
=> Fix cmake warning on FindMbedTLS

apps/srt-live-transmit.cpp, docs/apps/srt-live-transmit.md
Some error messages were downgraded to "warn" level in some previous PRs (#1271 May 8, 2020). SRT v1.4.2 and above.
For example, the "No room to store incoming packet.." has the "warn" level ([see here](https://github.com/Haivision/srt/blob/v1.4.3-rc.0/srtcore/core.cpp#L9326)).
By default, `srt-live-transmit` shows only error messages, which makes some important logs invisible.
This PR changes the default log level of `srt-live-transmit` to "warn".
=> [apps] Changed the default log level to Warn

srtcore/core.cpp, srtcore/core.h
Minor refactoring during the code studying.
=> [core] Minor refactoring during the code studying

srtcore/core.cpp, srtcore/sync_posix.cpp
1. sync_posix: make global variable and function file scope
2. replace static_assert by SRT_STATIC_ASSERT
=> Minor cleanup

.travis.yml, srtcore/core.cpp, srtcore/socketconfig.h, test/test_enforced_encryption.cpp
In `srt_getsockopt(..)` API function these `bool` socket options were actually using `int` type when casting the `optval`, which may lead to writing outsize the memory of the `optval` when `bool` is provided.
- `SRTO_SENDER`
- `SRTO_TSBPDMODE`
- `SRTO_DRIFTTRACER`
- `SRTO_ENFORCEDENCRYPTION`
This PR changes types to `bool` if `optlen` is zero of `sizeof(bool)`, otherwise casts to `int`.
Fixing cast to bool is the lesser evil compared to potential outside-of-memory writing.
This change however affects SRT API a bit and might lead to certain upgrading difficulties.
Both FFMpeg and GStreamer should not get into trouble with this change, as they only get the value of `SRTO_PAYLOADSIZE`.
Still, the output `optlen` should provide a hint of how many bytes were actually set by …
=> Fixing srt_getsockopt for bool socket options

srtcore/core.cpp
Return an error if `optlen` passed in `srt_getsockopt(..)` for `SRTO_CONGESTION` is not big enough to fit the string value of an option (effectively four chars + one null-terminating character).
=> [core] SRTO_CONGESTION: Check optlen in getsockopt

docs/API/API-socket-options.md, srtcore/core.cpp, test/test_fec_rebuilding.cpp
PRE restriction of a socket option will be applied on a socket in one of the following states:
- Listening (**added in this PR**);
- Connecting
- Connected
It increases the strictness of the restriction.
SRT v1.4.2 and prior didn't have this restriction. However, e.g. setting option `SRTO_LATENCY` in SRT v1.4.2 was rejected if socket's `m_bOpened` was `true`. This now corresponds to the PRE-BIND restrictions. At the same time, it does not make sense to forbid changing `SRTO_LATENCY` once the socket is bound to some UDP address.
But it makes sense to forbid it once the connection establishment is in progress (connecting or listening) or has already succeeded.
Once the socket starts listening, changing `SRTO_LATENCY` should not be a supported use case.
Options are set one by one. It means …
=> [core] Apply PRE sockopt restriction in listening state

srtcore/api.cpp, test/test_connection_timeout.cpp
Fixes #1880 
Added more logs around errors from `srt_accept`.
=> [core] Added more logs around accept errors

srtcore/core.cpp
Returning configuration value of `SRTO_TLPKTDROP` if a socket is not yet connected.
_A reopening of #1943, which was mistakenly created from fork's master._
=> [core] Fixed getting SRTO_TLPKTDROP: return config value until connected.

srtcore/core.cpp, srtcore/sync_posix.cpp
Minor changes: made `srt_options_action` constant. Renamed to `s_srt_option_action`.
The prefix `s_` is intended to depict internal (static) linkage.
- [C++ Core Guidelines I.2](https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#i2-avoid-non-const-global-variables) - Avoid non-const global variables
- [C++ Core Guidelines C.7](https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#c7-dont-define-a-class-or-enum-and-declare-a-variable-of-its-type-in-the-same-statement): Don't define a class or enum and declare a variable of its type in the same statement
=> [core] const SrtOptionAction

apps/apputil.cpp
The problem was with proper handling a single dash as a value:
```
app -option value -input - -output output.ts
```
The single `-` being a value was incorrectly treated as an option with no name.
=> [apps] Option utility fix: handle properly single dash as option value

docs/API/API-socket-options.md
according to the implementation
- `SRTO_MSS` has a pre-bind restriction
- `SRTO_LOSSMAXTTL` has a post restriction
=> [docs] SRTO_MSS: pre-bind restriction instead of pre

srtcore/api.cpp
This removes the call to logging in `CUDTUnited::cleanup` and adds a comment that explains why it should not be done.
If this function is called from the global application destructor, logging instruction may potentially refer to an object that is already deleted and cause a crash this way.
=> [core] Removed logging in cleanup

docs/API/API-functions.md, docs/API/API-socket-options.md
Improved the documentation of `srt_getsockopt(..)` advising to pass the size of `optval` in `optlen`.
The first step towards #1819 (checking `optlen` provided in `srt_getsockopt(..)`).
Also defines missing error codes for `srt_setsockopt(..)` function.
Added some guidelines for handling C string type options.
Depends on #1939: PRE restriction in "listening" state.
=> [docs] API-functions: pass optlen in srt_getsockopt

docs/API/API-socket-options.md, srtcore/socketconfig.h
`srt_setsockopt(..)`:
- `SRTO_CONNTIMEO`: return error setting negative value
- `SRTO_PAYLOADSIZE`: return error setting negative value, fix FEC validation.
- `SRTO_SNDDROPDELAY >= -1`
- `SRTO_SNDTIMEO >= -1`
- `SRTO_*LATENCY >= 0`
- `SRTO_PEERIDLETIMEO >= 0`
=> [API] Check invalid sockopt values

.travis.yml, apps/srt-tunnel.cpp, apps/transmitmedia.hpp, srtcore/buffer.cpp, srtcore/channel.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp, srtcore/logging.h, srtcore/socketconfig.h, srtcore/window.h
- [core] Fixed some minor build and static analyzer warnings.
- [build] Added `-Werror` flag to Linux and macOS CI builds on Travis.
- [apps] Fixed virtual call from a destructor. Virtual functions should not be invoked from a constructor or destructor of the same class. Confusingly, virtual functions are resolved statically (not dynamically) in constructors and destructors for the same class.
=> [core] Fixed type conversion build warning

docs/API/API-functions.md, srtcore/srt.h, srtcore/srt_c_api.cpp, srtcore/sync.h
Adds `int srt_clock_type(void)` API function to determine in runtime the internal clock type used by SRT library.
Possible return values:
```c++
#define SRT_SYNC_CLOCK_STDCXX_STEADY      0 // C++11 std::chrono::steady_clock
#define SRT_SYNC_CLOCK_GETTIME_MONOTONIC  1 // clock_gettime with CLOCK_MONOTONIC
#define SRT_SYNC_CLOCK_WINQPC             2
#define SRT_SYNC_CLOCK_MACH_ABSTIME       3
#define SRT_SYNC_CLOCK_POSIX_GETTIMEOFDAY 4
#define SRT_SYNC_CLOCK_AMD64_RDTSC        5
#define SRT_SYNC_CLOCK_IA32_RDTSC         6
#define SRT_SYNC_CLOCK_IA64_ITC           7
```
Defines are used instead of enum to allow possible inclusion of `SRT_INTERNAL_CLOCK_VERSION` in `version.h` to determine the clock type at the compilation time.
Fixes #1702
=> [core] New API function srt_clock_type()

CMakeLists.txt, srtcore/core.cpp, srtcore/core.h
Improved RTT estimation in the following way:
- On the receiver side, reset smoothed RTT to the very first RTT sample obtained from the ACK/ACKACK pair. At the beginning of a transmission, the value of smoothed RTT is either equal to `INITIAL_RTT = 100 ms`, or is taken from cache. It remains so until the very first ACKACK packet is received from the sender and triggers RTT sample calculation. At this moment, the smoothed RTT is reset to the very first RTT sample and the EWMA is applied further on the subsequent RTT samples.
- On the sender side, in the case of unidirectional transmission, the values of smoothed RTT and RTT variance are now extracted from the ACK packets. There is no more EWMA applied on the sender side to avoid double smoothing, see issue #782. 
The initial values of RTT …
=> [core] Improved RTT estimation

docs/API/statistics.md, srtcore/cache.cpp, srtcore/cache.h, srtcore/common.h, srtcore/congctl.cpp, srtcore/congctl.h, srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp, srtcore/group.cpp
- Renamed `m_iRTT` variable to `m_iSRTT` so it reflects that the RTT estimate is a smoothed RTT, an exponentially-weighted moving average (EWMA) of an endpoint's RTT samples. SRTT means smoothed RTT (see [RFC6298](https://datatracker.ietf.org/doc/html/rfc6298) for the reference).
- Updated `msRTT` description in `docs/API/statistics.md`.
=> [core] Renamed m_iRTT variable to m_iSRTT

examples/example-client-nonblock.c
`SRTO_RCVSYN` and `SRTO_SNDSYN` were wrongfully set to `1` instead of `0`, as noticed by @nobodyintheworld in [this comment](https://github.com/Haivision/srt/pull/1746#issuecomment-828903129).
=> Fixed nonblocking client example

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/filelist.maf, srtcore/group.cpp, srtcore/tsbpd_time.cpp, srtcore/tsbpd_time.h
Extracted refactoring around `CRcvBuffer` and TSBPD logic from PR #1965. No functional changes are expected.
The new `CTsbpdTime` class is now to operate with TSBPD timing.
=> TSBPD logic extracted from CRcvBuffer. 

docs/API/API-socket-options.md
Fixed `SRTO_RCVLATENCY` description of the default value in live mode.
The value of `0` depicts zero buffering delay, not the default 120 ms.
Wronfully added in PR #1607.
=> [docs] Fixed SRTO_RCVLATENCY description

docs/features/handshake.md, srtcore/core.cpp
The following condition in `CUDT::cookieContest()` can overflow the 32-bit signed integer:
```c++
int better_cookie = m_ConnReq.m_iCookie - m_ConnRes.m_iCookie;
```
The value of `better_cookie` is then checked against zero. A positive value is resolved to INITIATOR, a negative value is resolved to RESPONDER. Otherwise, DRAW and try again.
However, checking whether `better_cookie` has a negative or a positive value is not very reliable, as some compilers may optimize it just by comparing `m_ConnReq.m_iCookie` and `m_ConnRes.m_iCookie` instead.
The example input provided below results in HSD_DRAW when SRT is linked with -O3 and C++14 by clang.
A simplified example provided [in this comment](https://github.com/Haivision/srt/pull/1517#issuecomment-685745391) provides different results when …
=> [core] Fixed cookie contest

srtcore/api.cpp, srtcore/api.h, srtcore/core.cpp, srtcore/core.h, srtcore/group_common.cpp, srtcore/group_common.h, srtcore/strerror_defs.cpp
Extracted minor refactoring from PR #1857 around `strerror_array_sizes`, code formatting, etc. to reduce the diff.
=> [core] Minor refactoring around strerror_array_sizes

srtcore/socketconfig.h
There is a typo in the comment, and specify the configuration value
in comment has the risk of out of sync with source code.
=> [core] Fix comments

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp
The current "no room to store incoming packet" log message format does not provide enough hints to define the reason.
```shell
SRT.qr: @246279816:No room to store incoming packet: offset=1 avail=1
ack.seq=864548218 pkt.seq=864548219 rcv-remain=25598 drift=-768
```
**Log level: warning** (as before).
1) Example log message when the app is not reading fast enough:
```shell
No room to store incoming packet seqno 1887365986, insert offset 1711. Space avail 190/849 pkts.
Packets ACKed: 658 (TSBPD ready in -1680 : -1219 ms), not ACKed: 0, timespan 460 ms. STDCXX_STEADY drift 0 ms.
```
TSBPD ready in -1680 : -1219 ms indicates that there are 658 packets available for reading for already at least 1.6 seconds.
2) Example log message when there is almost nothing for the app to read, and not enough …
=> [core] Improved 'no room to store' log message

srtcore/queue.cpp
./test-srt  --gtest_filter=TestEnforcedEncryption.CASE_B_2_NonBlocking*
==24654==ERROR: AddressSanitizer: heap-use-after-free on address 0x62a000000f40 at pc 0x000109e6c756 bp 0x700000512550 sp 0x700000512548
READ of size 8 at 0x62a000000f40 thread T6
#0 0x109e6c755 in srt::sync::TimePoint<srt::sync::steady_clock>::TimePoint(srt::sync::TimePoint<srt::sync::steady_clock> const&) sync.h:189
#1 0x109df3f6c in srt::sync::TimePoint<srt::sync::steady_clock>::TimePoint(srt::sync::TimePoint<srt::sync::steady_clock> const&) sync.h:190
#2 0x10a1f0bfb in CRendezvousQueue::updateConnStatus(EReadStatus, EConnectStatus, CPacket const&) queue.cpp:949
#3 0x10a1fa38a in CRcvQueue::worker(void*) queue.cpp:1337
#4 0x7fff2032c94f in _pthread_start+0xdf (libsystem_pthread.dylib:x86_64+0x694f)
#5 …
=> Fix use-after-free in rendezvous queue

scripts/win-installer/.gitignore, scripts/win-installer/README.md, scripts/win-installer/build-win-intaller.ps1, scripts/win-installer/install-nsis.ps1, scripts/win-installer/install-openssl.ps1, scripts/win-installer/libsrt.nsi, scripts/win-installer/libsrt.props
See the scripts/win-installer/README.md file for details.
The Windows installer for SRT is currently managed in a [separate project](https://github.com/tsduck/srt-win-installer) in the context of the [TSDuck project](https://tsduck.io). It was proposed as a contribution in issue #1068. This pull request follows @maxsharabayko's request in the same issue.
=> Added script to build the Windows installer for SRT libraries

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/tsbpd_time.cpp, srtcore/tsbpd_time.h, srtcore/utilities.h
RTT sample is now taken into account in drift calculations.
TSBPD time base is the base time difference between the local clock of the receiver, and the clock used by the sender to timestamp packets being sent.
It is first initialized with the reception of the conclusion handshake as follows:
```
usTsbpdTimeBase = Tnow - usPktTimeStamp,
```
where `Tnow` is the time the HS packet is received (current time), `usPktTimeStamp` is the timestamp set on the packet.
For any further packet with its `usPktTimeStamp` corresponding to the sending time (only true for control packets), It is assumed that:
```
Tnow = usTsbpdTimeBase + usPktTimeStamp
```
Any consistent difference is caused by the drift of the two clocks (SND and RCV).
Therefore, drift is measured on every incoming ACKACK control packet …
=> Drift Tracer: taking RTT into account

srtcore/core.cpp
Fixes #2008 (although maybe partially)
The problem: HSv4 connection procedure didn't predict rejection on minimum version.
The problem with HSv4 version is that the connection is fully made in UDT terms, and HSREQ extension will be sent later as an extended message, and at this time it's way too late to decide about rejection. Therefore the full version check is impossible to be implemented for HSv4 clients.
However it's possible to reject any HSv4 clients if the minimum version is set to the version that supports HSv5, that is, 1.3.0. The rule is that if a client supports HSv5, it must use HSv5 connection method, if the other party accepts it. This means that the HSv5 listener must respond with HSv5 if it supports it, and then the caller cannot use HSv4 against a listener that reports …
=> [core] Fixed version rejection for HSv4 caller

srtcore/buffer.cpp, srtcore/core.cpp
The range pair of `UMSG_DROPREQ` should be `[low, high]` instead of `[low, high)`, right?
The previous code always make `m_iSndCurrSeqNo` bigger than the largest msg sent, then cause other problems.
=> [core] fix TTL drop packets

srtcore/api.cpp, srtcore/channel.cpp, srtcore/congctl.cpp, srtcore/core.h, srtcore/platform_sys.h, srtcore/srt.h, srtcore/srt_compat.h, srtcore/sync.cpp, srtcore/sync.h, srtcore/udt.h, srtcore/utilities.h, test/test_sync.cpp
_Commit no. 1._
Previously a custom definition `__MINGW__` was defined in `udt.h`. However, `udt.h`. was not included in every source file, which uses `__MINGW__` preprocessor definition, **including `srt.h`**.
According to [this table](http://beefchunk.com/documentation/lang/c/pre-defined-c/precomp.html) MinGW defines `__MINGW32__` preprocessor definition.
Now simply using `__MINGW32__` preprocessor definition in relevant places.
_Commit no. 2._
POSIX `rand()` is not thread safe.
This PR makes use of `rand_r(unsigned int *seed)` instead.
- C++11 enabled: `std::random_device` and `std::uniform_ditribution`;
- C++03 mode: a thread-safe `rand_r(unsigned int *seed)` is used instead.
- MinGW: still uses `rand()` as there is no `rand_r(..)` available.
Fixes #1825.
Maybe improves the situation …
=> [core] Added srt::sync::genRandomInt(..)

srtcore/buffer.cpp, srtcore/core.cpp, srtcore/srt.h
The range pair of `UMSG_DROPREQ` must be [low, high] instead of [low, high).
`m_iSndLastDataAck` is the very first packet that is present in the sender buffer (first packet after ACK). Therefore it should not be included in the range for dropping.
Revealed while reviewing #2003.
Related to #1910.
=> [core] Fixed DROPREQ on NAK behind SndLastDataAck

scripts/win-installer/README.md, scripts/win-installer/build-win-installer.ps1, scripts/win-installer/install-libsrt.ps1
- More comprehensive README.
- Added a sample installation script for users to automate the download and
installation of libsrt. Useful to automate user's CI/CD pipeline.
- Renamed typo in script name ("intaller").
- Updated build script to also produce the .zip archive as published with version 1.4.3.
But note that binaries don't compress well (only 2% space) and publishing a .zip
instead of the .exe does not provide much improvement anyway.
=> [build] Improved Windows installer

srtcore/core.cpp, srtcore/core.h, srtcore/queue.cpp, srtcore/queue.h
Fixes #2027
Fixed a problem: when `getNextAvailableUnit` returns NULL, the packet is read temporarily and dropped, as there's no possible storage where it could land. The problem is, however, that this packet's data were also necessary in some of the subprocedures in `updateConnStatus` and therefore it was being accessed (which was new towards UDT, and it's related to some bugfixes and additional data access necessity in case of HSv5).
The fix: the socket ID is pre-extracted (with fallback to 0 in case of lack of extracted unit) and wherever a packet is required to be accessed, a check for NULL is added, as well as a NULL pointer to a packet is now acceptable (replaced reference).
=> [core] FIX: Added check for NULL unit when passing to updateConnStatus

scripts/build-android/build-android, scripts/build-android/mkmbedtls, scripts/build-android/mksrt
Fixes #2022 
The fix: Always set OpenSSL paths explicitly. This works for new CMake 3.20 branch as well as for Ubuntu LTS's CMake 3.16.
Also this PR adds support for Mbed TLS build for Android.
=> Updates for Android build script

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/group.cpp, srtcore/group.h
Fix the issue memtioned in https://github.com/Haivision/srt/issues/1805#issuecomment-785260692
=> [core] use seq larger than m_RcvBaseSeqNo to update group readablity

.gitignore, CMakeLists.txt
Let CMake generate Compilation Database for LSP editor plugins.
=> [build] Added compile_commands.json to .gitignore

srtcore/buffer.cpp
Fixed a issue introduced by #2026 
The `skipData()` after `getRcvFirstMsg()` can only skip empty data,
while #2026 may skip multiple non-empty ready-to-play packets that smaller than group recv base.
=> [core] Fixed skip non-empty data

test/test_fec_rebuilding.cpp
This adds fixes:
1. Extended timeout for `srt_accept_bond` call to 2 seconds.
2. Preinitialized buffers for extracted FEC configuration (happened to be displayed with garbage contents)
3. Made the accept failure assert instead of expect (failure will only lead to other failures).
=> [test] Added fixes for FEC test occasional failure

apps/apputil.cpp
After PR #1743 json stats from `srt-live-transmit` has quotation marks around numerical values. Those quotes can be omitted.
TODO:
=> [apps] Output json stats values as numbers

srtcore/tsbpd_time.cpp
The refactoring in PR #1968 had removed TSBPD base update on incoming ACKACK control packet used for drift tracing.
At the same time `CTsbpdTime::getTsbPdTimeBase(uint32_t timestamp_us)` while in wrapping-aware state was only tracking for packet timestamps below the value of `TSBPD_WRAP_PERIOD` (30 s).
The wrapping period itself ends once a data packet with a timestamp in range `[TSBPD_WRAP_PERIOD; 2 * TSBPD_WRAP_PERIOD]` is received.
All these lead to an issue when an ACKACK packet with TS `30.000001` s arrives: the time base is not updated (like before), and the TS is already higher than `TSBPD_WRAP_PERIOD`, meaning that carryover correction is not applied.
This PR increases the carryover-applicable range for TS up to `2 * TSBPD_WRAP_PERIOD` in `getTsbPdTimeBase`.
Fixes #2041.
Further …
=> [core] Fixed getTsbPdTimeBase: carryover within 2 wrapping periods

srtcore/core.cpp
Extracted from PR #2046 by @gou4shi1.
Changes of the receiver buffer's state must be protected by `CUDT::m_RcvBufferLock` mutex.
Functions fixed:
- `CUDT::receiverBuffer(..)`
- `CUDT::recvfile(..)`
=> [core] Added missing RCV buffer lock in CUDT::receiveBuffer(..).

srtcore/epoll.cpp
epoll_create1() was added to the kernel in version 2.6.27. Library
support is provided in glibc starting with version 2.9 which was
released at the year of 2008.
=> [core] Set CLOEXEC for epoll on Linux

CMakeLists.txt, srtcore/logging.h, srtcore/platform_sys.h, srtcore/srt.h, srtcore/srt_attr_defs.h, srtcore/sync.h, srtcore/sync_posix.cpp, srtcore/udt.h
- Added Clang TSA attributes to run static analysis.
- Added CMake build option ENABLE_CLANG_TSA (disabled by default).
- `srt::sync::UniqueLock` now throws an exception from unlock and lock.
See also:
- [Thread Safety Analysis](https://clang.llvm.org/docs/ThreadSafetyAnalysis.html);
- [CLang Annotations](https://clang-analyzer.llvm.org/annotations.html#attr_nonnull);
- [Abseil thread annotations](https://abseil.io/docs/cpp/guides/synchronization).
=> [core] Added Clang TSA attributes.

srtcore/srt_attr_defs.h, srtcore/utilities.h
Moved compiler attribute definitions to a dedicated header `srt_attr_defs.h`.
=> [core] Moved compiler attribute definitions

docs/API/API-socket-options.md, docs/API/API.md, srtcore/socketconfig.cpp, srtcore/socketconfig.h, test/test_socket_options.cpp
Tests have confirmed the reduced retransmission algorithm provides better results both under artificial impairments and in real public networks. Making it the default one.
=> [core] Changed the default SRTO_RETRANSMITALGO to 1

configure-data.tcl, scripts/build-android/build-android, scripts/build-android/mkssl
- Select correct toolchain for OpenSSL (linux-x86_64 vs darwin-x86_64);
- Cross-build should get OpenSSL include dirs from command line, not host ones from brew;
- Minor tweaks to support zsh.
=> Cross-compile android from macOS host

srtcore/api.h, srtcore/core.cpp, srtcore/core.h, test/test_socket_options.cpp
`CUDT::m_PeerID` is not initialized by the constructor. It has a random (garbage) value until set during HS.
When a caller with a passphrase tries to connect to a listener without a passphrase, the listener sends a rejection conclusion HS.
The caller, receiving the HS, sees the rejection code (in `CUDT::processAsyncConnectRequest(..)`), and returns from the function without initializing `m_PeerID`.
As `processAsyncConnectRequest(..)` returns false, a SHUTDOWN control packet is sent from `CRendezvousQueue::updateConnStatus(..)`.
But destination SRT socket ID is still not initialized and may contain some garbage value, that could match some existing SRT socket ID on the listener side.
In the worst case, it could lead to a closure of a different valid connection existing on the same port, …
=> Fixed SHUTDOWN message with a wrong (uninitialized) DST socket ID

srtcore/core.cpp
If it does not, it will lead to a crash, reported in #1979.
The reason for it to happen is unclear. And it is rare. So an IPE will be shown in this case. It is better than a crash and will allow us to track the issue further.
=> [core] Check if CryptoControl exists in createSrtHandshake(..).

srtcore/congctl.cpp, srtcore/congctl.h, srtcore/core.cpp, srtcore/socketconfig.cpp
Renamed LiveCC and FileCC event-related functions:
- `updateSndPeriod` -> `onACK`
- `slowdownSndPeriod` -> `onLossReport`
- `speedupToWindowSize` -> `onRTO`
- `updatePktSndPeriod_onTimer` -> `onRTO`
Moved congestion control code into the `srt` namespace (partially addresses #1924).
Fixes #1526.
A couple of warnings fixed for #1646.
=> Renamed congestion control event-realated functions

srtcore/core.cpp, srtcore/queue.cpp
As described in #1979 in [this comment](https://github.com/Haivision/srt/issues/1979#issuecomment-896845181), if a socket was closed and already removed from the connection queue (`CRendezvousQueue`), it may still get itself to `vector<LinkStatusInfo> toProcess` in `CRendezvousQueue::updateConnStatus(..)`.
After PR #2075 nothing serious would happen. Still, it might be worth checking this situation earlier, and not even start to fill the response handshake.
The `CUDT::closeInternal` sets `m_bOpened = false` in the end under the `m_ConnectionLock`. So checking `m_bOpened` in the beginning of `CUDT::processAsyncConnectRequest(..)` would allow to return earlier.
Fixes #1979.
=> [core] Check if socket is still open before replying to HS

srtcore/utilities.h
On the Debian kfreebsd port, both endian.h and sys/endian.h are
available. After discussing with the kfreebsd port maintainer and since
this is userspace related, we should prefer the one from the glibc
See: #2066
=> [core] Prefer the endian.h header file from glibc if available

srtcore/api.h, srtcore/sync_posix.cpp
As reported in #1974, Win QPC frequency may be below 1 microsecond, which would result in a zero frequency value, eventually leading to a division by zero.
This PR sets the frequency to 1 and shows an error message instructing to consider using C++11 timing instead.
The reported mobile CPU Intel Core(TM) M-5Y10c CPU @ 0.80GHz 1.00GHz was released in Q1 2015.
Fixes #1974 as no further improvements are expected yet. Going to a floating-point frequency may influence SRT performance for general users. Will wait for further feedback with the error message shown to all affected users.
=> [core] Check Win QPC frequency is non-zero

test/test_ipv6.cpp
On systems with IPv6 support disabled the connection fails, but the blocking `DoAccept()` still waits for incoming connections (hanging forever).
Instead, if the caller fails to connect, it now closes the listening socket to break waiting for `srt_accept()`.
=> [tests] Fixed possible TestIPv6 hangups if connection fails

srtcore/api.cpp, srtcore/api.h, srtcore/core.cpp, srtcore/group.cpp
Previously `CUDTSocket was holding a pointer to the `CUDT` instance and actually owned it, as it was deleting the instance in its destructor. The `CUDT` was allocated and assigned to the pointer separately, which does not protect from someone wrongfully changing the pointer afterwards.
With this PR `CUDTSocket` owns a member CUDT class and constructs it within its own construction.
=> Rafactoring: CUDTSocket now owns a member CUDT class

test/test_file_transmission.cpp
The FileTransfer unit test tends to fail because it tries to bind to a port that is already in use.
This PR adds a search for an available UDP port.
=> [tests] Test FileUpload: find unused UDP port

apps/apputil.cpp, apps/apputil.hpp
The loop `for (auto s: scheme)` was crashing in `srt_test_multiplex` on MacOS likely due to a bad copy constructor. `s->names()` is an empty set. `s->names().count("i")` crashes.
=> [apps] Fixed loop over OptionScheme

CMakeLists.txt, docs/build/build-win.md, scripts/haiUtil.cmake
=> [build] Default STDCXX_SYNC=ON on Windows, try to use CLOCK_MONOTONIC by default on Linux.

srtcore/core.h
- [core] Removed redundant `srt` namespace scope resolution in `CUDT`
- [core] Added `SRT_ATTR_GUARDED_BY` to some members of `CUDT`. Imported from #1859.
=> Minor improvements: removed redundant srt namespace resolution

testing/srt-test-multiplex.cpp, testing/testactivemedia.hpp, testing/testmediabase.hpp
1. `testing/testactivemedia.hpp`:
```shell
error: ‘atomic’ in namespace ‘std’ does not name a type
```
2. `testing/testmediabase.hpp`:
```shell
error: use of deleted function ‘std::atomic<bool>::atomic(const std::atomic<bool>&)’
```
3. Workaround of the bad move semantics.
```c++
vector<OptionScheme> optargs = {
{ {"ll", "loglevel"}, OptionScheme::ARG_ONE },
{ {"i"}, OptionScheme::ARG_VAR },
{ {"o"}, OptionScheme::ARG_VAR }
};
```
`OptionScheme`'s `const OptionName* pid` does not own the `pid` object, so move constructor only copies the pointer. In the example above the pointer points to a temporal object `{ "ll", "loglevel" }`. GCC 4.5 removes this r-value object, and CLI parsing is performed incorrectly.
=> [apps] Fixed testing apps building with GCC 4.8

srtcore/group.cpp
Fix crash:
```
STACKTRACE   3 >>> /home/xxx/remote_server/lib/libpthread.so.0(+0x11390) [0x7fa906ed1390]
0x0000000000011390: __restore_rt at ??:?
STACKTRACE   4 >>> CRcvBuffer::getRcvReadyPacket(int)(+0x54b) </home/xxx/remote_server/lib/libsrt.so.1.4> [0x7fa90783820b]
0x000000000005120b: CRcvBuffer::getRcvReadyPacket(int) at ??:?
STACKTRACE   5 >>> CRcvBuffer::isRcvDataReady(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >&, int&, int)(+0x82) </home/xxx/remote_server/
lib/libsrt.so.1.4> [0x7fa907838692]
0x0000000000051692: CRcvBuffer::isRcvDataReady(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >&, int&, int) at ??:?
STACKTRACE   6 >>> …
```
=> [core] Added missing lock for isRcvDataReady()

CMakeLists.txt, apps/srt-tunnel.cpp, scripts/FindPThreadGetSetName.cmake, srtcore/srt_attr_defs.h, srtcore/threadname.h, test/test_threadname.cpp, testing/srt-test-multiplex.cpp, testing/srt-test-relay.cpp, testing/testactivemedia.cpp, testing/testactivemedia.hpp
1. Extracted `pthread_getname_np()` related changes from PR #2104 (by @jlsantiago0).
- Detect availability of `pthread_getname_np()`  and `pthread_setname_np()` functions in CMake.
- Use the `pthread_getname_np()`  and `pthread_setname_np()` functions if available in `ThreadName` class.
2. **Additional minor change in the second commit:** put `ThreadName` class inside `srt` namespace.
This fixes MacOS builds for MacOS <10.6 as `pthread_getname_np()` and `pthread_setname_np()` was introduced in MacOS 10.6 and is not available in MacOS 10.5 and earlier.
The rework of the `pthread_getname_np()` and `pthread_setname_np()` allows other operating systems that support the API to use it. For instance, these functions are available in many of the BSD variants, but maybe in a different header file …
=> [core] Detect pthread_getname* availability

CMakeLists.txt, scripts/CheckCXXAtomic.cmake, scripts/CheckGCCAtomicIntrinsics.cmake
This patch generalizes the detection of libatomic and whether it can/should be linked into the SRT library when linking with the static library.
Tested with Android and MacOS 10.5 builds.
=> Generalize libatomic Detection.

scripts/win-installer/libsrt.props
The libsrt is compiled for platforms Win32 and x64, the traditional
names with Visual Studio. Some applications are built with custom names,
typically x86 or Win64. This commit makes sure that these applications
use the correct libsrt platform.
=> Update Windows installer for alternate platform names

srtcore/threadname.h
Fixed security hotspot of using `strlen` identified by SonarCloud.
Using "strlen" or "wcslen" is security-sensitive.
=> [core] Avoid using strlen in ThreadName class

docs/features/access-control.md
=> [docs] Improved Access Control general syntax description

srtcore/congctl.cpp
PR #1997 introduced an issue in FileCC, where `genRandomInt(1, max)` can be called with `max=0`. This results in an invalid call, as it means a request to generate a random value in range [1; 0].
=> [core] Fixed FileCC random decrease

CMakeLists.txt
Noticed test-srt ending up in a distro package.  
I assume its not really needed in a typical runtime environment
=> [build] Build but do not install test-srt

srtcore/platform_sys.h
Fix for this warning:
~~~
srt/platform_sys.h:48:5: error: "__APPLE__" is not defined, evaluates to 0 [-Werror=undef]
48 | #if __APPLE__
|     ^~~~~~~~~
~~~
With clang, it is possible to use a pragma diagnostics before `#include <srt/srt.h>` to mute the warning.
With gcc, however, the situation is critical. Although the same pragma exists, it does nothing due to a known gcc bug since 2012, never fixed. Apparently, the bug appears too early in the lex analysis phase and #pragma are not yet parsed. It seems a bit difficult to solve and nobody wanted to fix it in 9 years.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53431
The problem is important in applications with a strict "no warning policy" (`-Wall -Wextra -Werror`). If a warning is impossible to mute, the compilation fails.
Note: …
=> Fixed 'undef' warning with gcc and clang

scripts/iOS.cmake
Fixed CMake warning for iOS target:
```shell
CMake Warning (dev) at .../srt/scripts/iOS.cmake:154 (set):
implicitly converting 'string' to 'STRING' type.
CMake Warning (dev) at .../srt/scripts/iOS.cmake:157 (set):
implicitly converting 'string' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
`string` is not a type, but an operation. See [here](https://cmake.org/cmake/help/latest/command/string.html).
Use uppercase `STRING` instead. See [`set()` command](https://cmake.org/cmake/help/latest/command/set.html?highlight=set).
=> [build] Fixed CMake warning about string

CMakeLists.txt, scripts/CheckGCCAtomicIntrinsics.cmake
Earlier versions of the NDK need to link against `libatomic` when compiling statically.
Even tho the test does not seem to require it, remove UnSetVariableFull it is not actually doing what I intended.
Citing @jlsantiago0:
> For Android, the `-Wl,--exclude-libs,libatomic.a` gets added to the link options but only for the rules when statically linking the SRT library to SRT the applications.
It only happens for some of the NDK versions. I don't know which ones in particular as I am currently only testing r16b and r21. r16b needs it or the build breaks for about half of the architectures. r21 doesn't need it, but it is fine if we link against it anyway. But it is likely that the other reported Android build failures are using other versions of the NDK than I am.
> 
> Ordinarily, the …
=> [build] Fix build Android with NDK <17.

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/group.cpp, srtcore/group.h, srtcore/tsbpd_time.cpp, srtcore/tsbpd_time.h
When a group member updates its clock drift value and potentially the TSBPD base time, all other members need to be synchronized to use the same value.
Previously, the minimum drift value and the minimum TSBPD base time among all group member was taken as a reference, which resulted in bad behavior.
Having the improved drift tracer logic (PR #1965) now allows to do a proper synchronization of group members,
**Network**: Win 10 <--> 1Gbps switch <--> CentOS 7.
**Network impairments**: RTT 40 ms, 1% packet loss.
**SRT latency**: 120 ms.
Both broadcast group transmission and single path transmission are running in parallel over the same local switch as described below.
```shell
(broadcast group sender)
srt-xtransmit generate srt://192.168.0.7:4200 srt://192.168.0.7:5200 --sendrate 10Mbps …
```
=> Fixed group drift synchronization

srtcore/common.h, srtcore/group.cpp, srtcore/list.cpp, test/test_seqno.cpp
There is an issue with the discrepancy check of packet sequence number performed by a group reader.
The issue was originally described in #2138 (issue no. 1 of 2).
A group reads packet with sequence number `0x7FFFFFFF` (maximum seqno value).
The base seqno `m_RcvBaseSeqNo` of a group reader is set to `0x7FFFFFFF`.
The next expected packet number is 0. However, once a packet with seqno 0 (`mctrl.pktseq = 0`) is read from one of group members, the following check evaluates into `true`, and a sequence discrepancy is wrongfully detected. 
```c++
abs(m_RcvBaseSeqNo - mctrl.pktseq) > CSeqNo::m_iSeqNoTH)
```
The member socket is then identified as broken and is to be closing. Closing this socket results in the issue no.2 described in #2138. Issue no. 2 is not addressed in this PR.
Check the …
=> Fixed checking the packet seqno validity when reading from a group member

apps/apputil.cpp, apps/apputil.hpp, apps/srt-file-transmit.cpp, apps/srt-live-transmit.cpp
- Moved SRT version printing to a separate function.
- Added printing clock type in `srt-live-transmit` and `srt-file-transmit` on `-version` and `-help` flags.
Example output:
```shell
./srt-live-transmit -version
Built with SRT Library version: 1.4.4
SRT Library version: 1.4.4, clock type: MACH_ABSTIME
```
=> [apps] Print SRT version and clock type

srtcore/buffer.cpp, srtcore/buffer.h
Moved SND and RCV buffers into the `srt` namespace.
Related to #1924.
=> [core] Moved SND and RCV buffers into the 'srt' namespace

CMakeLists.txt, srtcore/buffer.cpp, srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, test/test_buffer.cpp
- Fixed partial reading of packets from the RCV buffer in stream mode.
- Added unit tests for stream mode.
- Removed unused `SRT_DEBUG_TSBPD_DRIFT`.
Some fixes for read-readiness state tracking regardless of the packet border flag (FIRST, LAST).
Related to #2179 (maybe fixes, but to be further verified).
The new receiver buffer was introduced in PR #1964.
=> Fixed the new RCV buffer in STREAM mode

srtcore/strerror_defs.cpp, srtcore/utilities.h
Added missing include of `<stdexcept>`.
Also there are several versions of the `runtime_error` constructor:
```c++
std::runtime_error( const std::string& what_arg ); // C++03
std::runtime_error( const char* what_arg );  // since C++11
```
The error message argument of the `std::runtime_error` is copied to an internal member of the `runtime_error`, so the initial object does not have to remain valid after an exception is thrown.
If C++03 is used, an implicit conversion from `const char*` to `std::string` should happen.
- `m_strIndexErr` could be defined in `srterror_defs.cpp`.
=> [core] Fixed std::runtime_error usage (use C++03 version instead of C++11)

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/core.h
The source time for a message can be provided using the [`SRT_MSGCTRL`](https://github.com/Haivision/srt/blob/v1.4.4/docs/API/API-functions.md#SRT_MSGCTRL) structure:
```c++
typedef struct SRT_MsgCtrl_
{
// …
int64_t srctime;             // Source time, in microseconds since SRT internal clock epoch
// …
} SRT_MSGCTRL;
```
**Currently,** inside SRT a message gets two timestamps:
1. Submission timestamp (`tsOriginTime`), which is used for:
- SND Too-Late Packet Drop;
- TTL Message Drop (not to be confused with IP_TTL);
- SND buffer timespan (stats).
2. Source timestamp if provided (`tsSourceTime`)
- Data Packet Timestamp
**This PR** keeps only one timestamp for everything (source time if provided, otherwise submission time).
**Note:** Extracted from #2180.
=> Prefer Using Source Time if Provided

docs/API/API-functions.md, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp
I found that in message mode, messages are often sent after TTL due to congestion control.
=> [core] Both readData() consider msgttl

srtcore/channel.cpp
This resolves Solaris unit tests failures caused by `srt::CChannel::setUDPSockOpt()` calling `setsockopt()` which can return failure when attempting to increase the `SND`|`RCV` buffers in excess of the system maximums, but still sets the buffersize to the system max.
The unit tests now PASS and SRT now works in HVIORouter.
=> [bug] Fix UDP RCV and SND buffer size settings

srtcore/list.cpp
During the debug of https://github.com/Haivision/srt/issues/2192, I found that `m_iTail` would not be reset to `-1`, although it's harmless, let's keep member variables consistent.
=> [core] fix CRcvLossList::m_iTail not reset to -1

srtcore/list.cpp, srtcore/list.h
fix https://github.com/Haivision/srt/issues/2192#issuecomment-983376741
Previously, these is a comment saying that `Data to be inserted must be larger than all those in the list, guaranteed by the UDT receive`, let's guarantee this by the internal check.
=> [core] make sure data to be inserted into CRcvLossList are monotonic

srtcore/group.cpp
Fix #1805 since #1835 lacks activity for several months.
* If `ready_sockets()` is empty, epoll readiness should be updated to false, othrewise, application may keep re-polling this group.
* if `nready == 0`, epoll readiness should also be updated to false. (This change was extracted from #2046)
* `m_bNewRcvReady` of #1835 should be useless since `recv_WaitForReadReady()` also checks `m_pRcvBuffer->isRcvDataReady()` under protection of `m_GroupLock` and `m_RcvBufferLock`. The `Not available AT THIS TIME, but TSBPD provided new one` log from that PR was never been printed in my prod.
=> [core] fix recv_WaitForReadReady() return empty

srtcore/buffer_rcv.h, srtcore/core.cpp, srtcore/core.h, srtcore/group.h
Fix #2186 and part of #2046.
I noticed that the return value of `ackDataUpTo()` is only used to update group readiness, so it should use the last readable seq.
More PRs will be extracted from #2046, base on the new rcv buffer.
=> [core] fix m_GroupOf->updateReadState() in message mode

srtcore/core.cpp
In bidirectional transport mode, in some cases, RTT is never updated, maybe a spelling mistake?
=> [core] Fix rtt estimate in bidirectional mode

srtcore/core.cpp
Fixed the issue with RTT in case of bidirectional transmission introduced when adding atomic types in PR #1863.
I've also checked all the atomic related changes. They are not affecting RTT logic anywhere else luckily.
Replaces PR #2208.
=> [core] Fixed the issue with RTT in case of bidirectional transmission

docs/apps/srt-live-transmit.md
Updated after the change that caller mode can also specify `adapter`.
Additionally some general refactoring and completion of the lacking information.
=> [docs] Updated options description for srt-live-transmit

docs/API/statistics.md, srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/core.cpp, srtcore/core.h
The receiver buffer may have packets dropped by sender (marked as `EntryState_Drop`).
In that case, the ACK position is likely ahead of the current reading position. This has to be taken into account in the TSBPD thread.
It can result in the receiver hanging up for a couple of seconds, making the sender break the connection.
1. At some point, the receiver hangs up (for about 12 seconds in total) due to the issue fixed above.
2. Three seconds later the sender detects there is no response from the receiver, and breaks the connection.
3. About ten seconds later receiver wakes up and continues processing incoming packets, that were accumulated in the system buffer of the UDP socket. 
4. Because of that stall it receives heavily delayed ACKACK packets. Based on the ACK - ACKACK pair of packets …
=> [core] Fixed RCV TL drop of packets dropped by SND

srtcore/core.cpp, srtcore/core.h
The new function `CUDT::dropTooLateUpTo(..)` added in PR #2214 is expected to work only with the new receiver buffer, thus breaking the build if the old receiver buffer is enabled.
This PR enables the function only if the new receiver buffer is used.
=> [core] Fixed build with the old RCV buffer

srtcore/buffer_rcv.cpp
Fixed the crash mentioned in https://github.com/Haivision/srt/pull/2223#issue-1098910115
`m_iMaxPosInc` should be sync with `m_iStartPos`
=> [core] fix m_iMaxPosInc was not updated in releaseNextFillerEntries()

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h
=> [core] add CRcvBufferNew::dropUnitInPos() to simplify dropUpTo() and dropMessage()

srtcore/buffer_rcv.cpp
=> [core] CRcvBufferNew::dropUpTo() able to drop non-empty units

srtcore/core.cpp
Try to fix this crash:
```
16:21:32.786189819 : STACKTRACE  10 >>> /home/xxx/remote_server/lib/libstdc++.so.6(+0xa5811) [0x7efcceccf811]
16:21:32.786190773 : 0x00000000000a5811: std::terminate() at ??:?
16:21:32.786191903 : STACKTRACE  11 >>> /home/xxx/remote_server/lib/libstdc++.so.6(+0xa5a65) [0x7efcceccfa65]
16:21:32.786193209 : 0x00000000000a5a65: __cxa_throw at ??:?
16:21:32.786194146 : STACKTRACE  12 >>> srt::CRcvBufferNew::getTimespan_ms() const(+0xc8) </home/xxx/remote_server/bin/remote_server> [0x55b19eb78508]
16:21:32.786195049 : 0x0000000000131508: srt::CRcvBufferNew::getTimespan_ms() const at /.../srt/srtcore/buffer_rcv.cpp:559
16:21:32.786197136 : STACKTRACE  13 >>> srt::CRcvBufferNew::updRcvAvgDataSize(std::chrono::time_point<std::chrono::_V2::steady_clock, …
```
=> [core] fix missing m_RcvBufferLock in processCtrlDropReq()

srtcore/buffer.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/queue.cpp, test/test_buffer.cpp
The code related to forming an original data packet for sending has been moved to a separate function `packUniqueData(..)`.
The encryption of the payload has been moved inside that function as well, as it is only needed to encrypt the original payload. Once encrypted, it is stored so in the sender buffer, thus the second encryption call is needed when the packet is being retransmitted.
Moving the encryption inside the `packUniqueData(..)` also means that packet timestamp and destination socket ID are not yet set in the header of the packet. However, only the packet sequence number is used as the counter for the AES encryption, therefore this change is safe.
Changes extracted from PR #2180.
Checked encryption and decryption including KM refresh using `srt-xtransmit`:
```shell
(receiver) …
```
=> [core] Refactoring: added packUniqueData(..) function

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp
Use SND buffer delay for TL Packet Drop instead of the timespan between the first and the last packet in the buffer.
Sender dropping logic is applied if the sender buffer timespan exceeds `drop_threshold_ms`.
Instead, the delay of the oldest packet in the buffer should be used (`Tnow - OldestPacketTS`).
This also correlates with the usage of the source time if provided to calculate the timestamp, which was not the case previously (PR #2185).
As before, only packets older than `Tnow - drop_threshold_ms ` are dropped by the sender.
Fixes #898.
For some reason the lock was missing from the `CSndBuffer::readData(CPacket& w_packet, ..)`.
=> [core] Use SND buffer delay for TL Packet Drop instead of the timespan

srtcore/congctl.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/stats.h
Fixes #713.
1. Don't reschedule sending (keep pacing) on
- SND drop,
- NAK received
- retransmission timeout.
2. Added pacing amendment after sending probing packets.
Changes extracted from #2180.
=> [core] Fix MaxBW limitation

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/core.h
In the live streaming configuration with TL Packet Drop enabled original packet must have priority over packet retransmission because:
- The earlier the latest original packet reaches the receiver, the better the end-to-end latency constraint is kept as the receiver can detect too late packets earlier.
- If original packets are accumulating in the sender buffer, there is a network congestion, and likely most of the packet retransmissions won't reach the receiver. Therefore it is better to prioritize a more up-to-date payload, preserve the end-to-end latency and keep the jitter low. Once congestion is over, the streaming can be restored quicker.
- In-order but belated packets have a negative impact on jitter and end-to-end latency.
Proposed sending priority (for Live Configuration Only): …
=> Revised SND DROP and SND pacing logic

srtcore/core.cpp
Improved the condition for `smoothed_rtt` recalculation in the case of bidirectional transmission. See the [following comment](https://github.com/Haivision/srt/pull/2210#issuecomment-1026595026) and the correspondence in PR #2210 for details.
=> [core] Improved the condition for smoothed_rtt recalculation

docs/apps/srt-live-transmit.md
Add usage examples for these tools, which are part of the ffmpeg distribution, because not everyone will have access to a version of VLC (yet) which supports SRT, the reason being that VLC build configuration only accepts older versions of SRT, see https://github.com/videolan/vlc/blob/3.0.16/configure.ac#L4019.
=> srt-live-transmit.md: add ffplay, ffprobe examples

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/core.cpp, srtcore/core.h, test/test_buffer.cpp
Set the peer rexmit flag on the receiver buffer in `srt::CUDT::updateSrtRcvSettings()` instead of passing it on the construction time, as the value is not yet retrieved from the handshake. Fixes #2227. Affected SRT v1.4.5-dev.
There is already the TSBPD flag set in `srt::CUDT::updateSrtRcvSettings()`, ruining the RAII approach.
It would be better to pass both the "peer rexmit flag" and the TSBPD flag in the receiver buffer constructor and make them constant. However, it would touch too much code around the handshake flow with a high risk to introduce more bugs.
=> [core] Fixed setting the peer rexmit flag on the RCV buffer

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/group.cpp
Replace #2046.
Fix #2138 btw.
* The previous `Group::recv()` does not support to read a message that across multiple packets.
* Reduce `Group::recv()` from 500+ lines to 100+ lines.
=> [core] refactor Group::recv() base on new rcv buffer to support message mode

srtcore/group.cpp
Broken after merging #2218, that was using the old naming of the function.
=> [core] Fixed rcvDropTooLateUpTo calls.

srtcore/core.cpp, srtcore/core.h
* Decouple `group_read_seq` from `ackDataUpTo()`.
* If new recv buffer enabled, use `getFirstReadablePacketInfo()` instead of `getAvailablePacketsRange()` to support out-of-order messages. This need #2207 to make sure `getFirstReadablePacketInfo()` will not return seq behind `group_read_base`.
* If new recv buffer disabled, use `decseq(ack)` instead of `ack`.
=> [core] Improved group readiness updating in sendCtrlAck()

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/core.cpp
PR #1964 has changed the handling of [the message drop request](https://datatracker.ietf.org/doc/html/draft-sharabayko-srt-01#section-3.2.9) from the sender.
In particular, previously sender's requests to drop packets in the provided range from the receiver buffer were ignored expecting them to be anyway dropped as too late. Corresponding records are removed from the receiver's loss lists anyway to stop retransmission requests of those packets.
PR #1964 implemented the logic of handling sequence-number-based drop requests from the sender. However, this leads to dropping packets that are present in the receiver buffer and actually can be properly delivered to an upstream application.
In fact, only packets referring to a several-packets-long message have to be dropped, and only if at least …
=> Fixed handling SND drop request

docs/build/build-options.md
Describe CMake build options of SRT, reference corresponding option of the configure script. Previously only the `configure` script options were listed.
PR on behalf of @stevomatthews
=> [docs] Reworked the build options document.

apps/socketoptions.hpp, docs/API/API-socket-options.md, docs/apps/srt-live-transmit.md, srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp, srtcore/group.h, srtcore/socketconfig.cpp, srtcore/socketconfig.h, srtcore/srt.h, test/test_socket_options.cpp
`SRTO_GROUPMINSTABLETIMEO` is a socket option for SRT socket group. It does not do anything when set on an individual socket, but when set on a listener socket - it is used to derive the value for a group. Defines the minimum value of the stability timeout for a member socket to be considered unstable.
Fixes #1792
Fixes #2254 (a typo).
=> [core] Repurpose SRTO_GROUPMINSTABLETIMEO

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/common.cpp, srtcore/common.h, srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp, srtcore/group_backup.h
In the source (input) rate estimation configuration (`SRTO_MAXBW=0`, `SRTO_INPUTBW=0`) SRT estimates input rate based on the data coming from the app via `srt_sendmsg2(..)`. The estimate is used to set the maximum BW limit and pacing rate of sending.
In the main/backup mode an inactive member does not get any data for sending and does not perform any rate estimation.
Once it is activated, the rate estimator state is taken from an active member and assigned to this newly activated member.
⚠️  An activated member would instantly get all unacknowledged packets from the active member. However, those packets already have source timestamps. The source rate estimation honors these timestamps, but uses it only to estimate the interval. The estimate would then be overestimated a bit.
Fixes #2122, …
=> Backup groups: Take source rate estimate from an active link on idle member activation

srtcore/core.cpp
Fix #2236:
The `need_notify_loss = false` was introduced by #1448, according to https://github.com/Haivision/srt/pull/1448#issuecomment-1054299732
> This is to prevent checking for loss for a freshly turned-to-running link. If this isn't done then the sequence distance between the last reception - which in this case, as a group member, is artificially updated to be in synch with other links in the group - and the current packet reception would be treated as loss and loss-reported. This actually isn't a loss because the "previous" sequence is not really a received packet sequence. After turning to RUNNING state though since this moment this range should be treated as a loss.
But it also introduces another bug #2236
I have carefully checked  `synchronizeWithGroup()`, `updateIdleLinkFrom()`, …
=> [core] fix unrecoverable initial packets lose in group message mode

srtcore/core.cpp
Previously, if the extraction seq is differ from scheduling seq, only some debug logs will be printed, and a dropreq will be sent, but the extraction seq will not be overridden (even for the first packet).
As https://github.com/Haivision/srt/pull/1119#issuecomment-1059311728 said, we should use scheduling seq in group.
I will keep watching the error logs to see if we can safely override extraction seq with scheduling seq.
=> [core] Fix extraction seq with scheduling seq in group.

.travis.yml
Was using `OpenSSL_1_1_1-stable` branch. The branch could be updated with new commits, possibly making the build to fail.
=> [build] Travis MinGW job now uses OpenSSL 1.1.1g

srtcore/api.cpp, srtcore/api.h
These formatting changes anticipate the upcoming (potential) refactoring and fixes of certain functionality located in the `api.cpp` and `api.h` modules. For example, the `CUDTUnited::newConnection(..)` has to be refactored, as it does too many things (finds existing associated connection, creates the new one, sends HS conclusion response, etc.).
=> [core] Applied clang-format on api.h and api.cpp.

srtcore/core.cpp
If packet reordering happens on the network and an ACKACK packet arrives out of order, it affects the accuracy of RTT estimation. However, it might be better to use the "note" log level as it is not that critical for the library. However, it might be a good hint for potential issues related to network conditions, therefore the "note" level should work well.
=> [core] Downgrade ACKACK reorder log to Note

srtcore/queue.cpp
The `CSndUList::signalInterrupt()` and `CSndUList::realloc_()` are using `Condition::notify_all()` (`pthread_cond_broadcast`) to notify the sending queue is non empty or needs to be interrupted and closed.
The only receiver of this notification is the `CSndQueue::worker(void*)` thread. As of now, there is only one instance of this thread, and there is no need to use the broadcast notification.
_Note. Can the `notify_all()` be less performant than the `notify_one()`?_
SRT version: SRT v1.4.4, after PR #2045.
=> [core] CSndUList use notify_one() instead of notify_all()

srtcore/core.cpp, srtcore/group.cpp
As
```
volatile int32_t     m_iLastSchedSeqNo; // represetnts the value of CUDT::m_iSndNextSeqNo for each running socket
```
said, `m_iLastSchedSeqNo` should be "the first seq of next message to send" instead of "the first seq of last message that has been sent",
as `m_iLastSchedSeqNo` will be used as ISN when a new link is connected.
```
if (m_iLastSchedSeqNo != -1)
{
w_snd_isn = m_iLastSchedSeqNo;
IF_HEAVY_LOGGING(update_reason = "GROUPWISE snd-seq");
}
```
Btw, we should use `atomic` instead of  `volatile`?
=> [core] fix `CUDTGroup::m_iLastSchedSeqNo` was not updated correctly

srtcore/atomic.h
Previously it prefer to define `ATOMIC_USE_GCC_INTRINSICS` which in terms use  `volatile`, but [in C++11, we should use `std::atomic` for concurrency](https://xavierlamorlette.fr/cpp/effective_modern_cpp/#Item_40_-_Use_std::atomic_for_concurrency,_volatile_for_special_memory).
=> [core] prefer to use `std::atomic` if available

srtcore/group.cpp, srtcore/group.h
Replace `volatile` with `srt::sync::atomic` for concurrency.
Fix https://github.com/Haivision/srt/pull/2264#issuecomment-1098023860
=> [core] fix `volatile` in `group.h`

srtcore/buffer_rcv.cpp
1. Fixed possible null pointer object call. Checking `iLastPos`, but accessing the `m_iStartPos` potentially `NULL`.
```c++
if (m_entries[iLastPos].pUnit)
{
ss << ":";
const uint32_t usPktTimestamp = m_entries[m_iStartPos].pUnit->m_Packet.getMsgTimeStamp();
ss << count_milliseconds(m_tsbpd.getPktTsbPdTime(usPktTimestamp) - tsNow);
ss << " ms";
}
```
2. Show the first valid packet info `getFirstValidPacketInfo()` instead of `m_iStartPos` - the very first position in the buffer. Even if there is a gap in the beginning.
3. Show receiver buffer timespan instead of the TSBPD ready time span.
=> [core] Fixed CRcvBufferNew::strFullnessState(..).

srtcore/buffer_rcv.cpp, srtcore/utilities.h
- Defined an iterator for the `srt::FixedArray`. Also fixes potentially throwing an exception from the `CRcvBufferNew` destructor because the `operator[]` was used.
- Removed the member variable holding the error string. Instead form the string dynamically.
=> srt::FixedArray: define an iterator, changed exception throwing.

srtcore/md5.cpp, srtcore/md5.h
This renames the private md5 functions by adding srt_ prefix.
Otherwise, the md5 functions are shown as multiple definition
while static linking in presence of other libraries.
=> [core]: Fix name conflict with md5 functions

srtcore/api.h, srtcore/core.cpp, srtcore/handshake.h, srtcore/sync.h
1. Check if `CryptoControl` exists in `craftKmResponse(..)`. Fixes #2231.
2. Cleaned up the `CUDT::processConnectRequest(..)` function.
- ⚠️  Update listener write-ready only after the new connection. Was changed in #1650, but must not be done at all #1831.
=> Fixed crash in craftKmResponse due to CryptoControl being NULL

srtcore/buffer_rcv.h, srtcore/core.cpp
Use `m_RecvLock` instead of `m_RcvBufferLock` since the above `m_pRcvBuffer->applyGroupTime()` is protected by `m_RecvLock`, maybe we should change to `m_RcvBufferLock` consistently?
=> [core] fix `CRcvBufferNew::m_iStartSeqNo` was not sync in group

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/core.cpp, srtcore/core.h
The new receiver buffer keeps track of the packet sequence number in the starting position to be independent from SRT receiver ACK position.
As the receiver buffer is created **before** the connection is actually being established (see #2268), the starting sequence number has to be updated afterward.
- In particular, in the rendezvous connection mode both parties come with its own ISN. The negotiated ISN is the one from the party that has become INITIATOR after the cookie contest. The ISN has to be updated. Fixes #2306.
- Another source of the update is group connections, each having its own receiver buffer, that has to be synchronized at the start (and already after an individual connection has been established).
This PR adds an update of the RCV buffer's starting seqno.
=> [core] Fixed updating new RCV buffer on ISN change.

scripts/build-android/mkssl
The openssl share library file name always end with its version string, and then create soft link point to it. e.g.
libssl.so.1.1
libss.so -> libssl.so.1.1
libcrypto.so.1.1
libcrypto.so -> libcrypto.so.1.1
But in the Android NDK build, it only copy these .so extension files, that would cause crash because of it can not find the real xx.so.xx file.
Add the "SHLIB_EXT=.so" parameter to remove version extension file, this will make it easy to build with openssl .so file for android.
Please let me know if there is any question, thanks a lot.
=> [build] build openssl share library without version extesion for android

srtcore/core.cpp, srtcore/core.h
There were several examples that did not require C++11, although some of them do.
This fix allows all examples that don't require C++11 to be compiled using the compiler-default standard, while those that require C++11 are turned off in case when C++11 is explicitly disabled. Examples that do require it are sendfile/recvfile because they make use of in-application logging configurtion.
=> Allow non-C++11 examples to be compiled with C++11 disabled

srtcore/buffer_rcv.cpp
Mainly conversions to `int`.
Related issue #1646
=> [core] Fixed minor compiler warnings in RCV buffer

docs/API/API-functions.md, srtcore/api.cpp, srtcore/core.h, srtcore/group.cpp, srtcore/group.h, srtcore/srt.h, srtcore/srt_c_api.cpp
Removed unused `srt_include(..)` and `srt_exclude(..)` for unimplemented externally managed groups.
No reason to have these API functions if they are not needed.
Blocks #2316
=> [API] Removed unused srt_include(..) and srt_exclude(..)

CMakeLists.txt, examples/recvfile.cpp, examples/sendfile.cpp
`recvfile` and `sendfile` examples do not depend on `apps/logsupport.cpp`.
A follow-up fix after PR #2319.
=> [build] Sendfile and recvfile examples don't need logsupport.

testing/testmedia.cpp
Fixed the testing apps (`ENABLE_TESTING`) referencing previously removed `srt_group_configure()` function.
A follow-up fix for PR #2316.
=> [apps] Removed calls to non-existing srt_group_configure() function.

srtcore/core.cpp
The `m_HSGroupType` is set in `CUDT::runAcceptHook(..)`. But if listener callback is not configured, the `CUDT::runAcceptHook(..)` is never called, and  `m_HSGroupType` remains undefined.
Fixes #2175.
=> [core] Fixed setting group type on a socket accepted w/o listener callback

docs/API/API-functions.md
Added an example for the `srt_getsockname(..)` API function to avoid possible confusion like the one in #2334.
=> [docs] Added an example for srt_getsockname API function.

srtcore/core.cpp
The function `srt::CUDT::setInitialRcvSeq(..)` was mistakenly placed under the `#ifdef ENABLE_NEW_RCVBUFFER`.
That hides it from the linker when building with `-DENABLE_NEW_RCVBUFFER=OFF`.
Moved outside of the `ifdef`.
=> [core] Fixed build with the old receiver buffer.

docs/API/API-socket-options.md
Fixed retransmit algorithms naming plus added the link for Medium article.
=> [docs] Fixed retransmitalgo naming plus added the link for Medium article

docs/API/API-functions.md
=> Added a note on srt bind acquire not working with connected UDP socket

configure-data.tcl
1. Removed some no longer used options and added lacking cmake-option-reflexive options
2. Renamed experimental-bonding to bonding
3. Reordered options so that they match the order of option variables in cmake
=> [BUILD] Synchronized changes in configure script with latest changes

CMakeLists.txt
`make install` installs example apps and testing apps when those are enabled in the build.
This PR excludes those from being installed.
=> [build] Do not install examples and testing apps

docs/API/API-socket-options.md, docs/build/build-options.md
- Added `ENABLE_BONDING` build option description,
- Change version from 1.4.5 to 1.5.0 for some of the build and socket options.
=> [docs] Improved build and socket options description for v1.5.0

docs/API/API-functions.md, srtcore/group.cpp, srtcore/srt_c_api.cpp
ABI compatibility issues of SRT built with (`-DENABLE_BONDING=ON`) and without (`-DENABLE_BONDING=OFF`) socket groups as reported by [ABI Compliance Checker](https://lvc.github.io/abi-compliance-checker/).
=> [API] Fixed ABI compatibility issue with bonding enabled and disabled.

docs/features/access-control.md
Avoid confusion around the Stream ID.
Fixes #2281.
=> [docs] Improved the access control document.

docs/API/API-socket-options.md, docs/API/API.md
Starting from some versions of SRT the `SRTO_LINGER` is disabled by default in the live configuration
The documentation misses this point.
The following sections/documents are updated in this PR:
- [API-socket-options.md#SRTO_LINGER](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#SRTO_LINGER)
- [API.md#transmission-method-live](https://github.com/Haivision/srt/blob/master/docs/API/API.md#transmission-method-live)
Fixes #2289
=> [docs] Fixed SRTO_LINGER default values.

docs/build/build-options.md, docs/features/bonding-intro.md, docs/features/socket-groups.md
Minor improvements to Connection Bonding documentation:
- Fixed headings and formatting in some of the documents,
- Updated `ENABLE_BONDING` build option description.
=> [docs] Minor improvements to Connection Bonding documentation

srtcore/buffer_rcv.h, srtcore/core.cpp
Truncation from 'int' to 'bool'.
Fixes #2360.
=> [core] Fixed CUDT::packUniqueData return value.

README.md, docs/README.md, docs/build/build-android.md, docs/build/build-iOS.md, docs/build/build-linux.md, docs/build/build-macOS.md, docs/build/build-win.md
Improved the main README of the SRT project:
- Refactored and updated README structure as discussed in #1779.
- Added the table with quick links in the "Getting Started" section as suggested by Steve.
- Moved Build Instructions in separate documents under `docs/build`.
- Added "Features", "Sample Applications and Tools", "Contributing", "License", "Release History" sections.
Fixes #1779.
=> [docs] Improved the main README of the SRT project

srtcore/core.h, srtcore/packetfilter.h, srtcore/srt_attr_defs.h
SAL supports only one argument per function call. Added SRT_ATTR_REQUIRES2 to handle two independently.
Fixes #2362.
=> [core] Fixed warning on SRT_ATTR_REQUIRES.

srtcore/core.cpp, srtcore/fec.cpp, srtcore/fec.h, srtcore/stats.h, srtcore/utilities.h
- Explicitly compare with enum type. Fixes #2374.
- Fixed local variable 'i' hiding previous local declaration. Fixes #2371.
- Fixed 'false' value implicitly casting to an integer. Also some other minor warnings. Fixes #2372. Fixes #2370.
Partially addresses #1646.
=> Fixed some warning

srtcore/queue.cpp, srtcore/queue.h
Used for setting the RcvQueue:: worker thread name for logging.
Data race between `CRcvQueue::init()` and starting `srt::CRcvQueue::worker(void*)`.
=> [core] Made CRcvQueue::m_counter atomic to avoid data race.

srtcore/api.cpp
=> [core] Rethrow an exception without copying it.

srtcore/group.cpp
The original code
```
vector<SocketData*> successful, blocked;
const int blocklen = blocked.size();
stat = d->ps->core().sendmsg2(buf, blocklen, (w_mc));
```
is weird, correct me if I'm wrong :)
=> [core] fix sendBroadcast() use the size of blocked sockets as the size of buf to send

docs/API/API-functions.md
`srt_epoll_uwait` was meant instead of `srt_epoll_wait`.
=> [docs] Fixed a typo in srt_epoll_uwait

srtcore/api.cpp, srtcore/queue.cpp, srtcore/queue.h, test/test_buffer.cpp, test/test_unitqueue.cpp
Extracted undisputed changes from PR #2395.
The re-estimation of the number of units taken in the `CUnitQueue` was previously done as a workaround for synchronization issues around simultaneous access to `CUnitQueue::m_iCount`.
Those issues should be fixed by now, e.g. #1333.
No point in this CPU-heavy loop anymore.
```c++
while (p != NULL)
{
CUnit* u = p->m_pUnit;
for (CUnit* end = u + p->m_iSize; u != end; ++u)
if (u->m_iFlag != CUnit::FREE)
++real_count;
if (p == m_pLastQueue)
p = NULL;
else
p = p->m_pNext;
}
```
Previously `CUnitQueue` was tracking IP version. The value was submitted in `CRcvQueue::init(..)`, and used by `CRcvQueue::worker(..)` thread. There is no use for the value in the `CUnitQueue` itself.
Therefore, moved to `CRcvQueue`.
An exception was being caught in a named …
=> Improving CUnitQueue performance: don't adjust mcount

test/test_bonding.cpp
In the Bonding.CloseGroupAndSocket unit test (If a listener is not available) the following IPE situation can happen when sockets already removed from the epoll are being removed again.
Added ASSERT_GT(epoll_res, 0) to fail the test if epoll returns an error.
```shell
[ RUN      ] Bonding.CloseGroupAndSocket
22: Created group socket: 1405307167
22: Connecting two sockets 
22: Socket created: 331565342
22: Listen: wait for acceptability
22: Socket created: 331565340
22: Returned from connecting two sockets 
22: Listen: reported 1 acceptable and 0 errors
22: Listener will read packets...
22: Epoll result: 2
22: Epoll rlen: 0, wlen: 2
22: Epoll write[0]: 331565342 (removed from epoll)
22: Epoll write[1]: 1405307167 (removed from epoll)
22: Connect callback. Socket: 331565340, error: 1001, …
```
=> [tests] Minor fix for Bonding.CloseGroupAndSocket

haicrypt/cryspr-mbedtls.c
This change creates and initialises a message digest context inside the password-based key derivation function instead of having it declared statically, since the function may be accessed from multiple threads at the same time.
=> Create MbedTLS mdctx inside PBKDF

srtcore/core.cpp
Fixes #2414.
Was broken in PR #2212 (SRT v1.5.0).
=> [core] Fixed byteRcvLoss stats

test/test_ipv6.cpp
The `TestIPv6.v6_calls_v4` test fails is the system-default value of the IPV6_V6ONLY is 1 (r.g. it is so on FreeBSD, see #2007).
Therefore, the required value (0) has to be set on the caller socket explicitly. It can be done with the `SRTO_IPV6ONLY` socket option.
**Required OS**: Linux.
```shell
(Change system-default to 1)
sysctl -w net.ipv6.bindv6only=1
(Check the value is set)
cat /proc/sys/net/ipv6/bindv6only
(Run IPv6 unit tests)
./test-srt --gtest_filter="TestIPv6*"
```
Result without the fix:
```shell
[ RUN      ] TestIPv6.v6_calls_v4
Calling: 0::FFFF:127.0.0.1(IPv6)
/srt/test/test_ipv6.cpp:58: Failure
Expected: (connect_res) != (SRT_ERROR), actual: -1 vs -1
srt_connect() failed with: Connection setup failure: connection timed out
CALLER Sock name: : :::56019 (IPv6)
CALLER Peer …
```
=> Fixed TestIPv6.v6_calls_v4 in case the system-default IPV6_V6ONLY is 1.

CMakeLists.txt, srtcore/buffer_rcv.cpp
Changes:
1. `INT_MAX` replaced with `std::numeric_limits<int>::max()`.
2. Added `<limits>` header in buffer_rcv.cpp
3. Added `-D_DEBUG` when `ENABLE_DEBUG` is on (debug only).
4. Added cast in a condition to clear out the warning
=> Fixed build break when enabled SRT_ASSERT. Enabled _DEBUG in debug mode

srtcore/core.cpp, srtcore/crypto.cpp, srtcore/crypto.h, srtcore/sync.cpp
`CCryptoControl` takes too much responsibility, and also handles sending of KM packets via a `CUDT` socket class.
Ideally, the CUDT should send everything itself, and only ask `CCryptoControl` if something has changed and an exchange of updated keys is required. However, it is not easy to decouple this logic straight away.
This PR removed reference to `CUDT` where possible. When `CUDT` asks `CCryptoControl` to send something, it just passes a pointer to itself so that `CCryptoControl` can call the sending function.
This should at least allow using `CCryptoControl` in a unit test without mocking `CUDT`.
=> CCryptoControl: Partially removed dependency on CUDT.

haicrypt/cryspr-openssl-evp.c
`crysprOpenSSL_EVP_AES_EcbCipher(..)` was not setting the `outlen_p` value.
=> [core] Fixed outlen_p value in EVP_AES_EcbCipher

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp, srtcore/group.h, srtcore/tsbpd_time.cpp, srtcore/tsbpd_time.h
Normally [the TSBPD base time](https://datatracker.ietf.org/doc/html/draft-sharabayko-srt-01#section-4.5) is updated on the receiver side based on timestamps of incoming SRT data packets.
Clock drift estimate is updated based on ACK-ACKACK packet pairs, on the receiver side.
TSBPD base time update with this PR happens only if [the new receiver buffer](https://github.com/Haivision/srt/blob/v1.5.0/docs/build/build-options.md#enable_new_rcvbuffer) is used.
In case of an idle connection only KEEPALIVE packets are being sent to the peer. They must be used to track the TSBPD base time carryover. The carryover happens every 01:11:35 (HH:MM::SS) hours once the `timestamp` field of an SRT packet no longer has enough bits to represent a packet timestamp based on the current TSBPD time base.
A …
=> Update TSBPD base time and clock drift on an idle connection.

srtcore/api.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp, srtcore/queue.cpp, srtcore/sync.h, test/test_bonding.cpp, test/test_sync.cpp
1. All POSIX-like signal/broadcast names changed to notify_one/all to follow the naming used in the C++ standard.
2. Added a new CUniqueSync class that integrates CSync and UniqueLock and improved the CEvent class to make it more usable as a mutex/condition pair.
=> Changed cond notification naming. Added and used new sync utilities.

srtcore/handshake.cpp
Potential crash on out-of-bounds memory access.
However, it seems like luckily `RequestTypeStr(..)` is not called for GROUP and TIMEOUT rejection codes.
=> [core] Fixed missing reject reason types (logging).

README.md, docs/README.md, docs/build/build-macOS.md, docs/build/package-managers.md
Added "Packet Managers" section to "Build Instructions" of main README. This PR is a replacement for PR #2453. 
Actually as the "Packet Managers" section is pretty long when we list all the managers, I've decided to put it as a [separate document](docs/build/package-managers.md) under `docs/build/` folder and add a link from the main README "Build Instructions".
Co-authored-by: Adela0814 <95600143+Adela0814@users.noreply.github.com>
Co-authored-by: maxsharabayko <maxlovic@gmail.com>
=> [docs] Added Packet Managers section to Build Instructions

scripts/release-notes/README.md
The main change is fixing the following command line, as it excludes the very top commit (the HEAD itself):
```shell
git log --pretty=format:"%h|%s|%an|%ae" v1.4.0...HEAD^ > commits.csv
```
The rest is just about describing the missing steps.
=> [docs] Updated docs on release notes generation

apps/uriparser.cpp
`std::map::at(const Key& key)` throws an exception of type `std::out_of_range` if the target key is not found.
Instead, the `m_uriType` value is expected to remain as `UNKNOWN`.
Therefore replaced with `find`.
=> [apps] UriParser: fixed protocol type detection.

srtcore/core.cpp, srtcore/fec.h
Because of https://github.com/Haivision/srt/pull/2463, I searched all usages of `m_iMaxSeqNo`.
it is a valid seqno, so I replaced some `m_iMaxSeqNo` with `SRT_SEQNO_NONE`.
=> [core] Fixed some wrong usages of m_iMaxSeqNo.

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/core.cpp, srtcore/list.cpp
It caused the "No room" issue:
```
processData: LOSS DETECTED, %: [ {2147483645 1} ] - RECORDING.
...
20:49:09.916010/SRT:RcvQ:w1!W:SRT.br: CRcvBufferNew::dropUpTo: seqno 3 m_iStartSeqNo 3. Nothing to drop.
20:49:09.916022/SRT:RcvQ:w1 D:SRT.xt: ackDataUpTo: %3 -> %2147483647 (-4 packets)
20:49:09.916031/SRT:RcvQ:w1 D:SRT.xt: ACK: clip %2147483647-%2147483647, REVOKED 0 from RCV buffer
...
20:53:59.603949/SRT:RcvQ:w1!W:SRT.qr: @203486701: No room to store incoming packet seqno 8190, insert offset 2. iFirstUnackSeqNo=2147483647 m_iStartSeqNo=8188 m_iStartPos=6659 m_iMaxPosInc=2. Space avail 2/8192 pkts. (TSBPD ready in -182ms, timespan 0 ms). STDCXX_STEADY drift 0 ms.
```
Previously, the loop of `CRcvLossList::remove()`
```
for (int32_t j = seqno1; j < CSeqNo::m_iMaxSeqNo; ++j) {}
``` …
=> Fixed CRcvLossList can not remove m_iMaxSeqNo.

srtcore/socketconfig.cpp
This PR fixes build on MacOS with `SDK-10.5`. The SDK confuses `namespace sync` with the POSIX `sync(3P)` e.g. `void sync(void);` function call. The intent of this code seems to be use `srt::sync::milliseconds_from()` method. So further qualifying the namespace disambiguates the intent.
=> [Build] Fix MacOS Build SDK-10.5.

srtcore/core.cpp
This PR consists two commits:
* [Moved m_FreshLoss.push_back() out of the incoming loop.](https://github.com/Haivision/srt/commit/f8869021c369b40ab8eb66b5906b69d38d2c5ae6)
Previously, `m_FreshLoss.push_back()` happened inside
```
for (vector<CUnit *>::iterator unitIt = incoming.begin(); unitIt != incoming.end(); ++unitIt)
```
result that `srt_loss_seqs` will be added and logged repeatedly.
* [Also protected m_pRcvLossList->insert() with m_RcvBufferLock.](https://github.com/Haivision/srt/commit/2b014ad099ddd39bd59435ff96d9a42f6955c38f)
* Update `m_FreshLoss` and `m_pRcvLossList` at the same time to improve their consistency and reduce one `m_RcvLossLock`.
* Fix the synchronous issue between `processData()` and `tsbpd()`, related PR https://github.com/Haivision/srt/pull/2195, I found that …
=> [core] Improved m_FreshLoss and m_pRcvLossList in processData()

docs/build/build-win.md
=> [docs] Defined a reason to use C++11 on Windows instead of pthreads port.

srtcore/buffer_snd.cpp, srtcore/buffer_snd.h, srtcore/packet.cpp, srtcore/packet.h
The additional space is to be used to store the auth tag in GCM AEAD mode.
The SND buffer (unfortunately) has to know if AUTH tag is to be used or not because it splits a message into several packets when `addBuffer(..)` is called. Every packet needs to have additional space in the end for the AUTH tag if AES GCM is enabled.
The `CPacket` class has to possess a 'capacity' property to distinguish between the payload size and the capacity to hold more data (auth tag).
The structure of the data packet is the following (with the auth tag in the end):
```
0                   1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+- SRT Header +-+-+-+-+-+-+-+-+-+-+-+-+-+
|0|                    Packet Sequence Number …
```
=> [core] Add auth tag to the sender buffer.

haicrypt/cryspr-openssl-evp.c, haicrypt/cryspr.c, haicrypt/cryspr.h, haicrypt/haicrypt.h, haicrypt/hcrypt.c
- Fixed usage of the `aes_gcm_cipher(..)` prototype. `crysprStub_AES_GCMCipher` was not matching.
- Renamed CRYSPR_AUTHTAGMAX to HAICRYPT_AUTHTAG_MAX and relocated.
=> CRYSPR AES GCM follow up adjustments.

srtcore/buffer_rcv.cpp
Just moved the check of the last position up, because if it contains a NULL unit, the `while` loop has no sense.
=> Minor edits to the CRcvBuffer::getTimespan_ms().

srtcore/core.cpp
Ref: https://github.com/Haivision/srt/pull/2467#issuecomment-1263702682
=> [core] Made offset consistent with avail_bufsize.

haicrypt/haicrypt.h, haicrypt/hcrypt.c, haicrypt/hcrypt_ctx_rx.c, haicrypt/hcrypt_ctx_tx.c, haicrypt/hcrypt_msg.h, srtcore/crypto.cpp
```
0                   1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|S|  V  |   PT  |              Sign             |   Resv1   | KK|
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                              KEKI                             |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|     Cipher    |      Auth     |       SE      |     Resv2     |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|             Resv3             |     SLen/4    |     KLen/4    |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                              Salt                             | …
```
=> [AEAD] Set AES-GCM auth in the KM message.

srtcore/api.cpp, srtcore/group.cpp, srtcore/group.h
Currently there is no log for `group xxx add member yyy` in listener side if the heavy logging is disabled.
=> [core] Tune logs of group members adding and removing.

srtcore/core.cpp
According to the [SRT Internet-Draft](https://datatracker.ietf.org/doc/html/draft-sharabayko-srt-01#section-4.3.1.1), if the Extension Flags field does not contain the magic value 0x4A17 the connection is rejected. This is a contingency for the case where someone who, in an attempt to extend UDT independently, increases the Version value to 5  and tries to test it against SRT.
Fixes #2494.
=> [core] Reject if SRT_MAGIC_CODE is not set in the HS induction response.

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/buffer_snd.cpp, srtcore/buffer_snd.h, srtcore/buffer_tools.cpp, srtcore/buffer_tools.h, srtcore/filelist.maf
Things done:
1. Everything except the CSndBuffer class removed from `buffer_snd.h` to `buffer_tools.h` and same with implementation files.
2. Completed the file heading information in `buffer_rcv.cpp`
3. Reviewed and fixed the list of includes.
=> Refax: moved buffer tools to a separate file

CMakeLists.txt, apps/socketoptions.hpp, docs/API/API-functions.md, docs/API/API-socket-options.md, docs/apps/srt-live-transmit.md, haicrypt/hcrypt_ctx_rx.c, scripts/googletest-download.cmake, srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/core.cpp, srtcore/crypto.cpp, srtcore/handshake.cpp, srtcore/socketconfig.cpp, srtcore/socketconfig.h, srtcore/srt.h, srtcore/srt_c_api.cpp, test/filelist.maf, test/test_crypto.cpp
=> Add AES GCM to the SRT API.

srtcore/core.cpp
I found the `ackDataUpTo: IPE` logs from https://github.com/Haivision/srt/pull/2463 happened frequently, e.g.
```
11:05:45.433712/SRT:TsbPd!W:SRT.br: @965985327:RCV-DROPPED 53 packet(s). Packet seqno %1675849901 delayed for 234.185 ms
11:05:45.433777/SRT:RcvQ:w1*E:SRT.xt: @965985327: ackDataUpTo: IPE: invalid ACK from %1675849901 to %1675849848 (-53 packets)
```
It may caused by the inconsistency between `getFirstLostSeq()` and `ackDataUpTo()`:
```
[RcvQ] m_pRcvLossList->getFirstLostSeq() -> 1675849848
[TsbPd] rcvDropTooLateUpTo() -> 1675849901
[RcvQ] ackDataUpTo() -> 1675849848 < 1675849901!
```
So `getFirstLostSeq()` should be protected by `m_RcvBufferLock` together with `ackDataUpTo()`.
=> [core] Fixed the inconsistency between getFirstLostSeq() and ackDataUpTo()

srtcore/core.cpp
For the first commit:
```
/SRT:RcvQ:w24 D:SRT.xt: sendCtrl(UMSG_ACK): @318884507:ACK ERROR: 1949537403-1949537402(diff -1)
/SRT:RcvQ:w24 D:SRT.xt: sendCtrl(UMSG_ACK): @318884507:ACK ERROR: 1949537406-1949537405(diff -1)
/SRT:RcvQ:w24 D:SRT.xt: sendCtrl(UMSG_ACK): @318884507:ACK ERROR: 1949537411-1949537410(diff -1)
/SRT:RcvQ:w24 D:SRT.xt: sendCtrl(UMSG_ACK): @318884507:ACK ERROR: 1949537412-1949537411(diff -1)
```
These are just repeat ACK.
For the second commit:
```
08:02:11.739054/SRT:RcvQ:w1*E:SRT.in: @758730097:IPE: ACK record not found, can't estimate RTT (ACK number: 3829, last ACK sent
: 4888, RTT (EWMA): 63834614)
08:02:11.983967/SRT:RcvQ:w1*E:SRT.in: @758730097:IPE: ACK record not found, can't estimate RTT (ACK number: 3830, last ACK sent
: 4892, RTT (EWMA): 63834614) …
```
=> Fixed some ACK error logs.

srtcore/packet.cpp, srtcore/queue.cpp, srtcore/queue.h
Changes:
1. Added formatting function for numbers used in `CPacket::pack` logging to make log information clearer.
2. Put whole contents (previously too finegrained) of packet.cpp file under `srt` namespace
3. In queue.cpp, shipped off the highrate logging facility to a separate function and simplified macro in order to improve readability of the `CSndQueue::worker` function.
=> Refax: improve logging and code readability around specific logging

srtcore/group.cpp, srtcore/group.h
This adds a size cache to the group container.
The group container is `std::list` and as such it doesn't have its own saved cache. There were two reasons to add this:
1. In some future implementations the call to the container's size() can be even very often, while `std::list` original size() is linear time in the number of members.
2. There will be also situations when the size is needed to be taken without locking the group's mutex. With this cache the size can be directly taken from the cache, and as atomic, it doesn't need to be mutex-locked.
=> Refax: added size cache to the group container

srtcore/api.h, srtcore/core.cpp, srtcore/group.cpp
1. The call to `m_pRcvLossList->getLossLength()` (affinity: `CRcvQueue::worker`) added a mutex lock because this container may be also modified in the `CUDT::dropFromLossList` that is among others also called from `CUDT::rcvDropTooLateUpTo` (affinity: `CUDT::tsbpd`). Of course, the list can be also modified before sending the lossreport could be done, but this will then recheck the losses anyway.
2. The socket is set closing state before its ties to the group are severed. This prevents the socket from any processing that should involve working socket, while access to some vital resources may be already denied for this socket, as they are dependent on the group.
=> Refax: safety improvements

srtcore/buffer_rcv.h, srtcore/core.cpp, test/test_buffer_rcv.cpp
Fixed https://github.com/Haivision/srt/pull/2467#issuecomment-1280677923
=> [core] Fixed CRcvBuffer::getAvailSize() may jump around.

srtcore/api.cpp, test/filelist.maf, test/test_socketdata.cpp
=> Fixed: connected peer address not recorded

srtcore/core.cpp, srtcore/core.h, test/filelist.maf, test/test_bonding.cpp
1. Added exclusion for non-bonding for fields in `CUDT` that are not in use when bonding is off
2. Changed bonding test conditional from "masking whole file" to conditional in the filelist
3. Removed unused `CUDT::defaultPacketArrival`. This function was planned to be an alternative loss handling for the case of common-buffer groups, but things have changed largely in the meantime and this function is no longer necessary, and not used in the new group code.
4. In `test_bonding.cpp` deleted lines with unused includes and defines.
=> Refax: Cleanup for bonding conditionals and unused code

srtcore/api.cpp
Hi,
As discussed here https://srtalliance.slack.com/archives/C7MP1DJ20/p1667339255259169, in `srt_connect()` the input parameters are not validated before their usage whereas all other functions validate their input parameters.
I guess the validation was missing, the PR adds it.
=> [core]: Fixed validation of input parameters in srt_connect

srtcore/core.cpp, srtcore/core.h, srtcore/packet.cpp
=> Refax/postfix: further fixes after last refax changes

docs/build/build-options.md
As I always have to spend 5-10 minutes to find out how to activate the HAICRYPT logging, I thought it would be helpful to have it in our docs.
=> [docs] Added a note on activating HAICRYPT logging

CMakeLists.txt
Normally, the libraries listed in CMAKE_CXX_IMPLICIT_LINK_LIBRARIES are of the form of either an absolute file name (which is already handled) or a plain library base name without prefixes or suffixes.
In some cases, it may also be a literal linker option in the form -l<value>. This seems to happen when the compiler driver specifies -l:<literalfilename>.
This avoids creating bogus pkg-config entries when building with llvm-mingw, with -DCMAKE_CXX_FLAGS=-static-libgcc, which makes CMAKE_CXX_IMPLICIT_LINK_LIBRARIES end up with one entry being "-l:libunwind.a".
=> [build] Identify parameters with a prepended -l in CMAKE_CXX_IMPLICIT_ LINK_LIBRARIES

test/test_bonding.cpp
1. The locally created socket for listening has been closed. The socket left open has made the port kept busy and caused other tests to fail.
2. Added extra checks for the test so that SRT functions, if they fail unexpectedly, got also their error displayed in the test.
=> Test bugfix: close the listener socket that was left open after exitting the function.

srtcore/core.cpp
`m_iAuthTagSize`  was not properly initialized, resulting in corrupted contents when large packets were transmitted.
=> [core] fix CSndBuffer parameter incorrect in AES GCM mode

.github/workflows/android.yaml, .github/workflows/cxx11-macos.yaml, .github/workflows/cxx11-ubuntu.yaml, .github/workflows/cxx11-win.yaml, .github/workflows/iOS.yaml
GitHub Actions: All Actions will begin running on Node16 instead of Node12. Link:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> [build] Upgrade to checkout@v3 GitHub action.

srtcore/buffer_rcv.h, srtcore/buffer_tools.cpp, srtcore/buffer_tools.h, srtcore/sync.h
The issue was introduced in #2499 (v1.6.0-dev).
The header `sync.h` requires `platform_sys.h`. The file `buffer_tools.h` included `sync.h` first, leading to the undefined `TARGET_OS_MAC`.
Also removed some excessive `sync.h` includes, as `common.h` already includes `sync.h`, no need to include twice.
When building on MacOS CLANG 13.0.0.13000029
```shell
[  3%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/buffer_rcv.cpp.o
srtcore/buffer_rcv.cpp:48:
srtcore/buffer_rcv.h:14:
srtcore/buffer_tools.h:56:
srtcore/sync.h:40:7: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
#elif TARGET_OS_MAC
^
```
=> [core] Fixed TARGET_OS_MAC not defined.

haicrypt/hcrypt_ctx_tx.c, haicrypt/hcrypt_tx.c, srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp, srtcore/crypto.h
The issue is described in #2502: it is possible to get a corrupted packet on the receiving side when encryption is enabled.
The reason is that a data packet may be encrypted with a key different from the one indicated in the `KK` flied of the data packet header.
The active key (odd/even) switch happens in the RcvQ thread:
```c++
CUDT::processCtrlAck(..)
⋅ ⋅ CUDT::checkSndTimers(..)
⋅ ⋅ ⋅ ⋅ CCryptoControl::sendKeysToPeer(..) // Key refresh
```
The SndQ Thread first sets the KK frags of a data packet, then encrypts the packet, **potentially with a different key if KM refresh has happened**.
```c++
CUDT::packUniqueData(..)
⋅ ⋅ CCryptoControl::encrypt(..)
```
https://github.com/Haivision/srt/issues/2502#issuecomment-1311631552
**Statement 1.** KM refresh is performed by the payload sender for …
=> [core] Moved KM refresh in packUniqueData()

haicrypt/hcrypt.c
When cloning the RX crypto context to the TX crypto context there was an error in not setting the AES-GCM flag.
The bug resulted in the listener being unable to send a message to the caller with AES GCM mode.
Fixes #2534.
Issue after #2476. Affected SRT version v1.6.0-dev.
=> [core] Fixed cloning the RX crypto context (AEAD)

docs/API/API-socket-options.md
=> Doc: fixed wrong description of PBKEYLEN conflict resolution

srtcore/queue.cpp
=> Fix: rendezvous: do not reject incoming packet with id=0 when rendezvous

srtcore/md5.cpp, srtcore/md5.h
Clang 14 compilation warning:
```shell
srtcore/md5.cpp:170:18: warning: performing pointer subtraction with a null pointer may have undefined behavior
[-Wnull-pointer-subtraction]
if (!((data - (const md5_byte_t *)0) & 3)) {
^ ~~~~~~~~~~~~~~~~~~~~~
```
The subtraction was done to avoid explicit casting. Although explicit casting is cleaner.
=> [core] MD5: Removed null pointer subtraction

test/test_listen_callback.cpp
=> [Test][MAINT] Splitting ListenCallback test into 3 separate tests, fixed proper setup/teardown

srtcore/api.cpp, srtcore/common.cpp, srtcore/common.h, srtcore/congctl.h, srtcore/packetfilter.cpp, srtcore/packetfilter.h, srtcore/packetfilter_api.h, srtcore/udt.h
Touches `udt.h`. It is not the official SRT API though.
Fixes #2379.
=> [core] Pass std::string by const ref where possible.

.travis.yml
If unit tests fail, the code coverage and sonar scanning are not needed, so just don't run them.
=> [build] Run codecov only after success in Travis.

docs/API/API-functions.md
=> Added lacking mention of BINDTODEVICE for srt_config_add

haicrypt/haicrypt_log.cpp, haicrypt/haicrypt_log.h, srtcore/api.cpp, srtcore/core.cpp, srtcore/logging.h
Requested by #2126.
The LOGF/HLOGF macros haven't been removed, just in case, but their usage will be now deprecated. The `form` method of the log dispatcher, which is being used in this macro, has been marked deprecated in order to make it loud. All uses of LOGF macros have been replaced with LOGC or LOGP.
Note that this has no influence on the logging in haicrypt, as it uses `vform`, not `form` method through the wrapper functions.
=> Refax: remove usage of LOGF/HLOGF

srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp, srtcore/crypto.h
Fixes #2553 (supposedly).
The issue is only reproducible in Travis. But based on [the stack trace](https://github.com/Haivision/srt/issues/2553#issuecomment-1337628118) after a crash the CryptoControl module is released, while the receiving thread checks the timers and attempts to resend a KM.
=> [core] Obtain ConnectionLock while sending crypto keys.

srtcore/core.cpp, srtcore/list.cpp, srtcore/list.h, test/test_losslist_rcv.cpp
One-record-removal procedure made by a separate function.
Additional: some fields of the `CSndLossList` exposed for better debug and test access.
=> Refax: moved removal of one seq from fresh loss list to a separate function

srtcore/queue.cpp
Fixes #2557 
The problem: The "rendezvous queue" has been serving in UDT for actually two purposes: beside rendezvous, it was also used to handle caller sockets in non-blocking mode (blocking mode for caller sockets' handling was executed completely in a loop in `CUDT::startConnect`). This was a procedure used for the following situations in response to an incoming handshake packet:
1. When a packet is coming with a given target Socket ID. In this case it should find and return such a socket, which is:
* a registered earlier caller socket that started the connection request
* a rendezvous socket which's id is known because at least one WAVEAHAND handshake has been received already
2. When a packet is coming with ID=0, which means it's a connection request, then:
* if to the address, to …
=> Fixed: reject RID for id=0 if not rendezvous

srtcore/core.cpp
Fixed a bug occurred in group in-order message mode.
I only enabled few heavy logs in production env:
```
13:16:28.613875/SRT:RcvQ:w3 D:SRT.sm: generateSocketID: : @540801042
13:16:28.614177/SRT:RcvQ:w3 D:SRT.gm: @540801042:synchronizeWithGroup: ST=13:14:17.945509367 [STDY] -> 13:05:18.457541056 [STDY] PST=13:14:17.856090360 [STDY] -> 13:05:18.429949816 [STDY]
13:16:28.614211/SRT:RcvQ:w3 D:SRT.gm: @540801042:AFTER HS: (GROUP, but no TSBPD set)
13:16:28.614251/SRT:RcvQ:w3 D:SRT.gm: applyGroupSequences: @540801042 gets seq from @540801166 rcv %1030134429 snd %1030134390 as GROUPWISE snd-seq
13:16:28.614268/SRT:RcvQ:w3 D:SRT.gm: @540801042:synchronizeWithGroup: DERIVED ISN: RCV=%1030134430 -> %1030134429 (shift by -1) SND=%1030134430 -> %1030134390 (shift by -40)
13:18:55.824817/SRT:RcvQ:w3 …
```
=> [core] Fixed missing DROPREQ for LOSSREPORT that partially predates ACK.

docs/API/API-socket-options.md, srtcore/socketconfig.cpp
The AES-GCM mode cannot be used at the moment if TSBPD is disabled.
The main reason is the different handling of the 'timestamp' field of a data packet (see  #2337).
When TSPBD is disabled, the timestamp is set at the time of sending, unique for every retransmission. The timestamp field is included in the associated data for integrity check, while encryption happens only the first time a packet is sent. Using the AES-GCM would fail on a retransmitted packet.
This PR restricts using AES-GCM without TSBPD until a further decision is taken to either exclude the 'timestamp' field from the integrity check when TSBPD is disabled or (preferably) use the same timestamping rule in any mode.
- Do not allow AES GCM if TSBPD is disabled.
- Do not allow disabling TSBPD if GCM is enabled.
=> [api] Socket Options: do not allow AES GCM if TSBPD is disabled.

docs/API/API-socket-options.md, srtcore/core.cpp, srtcore/crypto.cpp, srtcore/crypto.h
For an SRT listener to accept any crypto mode (AES-GCM or AES-CTR) the `SRTO_CRYPTOMODE=0` (Auto) can be used.
When `SRTO_CRYPTOMODE=0` (Auto) is set on an SRT Caller or SRT Rendezvous the actual mode to be negotiated is AES-CTR.
This change does not require further HS changes on the wire, still allows to let the listener to accept any crypto mode.
Once a connection is established, the actual crypto mode is returned via the `SRTO_CRYPTOMODE`: 1 (AES-CTR) or 2 (AES-GCM).
=> [API] Crypto mode 'auto' implemented for listener.

CMakeLists.txt, apps/socketoptions.hpp
The PR contains some follow-up fixes after #2586.
- CMake error message hint to use `USE_ENCLIB` (was `USE_ENC_LIB`).
- Apps URI option 'cryptomode' enabled if `ENABLE_AEAD_API_PREVIEW` (was `ENABLE_AEAD_PREVIEW`).
=> [apps] Fix ENABLE_AEAD_API_PREVIEW in apps.

docs/features/socket-groups.md
Possible values are 0 (default) or 1. (https://github.com/Haivision/srt/issues/1268#issuecomment-623985221)
=> groupconnect option "1" (not "true")

.github/workflows/cxx11-ubuntu.yaml, CMakeLists.txt, examples/recvlive.cpp, examples/recvmsg.cpp, examples/sendmsg.cpp, examples/test-c-client.c, examples/test-c-server.c
Changes:
1. Fixed build breaks in the C examples. Broken in #2572.
2. Added building examples and testing (devel apps) to one of the CI builds.
3. Added example files for simple testing the message mode.
The message mode testing can be done the following way:
1. recvmsg hosts a listener and receives messages, then displays them one after another on the screen, or writes them to subsequent files.
2. sendmsg reads messages each one with a single line. Optionally the line can start with + to additionally define a TTL for it. Optionally the input specification can start with + to define the input being a list of lines with filenames. Every line can also contain +N defining a TTL for this message, and the content is read from the given file. First 4 bytes of the message is an identifier, in …
=> [MAINT] Fixed example buildbreaks. Added examples for message mode transmission

srtcore/group.cpp
Message mode and file mode work well in group with the new recv buffer.
=> [core] Allow fileCC in group mode.

srtcore/core.cpp
An application can detect a failed decryption with the help of the [pktRcvUndecrypt](https://github.com/Haivision/srt/blob/master/docs/API/statistics.md#pktRcvUndecrypt) statistic.
The warning log message will be shown.
The application is to decide what to do about it: break a connection or continue.
=> [core] AEAD: don't break a connection on decrypt failure.

srtcore/core.cpp, srtcore/crypto.cpp, srtcore/srt.h
The CMakeLists.txt defines an empty `ENABLE_AEAD_API_PREVIEW`.
```cmake
add_definitions(-DENABLE_AEAD_API_PREVIEW)
```
Therefore the `srt.h` should check whether `ENABLE_AEAD_API_PREVIEW` is defined, not the value.
SRT v1.5.2-rc.0.
=> [API] Fixed #if ENABLE_AEAD_API_PREVIEW

srtcore/core.cpp, test/test_listen_callback.cpp
Fixes #2559
1. Setting the SRT_REJX_FALLBACK value in the listener callback in order to give it a default value for the case of rejection request, and clearing this value in case when the rejection reason was mistakenly set by the callback, but it resulted in acceptance.
2. Fixed the bug in the caller's handling of the listener's rejection callback - value exactly equal to URQ_FAILURE was not treated as error.
=> [BUG] Fixed default reject reason for a listener callback and wrong handling of a listener's reject response

.github/workflows/cxx11-macos.yaml, scripts/googletest-download.cmake
Fixes the MacOS GitHub Action build error seen lately:
```shell
googletest-src/googlemock/include/gmock/gmock-actions.h:455:3: error: definition of implicit copy constructor for 'PolymorphicAction<testing::internal::ReturnNullAction>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
GTEST_DISALLOW_ASSIGN_(PolymorphicAction);
^
/Users/runner/work/srt/srt/_build/googletest/googletest-src/googletest/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
void operator=(type const &) = delete
^
/Users/runner/work/srt/srt/_build/googletest/googletest-src/googlemock/include/gmock/gmock-actions.h:[101](https://github.com/Haivision/srt/actions/runs/3877271627/jobs/6620352411#step:4:102)1:10: note: in implicit …
```
=> [build] Use GTest from brew in MacOS action.

srtcore/core.cpp
Fixes #2620 
The problem: the caller may reject the connection that was accepted by the listener because the listener is set relaxed encryption and the caller - enforced encryption. In this case the caller was reporting `SRT_REJ_UNSECURE` regardless of the real rejection reason, which is determined during the KMRSP processing on the caller side.
=> [BUG] Fixed usage of the right rejection reason depending on the encryption error also when rejected on the caller level.

srtcore/fec.cpp
=> [MAINT] Removed extra redundant condition checks.

haicrypt/hcrypt_tx.c
Fixes #2376 
IMPORTANT: Since this version C99 is the minimum standard required for compiling haicrypt.
=> [MAINT] Fixed wrong null-safety condition check in haicrypt

srtcore/channel.cpp, srtcore/channel.h
The problem detected while fixing #2608 and handling of the dual-IP address binding cases.
The problem:
The CMSG should be provided only per requested information, however in case of dual-bound sockets (IPv4 + IPv6), which would be used in case when the listener has bound to "::" with IPV6_V6ONLY option 0 (which means binding to both IPv4 and IPv6 wildcards) will effectively have set both IPPROTO_IP/IP_PKTINFO and IPPROTO_IPV6/IPV6_RECVPKTINFO flags set and in consequence both IPv4 and IPv6 pktinfo message will be provided with `recvmsg` call. The problem was that the space reserved for filling in this message was set as the one for only IPv4 or IPv6. The fix reserved enough space to fill BOTH IPv4 and IPv6 pktinfo cmsg at once.
Besides, there is added also an enhanced diagnostics where …
=> [BUG] Fixed PKTINFO case that was failing for IPv4+IPv6 bound sockets

srtcore/api.cpp
Different overloads of the `new` operator handle allocation failures in different ways. If `new T` fails for some type `T`, it throws a `std::bad_alloc` exception, but `new(std::nothrow) T` returns a null pointer. If the programmer does not use the corresponding method of error handling, allocation failure may go unhandled and could cause the program to behave in unexpected ways.
As reported in PR #2578.
=> [core] CodeQL warning: checking NULL after new.

srtcore/common.h
CodeQL reports (#2578):
> This 'call to sprintf' operation requires 22 bytes but the destination is only 20 bytes.
Not sure where 22 bytes come from though.
I assume the longest would be `SrtVersionString(-2147483647) = -32767.-255.-255` which is 17 characters.
```c++
// int version max 2147483647, min -2147483648.
int patch = version % 0x100; // max 255   min -255
int minor = (version/0x100)%0x100; // max 255, min -255.
int major = version/0x10000; // max 127.  min -32767
```
=> [core] CodeQL: operation requires 22 bytes.

haicrypt/hcrypt_tx.c
Fixes #2651 
The ASSERT instruction was using `ctx` value that was not always equal to `crypto->ctx` at this time (could be altered in the function called before it).
=> [MAINT] Fixed invalid ASSERT checking outdated object in haicrypt

test/test_enforced_encryption.cpp
Related to #2503 although this problem was not confirmed in the latest version.
This adds the check if in the non-blocking mode the read-ready epoll flag has NOT been set in case of decryption failure.
Decryption failure is expected with both sides set "relaxed encryption", both have different password settings, and the sender is set a passphrase. In all other cases this should either result in rejected connection or successful reception, and these latter cases read-readiness should be expected (this is checked though through an attempt for reading).
=> [TEST] Added check for read-ready for decryption failure case

srtcore/core.cpp, srtcore/srt.h
The PR addresses issue #2626.
When packet decryption fails, the fields of the packet cannot be trusted, and therefore used for dropping the whole message.
Given that SRT only allows AEAD in live streaming configuration at the moment, it is ok to drop a packet from the RCV buffer based on the packet sequence number used to insert it into the buffer. In the live streaming configuration, one packet represents a single message, thus by dropping one packet the whole message is dropped.
This approach should be good enough for v1.5.2 and for live streaming configuration in general.
A more universal approach would require removing a packet from the RCV buffer (without dropping( and adding the packet sequence number to the RCV loss list (see PR #2649). Also, the RCV buffer state would have to be …
=> [core] Drop undecrypted packet based on sequence number.

srtcore/api.cpp, test/test_reuseaddr.cpp
1. setting SRTS_CLOSING state on a socket that was requested to be closed.
2. Added time tracking when closing a socket with tracked wiping to track the time taken for wiping out a socket.
=> [MAINT] Added setting CLOSING state when closing a socket

CMakeLists.txt, docs/build/build-options.md, srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp
If SRT fails to decrypt a packet, one error message is printed from `CCryptoControl::decrypt(..)` :
```shell
W:SRT.cn: decrypt ERROR (IPE): HaiCrypt_Rx_Data failure=-1 - returning failed decryption
```
and one warning is reported from `CUDT::handleSocketPacketReception(..)`:
```shell
Decryption failed. Seqno %...
```
Thus two warnings are printed per single decryption failure. In case of an attack in AES-GCM mode, a lot of data packets may be corrupted, and decryption is expected to fail. That would result in too many warning messages.
This PR introduces a new variable `m_tsLogSlowDown` to reduce the frequency of some potentially frequent warnings. Currently, only decryption failure warning uses this mechanism.
By default, the following warning will be shown not more often than once per 1 …
=> Reduce frequency of the decryption failure log

haicrypt/cryspr-mbedtls.c, haicrypt/cryspr.c, haicrypt/haicrypt.h, haicrypt/hcrypt_ctx_rx.c, haicrypt/hcrypt_ctx_tx.c, haicrypt/hcrypt_rx.c
The includes were necessary when platform_sys.h included pragmas to disable some warnings. These aren't needed now the warnings have been fixed properly.
This commit also includes a couple of warning fixes which seem to have slipped through the net.
=> Fixed warnings and removed redundant includes

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/core.cpp, test/test_buffer_rcv.cpp
Fixed `CRcvBuffer::dropMessage(..)`.
- Tell what to do with existing packets.
- Fixed pkt seqno dropping loop range.
The function is used in two situations:
1. Incoming message drop request from the sender.
2. Dropping a packet with decryption failure.
If msgno is valid, sender has requested to drop the whole message by TTL. In this case it has to also provide a pkt seqno range.
However, if a message has been partially acknowledged and already removed from the SND buffer,
the seqnolo might specify some position in the middle of the message, not the very first packet.
If those packets have been acknowledged, they must exist in the receiver buffer unless already read.
In this case the msgno should be used to determine starting packets of the message.
Some packets of the message can be …
=> [core] Fixed CRcvBuffer::dropMessage.

srtcore/buffer_rcv.cpp
To improve the `CRcvBuffer::dropMessage(..)` performance the packets are dropped based on pkt seqno range first.
Then, if the start of the message has not been dropped, and additional search step from the `seqnolo` position downwards is applied to look for a packet with `PB_FIRST` boundary flag.
Proceeding after #2657.
@gou4shi1 please have a look.
=> [core] Reworked the CRcvBuffer::dropMessage(..) function.

docs/API/configuration-guidelines.md
Closes #2662 
This fixes the description of how the size of the buffer is internally calculated.
=> [DOC] Changed the buffer size description to be clearer

apps/transmitmedia.cpp, docs/apps/srt-live-transmit.md, testing/testmedia.cpp
This adds handling of the `bind` parameter for SRT URI, for compatibility with srt-xtransmit.
Fixes #2665
=> [MAINT] Added 'bind' parameter handling for applications.

srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp, srtcore/srt_c_api.cpp, testing/testmedia.cpp
This adds the procedure to craft and send the rejection response in case when the handshake in rendezvous mode in one side has resulted in rejection. Some paths for this are common with caller mode so it's taken care of that it happens only in case of rendezvous mode.
Motivation: in case of caller-listener layout, it happens the following way:
1. Caller-Listener induction exchange.
2. The listener receives conclusion handshake, which is erroneous and it is being rejected
3. The listener responds anyway (in its distinct procedure), AFTER it closes the accepted socket without allowing it to be retrieved, and the listener handler procedure is crafting and sending the rejection response to the caller.
In some rare cases when the rejection is done on the caller, while the listener accepts the …
=> [FIX] Added rejection handshake sent to the peer in rendezvous mode

testing/srt-test-multiplex.cpp
=> [FIX] srt-test-multiplex: Fixed crash on medium error

srtcore/core.cpp
Partial fix for bug #2697. Peer filter config should now correctly be interpreted even on big endian systems
=> [core] Fix peer filter config being rejected because of endianness

haicrypt/cryspr-mbedtls.c, haicrypt/cryspr-mbedtls.h
Nothing much to see here, except satisfying my pedantry.
=> Fixed typos in MBedTLS where it referred to GnuTLS

srtcore/fec.cpp, srtcore/fec.h
Fixes #2707 
Repro information: configure transmission with having `packetfilter=fec,cols:100,rows:50,arq:always,layout:staircase` in the SRT URI on one of the transmission sides (the other will follow).
=> FEC: Emergency resize: Fixed crash-bug. Fixed minimum history condition.

apps/apputil.cpp, apps/srt-live-transmit.cpp, apps/srt-tunnel.cpp, apps/transmitmedia.cpp, apps/uriparser.cpp, haicrypt/cryspr-mbedtls.c, haicrypt/cryspr-openssl-evp.c, haicrypt/cryspr-openssl.c, haicrypt/hcrypt.c, srtcore/common.h, srtcore/core.cpp, srtcore/epoll.h, srtcore/fec.cpp, srtcore/logging.h, srtcore/platform_sys.h, srtcore/socketconfig.h, srtcore/srt_compat.c, testing/srt-test-live.cpp
Addresses most (but not all) of the warnings documented here:
https://github.com/Haivision/srt/issues/1646
Plus various other warnings I've encountered on different platforms.
=> Fixed various warnings on various platforms

CMakeLists.txt, srtcore/api.cpp, srtcore/core.cpp, srtcore/epoll.cpp, test/test_bonding.cpp, test/test_sync.cpp
Fixed variable shadowing in the core and tests.
Added `-Wshadow=local` in CMake build for GCC v7.0 and above.
Fixes #2725.
=> [core] Minor fix of variable shadowing.

srtcore/common.cpp
Fixes the last two remaining test failures on big-endian.  These operations were all already no-ops on little-endian, and unnecessarily byteswapped the IP addresses on big-endian.
Closes: https://github.com/Haivision/srt/issues/2697
=> [core] Correct remaining endianness issues

CMakeLists.txt, scripts/test_vista.c
Forcing the _WIN32_WINNT when the environment is already forcing a value results in a lot of warning.
If the user compiles for a higher version of Windows, we don't need to force compilation for Vista.
=> Fix downversioning of _WIN32_WINNT

haicrypt/hcrypt.c
The compiler reported possibly uninitialized value.
This theoretically could have happened because in case of error and returned -1 the variable isn't rewritten with anything. This was allowed to happen only because the error from this call wasn't handled.
=> [MAINT] Fixed unhandled error in haicrypt

srtcore/channel.cpp
Added check of the `WSASend` result, as reported in #973.
Given that `::send(...)` wan not observed to fail on Linux, adding a common `::select(...)` call for both Windows and Linux might decrease the performance.
This PR uses Windows OverlappedIO API to wait for `WSASend` to succeed.
Fixes #973.
Closes #974 (replaces).
=> Use overlapped WSASendTo to avoid UDP sending losses.

srtcore/buffer_rcv.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp, srtcore/group.h
There are two bugs found.
1. After reading a message the group's read-ready state is not updated.
2. There is no more need (I think) to update read-readiness upon sending an ACK. With the new receiver buffer reading is no longer blocked by the ACK position.
The function was introduced (changed) in v1.5.0 with the new receiver buffer in PR #2218. Maybe v1.5.0 with the old receiver buffer or earlier SRT versions didn't have this read-ready issue. In any case, there might have been other issues with the previous reading function.
=> [core] Fixed group read-ready epoll events.

srtcore/core.cpp
Initialize the receiver buffer with the peer's initial sequence number, because the peer would be sending.
Before PR #2711 the correct value was set after the RCV buffer had been initialized via `CUDT::applyResponseSettings(..)`.
**SRT versions with the bug:** v1.5.2, v1.5.2.rc.2.
Fixes #2773.
=> [core] Fixed RCV buffer initialization in Rendezvous.

docs/API/API-functions.md, docs/API/API-socket-options.md, docs/apps/srt-live-transmit.md
After changes in one of the PRs where the matter of IPv6ONLY option is required to resolve binding conflicts, now this option has the default value of -1 and it is not allowed when binding explicitly to an IPv6 wildcard address.
The documentation wasn't exactly clear about this.
=> [doc] Updating the explicit information for binding to IPv6 wildcard

.travis.yml, test/TESTS_HOWTO.md, test/filelist.maf, test/test_bonding.cpp, test/test_common.cpp, test/test_connection_timeout.cpp, test/test_enforced_encryption.cpp, test/test_env.h, test/test_epoll.cpp, test/test_fec_rebuilding.cpp, test/test_file_transmission.cpp, test/test_ipv6.cpp, test/test_listen_callback.cpp, test/test_losslist_rcv.cpp, test/test_main.cpp, test/test_many_connections.cpp, test/test_muxer.cpp, test/test_reuseaddr.cpp, test/test_socket_options.cpp, test/test_socketdata.cpp, test/test_unitqueue.cpp
Fixes #2611 
This adds the custom main function for gtest and allows parameters to be interpreted in the test function.
This is waiting for a solution for startup/cleanup part consistency with gtest exception policy. This PR provides an extra singleton class that would prepare the parameters; this can be linked with a special per-test used object that would interpret these parameters.
The syntax for the test options is beside the options for gtest. All gtest options start with `--gtest` and parameters are passed by  equal sign. All of them are removed from the command line by gtest and the others are free to take. Syntax:
`free_value1 -option1 value -option2 value1 value2 value3 -/ free_value2 free_value3 -option3 -- -value4 -value5 value6`
Here `free_value` represents an argument without …
=> [MAINT/TEST] Added custom main with transparent parameters

srtcore/core.cpp, srtcore/packet.cpp, srtcore/queue.cpp, srtcore/queue.h
Changes `CRcvQueue::storePkt(int32_t, CPacket*)` to `CRcvQueue::storePktClone(int32_t id, const CPacket& pkt)`.
Cloning happens inside the function only if the packet is to be stored, no cloning otherwise.
`CPacket::clone()` now uses `CPacket::allocate(int32_t)` as a common way to allocate memory and to mark the memory is owned by the `CPacket`. It is then deallocated automatically in the destructor.
Refactoring after reviewing and merging #2757.
=> [core] Refactor CRcvQueue::storePkt(..) for better resource management.

srtcore/core.cpp
I experienced a deadlock issue, the `CRcvQueue::worker` thread was blocked in `processCtrlShutdown()->releaseSynch()->pthread_join()` forever:
```
(gdb) thread 37 
[Switching to thread 37 (LWP 2609)]
#0  0x00007fd2f29cd98d in pthread_join (threadid=140541933123328, thread_return=0x0) at pthread_join.c:90
90	pthread_join.c: No such file or directory.
(gdb) bt
#0  0x00007fd2f29cd98d in pthread_join (threadid=140541933123328, thread_return=0x0) at pthread_join.c:90
#1  0x00007fd2f22a0c33 in std::thread::join() () from /home/proxy_server/lib/libstdc++.so.6
#2  0x000055dd734a4242 in srt::CUDT::releaseSynch (this=this@entry=0x7fd241ee63f8) at /worker/build/dc588689bec99c48/root/external/srt/srtcore/core.cpp:7645
#3  0x000055dd734ad456 in srt::CUDT::updateBrokenConnection …
```
=> [core] fix tsbpd() may deadlock with processCtrlShutdown()

srtcore/core.cpp
Fixes #2684 
The problem: the KMX failure was recognized and the response code was set, but the function didn't exit immediately with rejection state. This led to sending back the AGREEMENT while it should have responded with rejection to the peer.
=> [BUG] Rejection not undertaken in rendezvous after KMX failure

srtcore/core.cpp
The problem: there was a fix that added sending rejection HS packet back to the peer in case when rendezvous processing ended up in rejection. The condition, however, excluded only `CONN_CONTINUE` value, while beside `CONN_REJECT` there was also a possible `CONN_ACCEPT` value returned from `processRendezvous`, which would be still handled as it should outside the loop, but this way it was also treated the same as reject.
=> [core] Fix: In rendezvous when processing resulted in ACCEPT it was still sending rejection

srtcore/buffer_tools.cpp, srtcore/buffer_tools.h, srtcore/core.cpp
- [core] Minor code cleanup in CRateEstimator. Extracted from PR #2714.
- [core] Initialize ISN and PeerISN in CUDT.
=> Initialize ISN and PeerISN in CUDT, minor code clean up in CRateEstimator.

srtcore/core.cpp
In case of an AES GCM connection data packets with KK flag set to zero must be dropped.
=> Drop unencrypted packets in GCM mode.

srtcore/core.h
=> [core] Fixed SRT_ATTR_REQUIRES use.

scripts/win-installer/libsrt.nsi
The header file access_control.h was added in the source tree at some point but was not added in the Windows installer.
Please make sure to merge this one before release 1.5.3 in order to get valid Windows installers for that version.
=> Added missing public header files in Windows binary installer

srtcore/buffer_rcv.cpp, srtcore/channel.cpp, srtcore/common.cpp, srtcore/common.h, srtcore/congctl.cpp
Changes:
1. In LiveCC, the header size is taken now from CUDT::maxPayloadSize() and the current MSS size, to stay in sync with the value possibly differently elaborated in the future.
2. MSG TRUNC flag is now traced in the debug logs, to detect any problems resulting in getting bigger packets than expected.
3. checkIPv4Mapped added a simple wrapper to simplify its use.
4. In the receiver buffer, the average payload size is used without the initial size value, instead it recognizes a trap 0 value as "no packet received so far".
=> Pre-refax of change-independent parts for 2677

apps/uriparser.cpp
Apps like srt-live-transmit take their source and destination parameters as urls. Urls require several common characters (e.g. - space) to be percent encoded. This PR adds a simple ASCII / Latin-1 percent decoding function to uriparser.cpp that I applied to the url query string keys and values, so that the url encoding doesn't persist in SRT fields such as streamid.
I don't apply the decoding to the whole url, just the query keys + vals, and I didn't write a matching encoder for re-building a uri out of the decoded components. I'm not even sure this is really the right spot to be doing this. Maybe it should instead just be done when passing the url parameters in to build an actual SRT connection rather than inside the parser's data itself?
Anyway, this PR partially addresses issues #1173 …
=> [apps] Added url percent decoding to url query string keys and values.

srtcore/buffer_snd.cpp, srtcore/buffer_snd.h, srtcore/buffer_tools.cpp, srtcore/buffer_tools.h, srtcore/core.cpp, srtcore/core.h, srtcore/group_backup.h, srtcore/socketconfig.cpp, srtcore/socketconfig.h
Changes:
1. Socketoptions: exported the check for fitting payload size setting to a separate function.
2. CSndBuffer and CRateEstimator get an extra parameter for IP family to be used later.
3. In core.h, removed unused function and added `payloadSize()` that should be used to return payload size after connection.
=> Refax-only (with temporary differences) for 2677

CMakeLists.txt, configure-data.tcl, docs/build/build-options.md, haicrypt/cryspr-botan.c, haicrypt/cryspr-botan.h, haicrypt/cryspr-config.h, haicrypt/filelist-botan.maf, scripts/FindBotan.cmake, scripts/build-android/build-android, scripts/build-android/mksrt, scripts/iOS.cmake
As my project primarily uses Botan (https://botan.randombit.net) I decided to write a Botan cryspr for SRT so that I could drop my dependency on multiple crypto libs.
I'm sharing this in case it is of interest to anyone. I've not integrated this into the SRT build system(s) at this stage as I do not use them; instead dropping the SRT files directly into my projects.
=> A crypto service provider based on Botan

srtcore/core.cpp, srtcore/core.h, srtcore/sync.h
Fixes #2706 
This was initially created to verify #2706 problem causing a hangup with high bitrates on the sending side.
The suspected part was lack of mutex protection for the activities around ACK reception and the sequence number pointers `m_iSndLastAck` and `m_iSndCurrSeqNo` which could be modified simultaneously by the receiver thread upon reception of UMSG_ACK. There was a distinct corner case with possible modification of one of these fields during processing, which could cause a situation of impossible layout of the sequence numbers likely after sender-dropping packets.
Note: it is not clear what exactly has fixed the problem, but with this version the reported problem was no longer reproducible.
=> [BUG] Fixes lacking mutex protection to some ACK-related fields

srtcore/core.cpp
Broken in SRT v1.5.0 - v1.5.3.
=> [core] Fixed wrong pktSndDrop stats value.

docs/API/API-functions.md
Small tweak of the docs regarding SRT bonding :).
=> Update API-functions.md description to be more explicit about grpdata_size updates

srtcore/channel.cpp, srtcore/channel.h
An infinite hand up on the `WSAGetOverlappedResult` was observed when transferring files using srt-xtransmit on Windows.
Therefore adding a timeout of 100 ms to wait for the result.
This PR is mainly a reincarnation of #974.
SRT version with the issue: v1.5.3 (after PR #2632).
=> [core] Overlapped send with 100 ms timeout on Windows.

srtcore/common.h
Running our server as a daemon we get a SIGABRT crash in our logs with no indication of what the assert is. We have some occurrences of unresolved crashes reporting SIGABRT. Our ASSERT function logs the assert condition, file and line number, a stack back trace and all threads state.
=> Allow custom-defined SRT_ASSERT() function

srtcore/channel.cpp, srtcore/channel.h
We used to directly cast the result of CMSG_DATA to in_pktinfo or in6_pktinfo. As stated in CMSG_FIRSTHDR manpage, alignement of the return value of this method is not guaranteed, and a memcpy should be done to manipulate it. 
For some reason, the use of the mutable m_acCmsgRecvBuffer and m_acCmsgSendBuffer also caused alignemnt issues when using it as msg_control field of msghdr. Declaring a new char each time instead of using the mutable one solved this issue.
=> [core] Fix alignment issues in cmsg header managment (#2830)

apps/srt-live-transmit.cpp, apps/transmitmedia.cpp, docs/apps/srt-live-transmit.md
Introduce a new Source type that considers RTP separately to UDP.
The intention is to drop bytes from the head of the input buffer. This enables the RTP header to be dropped for use cases where the receiving end cannot accept RTP. The default behaviour is to skip the first 12 bytes. Where `rtpheadersize` is set, the number of bytes to skip can be varied, to deal with extended RTP headers for example.
No effort is made in this initial implementation to attempt to parse the RTP headers in any way eg for reordering, extracting timing, detecting length.
This goes some way to addressing #136.
=> Add support for RTP input in srt-live-transmit

srtcore/utilities.h, srtcore/window.cpp, srtcore/window.h
Extracted longer and copy-paste-looking code into external functions. Potentially they can be reused in other measurement activities.
=> Refax around Window measurement facility

srtcore/channel.h, srtcore/srt_attr_defs.h
SRT_ATR_ALIGNAS was defined in the wrong place 
fixes  #2865
=> [maint] Moved declaration of SRT_ATR_ALIGNAS to fix a warning

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h
Fixed the condition in the receiver buffer to update the first non-read position in case of dropping upto a sequence number.
Both `m_iFirstNonreadPos` and `m_iStartPos` are positions in the RCV buffer, but were compared using the `CSeqNo::seqcmp` as if they were packet sequence numbers. This bug was causing an extra loop over packets in the receiver buffer to find the first gap. The position was restored correctly, but costs extra CPU resources.
Mainly noticeable in a broadcast group connection, when a packet is read from one member, but dropped from all the rest members.
=> [core] Fixed the RCV buffer non-read position update condition

srtcore/list.cpp
Reset the `m_iLargestSeq` back to `SRT_SEQNO_NONE` once the loss list is empty. This way if the next packet loss seqno has a distance more than `m_iSeqNoTH` from the `m_iLargestSeq`, it is not ignored and added to the loss list.
Fixes #2873.
=> [core] Fix : Sequence number in the ACK packet isn’t correct (#2873)

docs/API/API-socket-options.md, docs/features/latency.md
1. Added the list of options that are modified by the `SRTO_TRANSTYPE` option (per a complaint that the order of setting options matters).
2. Modified a bit the information about `SRTO_RCVLATENCY` option as the `features/latency.md` document explains it better and in more details.
=> Updated the documentation about latency and transtype

srtcore/core.cpp, srtcore/core.h, srtcore/fec.cpp, srtcore/packetfilter.cpp, srtcore/utilities.h
Fixes #2876 
The problem: To FEC for recording the EXOR from the data packet included is the whole packet as the sending unit, that is, including the auth tag, if AEAD is enabled. This was not regarded in the packet filter configuration and hence if AEAD was on the FEC facility has allocated too small buffer and caused this way a memory override.
Some more logs around FEC were added to show this case, they better stay there.
=> Fixed bug: packetfilter configuration did not include AUTH tag when AEAD is on

test/test_fec_rebuilding.cpp, test/test_socket_options.cpp
The problem: although the call of `srt_accept_bond` is given 2s timeout, it may still happen to not be enough, especially when testing on a weak, loaded machine.
Added the call to `this_thread::yield()` to make the thread switched to the spawned one so that it can at least start calling the `srt_connect` method before `srt_accept_bond()` is going to pick it up. This should help with falsely failing tests in Travis.
=> [test] Added yielding for tests that spawn a thread for connect

test/test_enforced_encryption.cpp
This marks the socket extraordinarily closed to cancel pending connections as invalid, and therefore it won't be tried to be closed in `teardown()`.
=> [test] Prevent socket from being closed twice in EE test

srtcore/core.cpp
The list of options was unordered, hence the binary search failed to find those options. This lead to `srt_setsockopt` returning an error if called on a connected group socket.
=> [core] Fixed POST options setting on a connected group.

test/test_socket_options.cpp
Added SRTO_MAXBW and SRTO_MININPUTBW to unit testing.
=> [tests] Added SRTO_MAXBW and SRTO_MININPUTBW to unit tests.

srtcore/core.h
=> [core] Fixed SRT_SOCKOPT_NPOST when ENABLE_MAXREXMITBW is defined.

srtcore/api.cpp, srtcore/group.cpp, test/test_bonding.cpp
Fixes #2887
Fixed: the group's getOpt returns one of the possible way:
1. A groupwise option returns the value from its own fields
2. A socketwise option is returned either from the option storage, or default values.
3. Some options can't be requested on a group and for them error should be reported.
There was also added some options that should have been returend as groupwise, but were not updated accordingly.
=> [core] Fixed the problem of getting option values from groups

CMakeLists.txt, srtcore/api.cpp, srtcore/logging.h, test/test_env.h, test/test_epoll.cpp, test/test_file_transmission.cpp, test/test_main.cpp, test/test_many_connections.cpp, test/test_reuseaddr.cpp, test/test_sync.cpp
1. Some small refax in api.cpp (shortcut variables, preparing for another change)
2. Added possibly handling -lognote option and added handling in FileUpload test.
3. Reworked test_reuseaddr.cpp to use a fixture and a propoer resource management.
4. Added similar fixes in other tests.
=> [test] Improved tests to avoid all-breaking asserts and inter-test messup

.github/workflows/s390x-focal.yaml
Add a new github action that builds srt and runs test on a s390x big endian architecture
Fixes #2702.
=> [build] Add a github action for big endian testing

srtcore/channel.cpp, srtcore/platform_sys.h, srtcore/srt.h, srtcore/srt_compat.c, srtcore/srt_compat.h
fixes #2862
Removed duplicate declaration of SRT_API
Moved around variables to avoid set but not used warnings
=> [core] Fix some warnings when compiling with mingw

apps/srt-live-transmit.cpp, apps/srt-tunnel.cpp, srtcore/common.cpp, srtcore/logging.cpp, srtcore/logging.h, srtcore/packet.cpp, srtcore/srt.h, testing/srt-test-live.cpp
Last merge (PR #2868) introduced a bug which makes ffmpeg impossible to build with SRT because of an incorrect include of srt_compat.h in srt.h
=> [core] Fix some indirect inclusion issues 

apps/verbose.hpp, srtcore/logging.h, srtcore/utilities.h, testing/srt-test-mpbond.cpp, testing/srt-test-relay.cpp, testing/testactivemedia.cpp, testing/testactivemedia.hpp, testing/testmedia.hpp
Fixed:
1. Wrong use of `using namespace std` in a header file
2. Added lacking `std::forward` in variadic print functions.
=> [core][maint] Formal errors fixed

.github/workflows/cxx11-ubuntu.yaml, srtcore/api.cpp
Also disabled sonarscanner of PRs from forks.
There seems to be some workaround for scanning PRs from a fork discussed here:
https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/34
=> [core] A minor change (use reference to const).

test/test_main.cpp, test/test_reuseaddr.cpp
Fixed the use of the server pollid in test_reuseaddr.cpp that was a "test global variable" with weird consistency rules.
=> [test] Fixed tests that were weirdly failing

.github/workflows/abi.yml
Add an action to check backward API/ABI compatibility
=> [build] Add an action to check API/ABI compatibility

haicrypt/hcrypt.c
This fixes key rotation when kk changes
Remote TX sends one even key on initial handshake, and later sends two (even and odd) keys in a KMREQ USER packet
Here is srt-live-transmit showing initial handshake, and key update:
--------------------
15:45:37.523916/SRT:RcvQ:w1.N:SRT.cn: processSrtMsg_KMRSP: cmd=4(KMRSP) len=224 KmState: SND=SECURED RCV=SECURED 15:45:37.524445/SRT:RcvQ:w1.N:SRT.cn: @234271448: Connection established to: 10.129.73.178:5000 SRT source connected
15:45:42.285301/SRT:RcvQ:w1!W:SRT.cn: KMREQ/rcv: (snd) Rx process failure - BADSECRET 15:45:42.285372/SRT:RcvQ:w1.N:SRT.cn: processSrtMsg_KMREQ: cmd=3(KMREQ) len=288 KmState: SND=BADSECRET RCV=BADSECRET 15:45:42.285410/SRT:RcvQ:w1!W:SRT.cn: @234271448: KMREQ FAILURE: BADSECRET - rejecting per enforced encryption …
=> [crypto] HaiCrypt_Clone(): sets up receiver clone properly

docs/API/API-socket-options.md, docs/API/statistics.md, srtcore/core.cpp
Previously unencrypted packets were being dropped in case AES-GCM mode was used.
With this change, they are being dropped if the KM connection state is "Secured".
It respects the SRTO_ENFORCED_ENCRYPTION option that allows connections without encryption, in which case the RCV KM state would be "Unsecured".
=> [core] Drop noenc packets if RcvKmState is "secured".

CMakeLists.txt, docs/build/build-options.md
If -DUSE_ENCLIB is not specified, openssl-evp will now be the default encryption used
=> [build] Switch default enclib from openssl to openssl-evp

srtcore/channel.cpp, srtcore/packet.cpp, srtcore/packet.h, srtcore/utilities.h
Use `CPacket::toNetworkByteOrder()` and `CPacket::toHostByteOrder()` for byte order conversion instead of byte-level `htonl` and `ntohl` functions.
The length of the control packet is always a multiple of 4.
Tested receiving and sending without encryption using `srt-xtransmit`.
=> [core] Use common functions for byte order conversion.

srtcore/api.cpp, srtcore/core.cpp, srtcore/queue.cpp
It is not clear from SRT logs which SRT socket ID is associated with which local and remote IP. It is even more viable in group connections. Therefore a 'note'-level log message has been added one a connection is accepted by the listener.
Some logs were downgraded from 'note' to 'debug'.
```shell
srt-xtransmit receive "srt://:4200?groupconnect=1" --enable-metrics -v --loglevel note
12:34:57.347682 [I] Log level set to note
12:34:57.359667 [I] SOCKET::SRT srt://:4200: bound to ':4200'.
12:34:58.939000/T18380.N:SRT.cn: PASSING request from: 127.0.0.1:5200 to agent:121901312
12:34:58.939000/T18380.N:SRT.cn: Listener managed the connection request from: 127.0.0.1:5200 result:waveahand
12:34:58.940000/T18380.N:SRT.cn: PASSING request from: 127.0.0.1:55596 to agent:121901312 …
```
=> [core] Minor connection logging improvement.

srtcore/group.cpp
Count the number of packets dropped by a group based on the offset of the base RCV seqno towards seqno of a packet being read.
Fixes #2933.
=> [core] Fixed stats counting packets dropped by a group.

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp
Valid for a broadcast group member dropping existing packets from the RCV buffer because they were read from another member, not because they are missing. Such packets are now counted as 'discarded', and not included in the 'dropped' counter.
Fixes #2879.
Closes #2882.
=> [core] Stats: do not count discarded packets as dropped.

srtcore/core.cpp, srtcore/core.h
The synchronization is done upon reading from a group (`CGroup::recv(..)`).
Removed `CUDT::dropToGroupRecvBase()` function.
=> [core] Removed group syncing when sending control ACK.

srtcore/buffer_rcv.h, srtcore/core.cpp, srtcore/core.h, srtcore/queue.cpp
Extracted changes from #2527 that don't touch the logic and thus can be safely merged. Having them merged would reduce the reviewing scope of PR #2527. Also there might be follow up changes to the TSBPD logic partially correlated with #2527, so I would like to avoid merge conflicts as much as possible.
- Minor internal logging format changes.
- Renamed `CUDT::m_bTsbPdAckWakeup` to `m_bTsbPdNeedsWakeup`. There is no need to wait for an ACK to be sent as it does no longer change the read-ready state.
- Added some function to the `CRcvBuffer`.
=> [core] Minor internal logging format changes.

srtcore/group.cpp
A follow-up for #2934.
Only show sequence numbers of packets being dropped by a group.
=> [core] Fixed group RCV drop sequence range log.

srtcore/group.cpp
=> [core] Group set the RCV base seqno using peer ISN.

docs/API/API-socket-options.md, docs/API/statistics.md, haicrypt/hcrypt.c, srtcore/api.cpp, srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h, srtcore/core.cpp, srtcore/core.h, srtcore/fec.cpp, srtcore/group.cpp, srtcore/packetfilter.cpp, srtcore/queue.cpp, srtcore/utilities.h
This is a custom release of SRT v1.5.3 with some bug fixes that will be used in certain solutions until SRT v1.5.4 is released.
- PR #2945 fixes group RCV base seqno initialization.The group can now detect packet drop before the first packet is read(issue #2936).
- PR #2942 Fixed group RCV drop sequence range log.
- PR #2939 Minor internal logging format changes.
- PR #2938 fixes group packet drops(issue #2937), also fixes group fields initialization(issue #2941).
- PR #2935 Removed group syncing when sending control ACK.
- PR #2934 Fixed stats counting packets dropped by a group.
- PR #2932 Stats: do not count discarded packets as dropped.
- PR #2930 Minor connection logging improvement.
- PR #2921 Drop non encrypted packets if RcvKmState is "secured".
- PR #2905 Fix HaiCrypt_Clone() : …
=> Custom release SRT v1.5.3a

srtcore/core.cpp, srtcore/group.cpp
The `CUDTGroup::recv_WaitForReadReady(..)`  function forms the list of read-ready member sockets.
If a socket was not signaled as read-ready, its receiver buffer is still checked using the `CRcvBuffer::isRcvDataReady(..)` function. The first mistake is that the current time is not provided as an argument, so it always returns false when TSBPD mode is enabled.
Providing the current time greately redeces false drops of packets by a group (in the test setup described in #2937), but still occasional drop happens sometimes.
Therefore a member socket is instead checked for the existence of the very next packet to read.
Fixes #2937.
=> [core] Fixed group recv read-ready check.

srtcore/core.cpp
=> [core] Fixed checking the m_GroupOf is not NULL.

srtcore/group.cpp
make fails when ./confgure --enable-testing
`/home/build/srt_kageds/srtcore/group.cpp: In member function ‘void srt::StabilityTracer::create_file()’:
/home/build/srt_kageds/srtcore/group.cpp:2577:46: error: no matching function for call to ‘std::basic_ofstream<char>::open(const string&, const openmode&)’
m_fout.open(fname, std::ofstream::out);
^
/home/build/srt_kageds/srtcore/group.cpp:2577:46: note: candidate is:
In file included from /home/build/srt_kageds/srtcore/udt.h:86:0,
from /home/build/srt_kageds/srtcore/api.h:60,
from /home/build/srt_kageds/srtcore/group.cpp:5:
/usr/include/c++/4.8.2/fstream:713:7: note: void std::basic_ofstream<_CharT, _Traits>::open(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = …
=> fix build issue when configure --enable-testing

srtcore/core.cpp
Conditional jump or move depends on uninitialised value of `m_stats.traceBelatedTime`.
```shell
==15925== Thread 4 SRT:RcvQ:w1:
==15925== Conditional jump or move depends on uninitialised value(s)
==15925==    at 0x32B6BB: unsigned long CountIIR<unsigned long>(unsigned long, unsigned long, double) (core.h:89)
==15925==    by 0x31E4E3: srt::CUDT::handleSocketPacketReception(std::vector<srt::CUnit*, std::allocator<srt::CUnit*> > const&, bool&, bool&, std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > >&) (core.cpp:10078)
==15925==    by 0x31FD3C: srt::CUDT::processData(srt::CUnit*) (core.cpp:10475)
==15925==    by 0x3593AF: srt::CRcvQueue::worker_ProcessAddressedPacket(int, srt::CUnit*, srt::sockaddr_any const&) (queue.cpp:1475)
==15925==    by 0x358586: …
```
=> [core] Fixed missing traceBelatedTime initialization.

srtcore/group.cpp
(TRIAL FIX #2959)
This changes the following:
1. In case when sending failed over several links, waiting for unblocking any socket is done only if:
* in blocking mode
* no socket has succeeded
2. If at least one link succeeded, but there are any failed, failed links are immediately set closed.
=> [core] Fixed broadcast group: cut failed links on partial sending success

srtcore/core.cpp
The debug assertion was added in PR #1628 (SRT v1.4.3). It assumes a timestamp of an ACK packet is positive.
However, a timestamp value of 0 is a valid value. For an ACK it is unlikely to happen as the first full ACK is sent only after 10 ms (except for issue #2829 in SRT v1.5.3). Also handshaking takes some time.
Still lite ACK may be sent earlier in case of higher data rates.
Anyway, removing the debug assertion.
=> [core] Removed a wrong assertion about ACK timestamp.

srtcore/core.cpp, srtcore/core.h
Extracted from PR #2893.
```
WARNING: ThreadSanitizer: data race (pid=5444)
Write of size 8 at 0x7ba80005f118 by thread T1 (mutexes: write M226, write M223, write M898885562122236320, write M898604087145525592):
#0 srt::sync::CThread::join() srt/srtcore/sync_posix.cpp:442 (srt-xtransmit+0x464f2a)
#1 srt::CUDT::releaseSynch() srt/srtcore/core.cpp:7839 (srt-xtransmit+0x34d600)
#2 srt::CUDT::closeInternal() srt/srtcore/core.cpp:6332 (srt-xtransmit+0x34c769)
#3 srt::CUDTSocket::breakSocket_LOCKED() srt/srtcore/api.cpp:127 (srt-xtransmit+0x28d9e1)
#4 srt::CUDTUnited::garbageCollect(void*) srt/srtcore/api.cpp:3328 (srt-xtransmit+0x28f180)
Previous read of size 8 at 0x7ba80005f118 by thread T4:
#0 srt::sync::CThread::joinable() const srt/srtcore/sync_posix.cpp:424 (srt-xtransmit+0x464ce9)
#1 …
```
=> [core] Fix TSBPD thread create/join protection.

srtcore/api.cpp
=> [core] Put the use of m_bGCStatus under m_InitLock

README.md
Added SonarCloud badge. The quality gate is now passing after C++11 and higher warnings have been disabled on the project due to support of C++03.
=> [docs] Added SonarCloud badge.

CMakeLists.txt, haicrypt/cryspr.c, haicrypt/haicrypt.h, haicrypt/hcrypt.c, haicrypt/hcrypt.h, haicrypt/hcrypt_ctx.h, haicrypt/hcrypt_ctx_rx.c, haicrypt/hcrypt_ctx_tx.c, srtcore/core.cpp, srtcore/crypto.cpp, srtcore/crypto.h
- Changed the IV vector length to 12 bytes in the case of AES-GCM when peer's SRT version is 1.5.4 or above;
- Fixed AAD byte order when peer's SRT version is 1.5.4 or above.
The Initialisation Vector (IV) for the AES-CTR encryption mode is derived by exclusive ORing the first 112 bits of the Salt provided in the Keying Material with the packet sequence number (PktSeqNo) in the SRT header, and left-shifting the resulting value by 16 bits:
~~~~~~~~~~~
IV = (MSB(112, Salt) XOR PktSeqNo) << 16
~~~~~~~~~~~
Thus the counter (keystream) used by the AES engine is the 128-bit value obtained by concatenating the IV with the block counter ("ctr"):
~~~~
*    0   1   2   3   4   5  6   7   8   9   10  11  12  13  14  15   bytes
* +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+  ^
* …
=> Improved AES GCM encryption, changed IV length to 12 bytes.

examples/recvlive.cpp, examples/sendmsg.cpp, test/test_reuseaddr.cpp, testing/srt-test-relay.cpp, testing/testmedia.cpp
Fix variables shadowing that is now a warning with gcc 13
=> [tests] Fix warnings when compiling with g++ 11.4.0 on ubuntu 24.04

.appveyor.yml, scripts/build-windows.ps1
VC 2013 is so old that it's not downloadable from anywhere.
VC 2017 is still available as the "oldest" one.
VC 2015 could be still around, but it's also no longer supported and no longer downloadable.
=> [maint] Removed VC 2013. Added VC 2022

srtcore/sync.cpp, srtcore/sync.h, test/test_sync.cpp
=> [core] Add a shared mutex class

srtcore/api.cpp
Fixed a data race upon a simultaneous access to listener's config (`CUDT::m_config`) from SRT internal `newConnection(..)` and the app thread called for `srt_listen()`. Locking the listener's `m_ConnectionLock`.
Replaces #2961.
Fixes #2970.
=> [core] Fixed a data race on listener's config.

srtcore/queue.cpp
The `CRcvQueue::m_counter` variable is shared between threads. The `THREAD_STATE_INIT` macro used the value to form the thread name, but the value could be the same for several threads.
The thread must already have a name set via `ThreadName`. Therefore just extract it via `ThreadName::get(std::string&)`.
Fixes #2973.
=> [core] Fixed THREAD_STATE_INIT usage in CRcvQueue.

CMakeLists.txt, apps/verbose.cpp, apps/verbose.hpp
- Verbose log now has a single version with a mutex lock.
- Removed `SRT_ENABLE_VERBOSE_LOCK` build definition.
Fixes #2145.
I am not quite sure if the implementation of the Verbose::Log with a mutex is thread safe given the `template <class V> Log& operator<<(const V& arg)` is not protected by a mutex lock. What's protected is putting the end of line symbol on log destruction.
```c++
Verb() << VerbLock << "Starting TargetMedium: " << this;
```
=> [apps] Fixed verbose linkage difference.

apps/verbose.hpp, testing/srt-test-live.cpp, testing/srt-test-multiplex.cpp
1. Fixed: added atomic for lockline to avoid races when using line locking in Verb.
2. Added empty constructors in Log class to avoid copying when returning temporary object as proxy for operator <<.
3. Fixed invalid call to std::forward to allow variadic versions of Verb().
4. Changed operator<< to variadic Verb version in two app files.
=> [devel] Fixed atomic setting of locked line in Verb

srtcore/core.cpp, srtcore/logging.h, srtcore/packet.h
The lock was missing. The change is extracted from PR #2893.
=> [core] Apply lock on RCV buffer read-ready check.

srtcore/buffer_tools.cpp, srtcore/buffer_tools.h
Likely the initial idea was to make the `CSndRateEstimator` class independent from SRT-specific constants. But packet header sizes were missing in the retransmission rate estimation.
Fixes #3006.
SRT version affected: v1.5.3.
=> [core] Include packet header in rexmit BW calculation.

srtcore/core.cpp, srtcore/core.h
Made log frequency timeout per logid.
Fixes #2739.
=> [core] Slowdown ACKACK outoforder log frequency.

test/test_snd_rate_estimator.cpp
Added SRT header in unit tests for `CSndRateEstimator`.
Broken after #3008.
=> [tests] Fixed unit tests for CSndRateEstimator.

srtcore/api.h, srtcore/group.cpp
Fixes #3010 by not holding the m_GroupLock wile calling getOpt on a member socket.
=> [core] Fixed group lock-order-inversion.

test/test_bonding.cpp, test/test_buffer_rcv.cpp, test/test_connection_timeout.cpp, test/test_losslist_rcv.cpp, test/test_socket_options.cpp, test/test_sync.cpp, test/test_utilities.cpp, testing/srt-test-mpbond.cpp, testing/testmedia.cpp
<details><summary>AppleClang 15 Warnings</summary>
```shell
[ 66%] Building CXX object CMakeFiles/test-srt.dir/test/test_buffer_rcv.cpp.o
In file included from /Users/runner/work/srt/srt/test/test_buffer_rcv.cpp:3:
/opt/homebrew/include/gtest/gtest.h:1394:11: warning: comparison of integers of different signs: 'const int' and 'const unsigned long' [-Wsign-compare]
if (lhs == rhs) {
~~~ ^  ~~~
/opt/homebrew/include/gtest/gtest.h:1413:12: note: in instantiation of function template specialization 'testing::internal::CmpHelperEQ<int, unsigned long>' requested here
return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
^
/Users/runner/work/srt/srt/test/test_buffer_rcv.cpp:239:9: note: in instantiation of function template specialization 'testing::internal::EqHelper::Compare<int, …
```
=> [tests] Fixed unit tests compiler warnings AppleClang 15.

CMakeLists.txt, srtcore/common.cpp, srtcore/core.cpp
Fixes #1667
There was some kinda completely "out of sense" setting of +W epoll readiness flag for a listener socket at the moment when a new accepted socket was successfully spawned.
This is actually an old UDT library bug, maybe insignificant, but might bear consequences, it's present at the end of this function (in SRT it was renamed to `processConnectionRequest`):
```
int CUDT::listen(sockaddr* addr, CPacket& packet)
```
The standard rules for setting epoll flags other than those for data-read-ready and data-write-ready should follow the manner of TCP and Linux epoll, that is:
* SRT_EPOLL_OUT is set on the connecting socket to declare connection success. This is coincidentally the same with a statement that every newly connected socket is automatically ready to write, and it remains …
=> [BUG] Removed setting +W for a listener socket after accept ready

srtcore/threadname.h
Reference: https://man.netbsd.org/pthread_setname_np.3
=> pthread_setname_np(3) has different signature on NetBSD

test/test_env.h
This fixes a bug in test_env.h, which made options available only for fixture-based tests.
With this fix, options are available for all tests.
Extracted from #2444
=> [test] Added option handling also to non-fixture-based tests

configure-data.tcl
This fixes the handling of `--with-compiler-type` option for `./configure`:
* Handles properly gcc -> g++ name transformation, also with version suffix
* Sets up properly CMAKE_C_COMPILER and CMAKE_CXX_COMPILER options
Compiler prefix is handled like before.
This change is extracted from #2444 for cleanup.
=> Fixed proper compiler selection for --with-compiler-type configure option

apps/apputil.hpp, testing/srt-test-mpbond.cpp
This adds a friendly C++ wrapper over the `srt_setsockflag` call:
```
srt::setopt(sock)[OPTION] = value;
```
instead of
```
type value = something;
srt_setsockflag(sock, OPTION, &value, sizeof value);
```
Also an example usage was added to `srt-test-mpbond` app.
=> [apps] Added setopt utility for easily setting socket options

test/test_bonding.cpp
Added a test for Bonding, which does the following thing:
1. Sets up a listener on port 5555.
2. Connects the members, in this order: port 5556, 5555, 5555 (the first one trying to connect a nonexitent listener).
This is to test if when the initially created common ISN for the group holds even if the very first connection attempt fails.
This is created as an attempt to prove no failure against the proposal in #2735.
=> [test] Added test with bonding first connecting socket failure

.github/workflows/cxx11-win.yaml, srtcore/congctl.cpp, srtcore/handshake.cpp, srtcore/logging.h, srtcore/queue.h, srtcore/utilities.h, testing/srt-test-live.cpp, testing/srt-test-multiplex.cpp, testing/srt-test-relay.cpp, testing/testactivemedia.cpp, testing/testactivemedia.hpp, testing/testmedia.cpp, testing/testmedia.hpp, testing/testmediabase.hpp
Changes are added for various reasons.
Inline comments have been added to explain the reason of particular changes.
=> [core][apps] Some refactoring per clang-reported warnings

srtcore/common.cpp, srtcore/common.h, srtcore/epoll.cpp
`FormatLossArray` and `PrintEpollEvent` have been moved bodies to common.cpp.
=> [maint] Moved debug-related functions to common

srtcore/api.h, test/test_bonding.cpp
Problem: `SocketKeeper::socket` field could remain undefined in case when `acquire()` was called with `s == NULL`.
=> Fixed initialization problem in SocketKeeper version with acquire

.github/workflows/cxx11-macos.yaml, .github/workflows/cxx11-ubuntu.yaml
Added `-DCMAKE_COMPILE_WARNING_AS_ERROR=ON` to Ubuntu and macOS GitHub actions.
=> [build] Treat warnings as errors in macOS action.

srtcore/sync.h
C++20: template ID is not allowed in constructor and build fails for GCC>13 and/or c++>=20.
```
/home/jsantiago/tt09/srt/srtcore/sync.h:575:24: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
575 |     CSharedObjectPtr<T>()
|                        ^
/home/jsantiago/tt09/srt/srtcore/sync.h:575:24: note: remove the ?< >?
```
=> Fix Build GCC>13 and C++>=20.

apps/uriparser.cpp
The `uri_decode` function wasn't interpreting the % sequence properly if the value was 00 and stopped on the first error.
The fix:
* %00 is properly interpreted as a NUL character
* If the % coding syntax is erroneous, the % character is shipped as is and parsing continues since the next character
=> [apps] Fixed URI decoding in UriParser

srtcore/buffer_tools.cpp, srtcore/tsbpd_time.cpp, srtcore/tsbpd_time.h
Increased mutex protection of the TSBPDTime class, switched from a regular mutex to a shared mutex.
Fixes #3036, #3037.
=> [core] Improved mutex protection of the TSBPD.

haicrypt/hcrypt.h, haicrypt/hcrypt_ctx.h, haicrypt/hcrypt_msg.h, haicrypt/hcrypt_rx.c, haicrypt/hcrypt_xpt_srt.c
As reported in #3035, `srt/haicrypt/hcrypt_xpt_srt.c` has two definitions of the static variable `_hcMsg_SRT_MsgInfo`:
```c
// Line: 68
static hcrypt_MsgInfo _hcMsg_SRT_MsgInfo;
// Line: 156
static hcrypt_MsgInfo _hcMsg_SRT_MsgInfo;
```
One more problem is the `.parseMsg` field off the structure that is initialized with a pointer to `hcryptMsg_SRT_ParseMsg` function. The `hcryptMsg_SRT_ParseMsg` function in its turn uses the static _hcMsg_SRT_MsgInfo internally.
To resolve this interdependency the `hcryptMsg_SRT_ParseMsg` function is made visible and now requires a pointer to a `hcrypt_MsgInfo`  structure instead of using the static variable implicitly.
The `_hcMsg_SRT_MsgInfo` can now be const and initialized once the following way:
```c
static const hcrypt_MsgInfo _hcMsg_SRT_MsgInfo = { …
```
=> [core] Fixed static variable usage in the crypto module.

scripts/win-installer/build-win-installer.ps1, scripts/win-installer/install-openssl.ps1, scripts/win-installer/libsrt.nsi
On Windows, OpenSSL 3.3.2 (and maybe some previous versions) has changed two things:
1. The way the OpenSSL packages are located from slproweb has changed => need to update install-openssl.ps1
2. After installation of OpenSSL, the layout of library files was also completely changed => need to update build-win-installer.ps1 and libsrt.nsi
Before releasing SRT 1.5.4 and building the corresponding Windows installer, it is recommended to upgrade OpenSSL on the build system, i.e. run install-openssl.ps1
=> Update Windows installer for new OpenSSL versions

srtcore/buffer_rcv.cpp, srtcore/tsbpd_time.cpp, srtcore/tsbpd_time.h
Use better names for time-related member functions of the CTsbpdTime class.
Resolves #3043.
=> [core] Renamed TSBPD class functions.

CMakeLists.txt
Set `-stdc=99` compiler flag on srt_virtual target to fix #3048.
✔️  Tested with GCC 4.8.5.
=> [build] Apply -stdc=99 on SRT library.

apps/verbose.hpp
The `atomic.h` header of the SRT project can include `sync.h` header in the following case:
```c++
#if defined(ATOMIC_USE_SRT_SYNC_MUTEX) && (ATOMIC_USE_SRT_SYNC_MUTEX == 1)
#include "sync.h"
#endif
```
It leads to the compilation error because `sync.h` includes `atomic.h` and later `atomic_clock.h`:
```shell
[ 60%] Building CXX object /apps/socketoptions.cpp.o
In file included from /srtcore/sync.h:1069,
from /srt/srtcore/atomic.h:104,
from /srt/apps/verbose.hpp:15,
from /srt/apps/socketoptions.cpp:12:
/srt/srtcore/atomic_clock.h:25:5: error: 'atomic' does not name a type; did you mean 'atoi'?
atomic<int64_t> dur;
^~~~~~
atoi
/srt/srtcore/atomic_clock.h: In constructor 'srt::sync::AtomicDuration<Clock>::AtomicDuration()':
/srt/srtcore/atomic_clock.h:30:37: error: class …
```
=> [apps] Use sync.h instead of atomic.h in the verbose module.

scripts/release-notes/generate_release_notes.py, srtcore/group.cpp
The GCC 13 compiler produces a warning complaining that the length used for `std::copy` is out of bounds of an integer (or any other 1-byte type).
The source of this complaint was that the length was set in the `getOptDefault`, instead of a direct `sizeof` value. Even though the length returned for a Boolean is anyway determined via `sizeof(Type)` called from a template function, it is probably not that safe anyway.
Therefore just assert (in a debug build configuration) that the size returned is similar to the `sizeof` call used in the `importOption` function.
Fixes #3064.
=> [core] Resolved GCC13 build warning regarding std::copy of a bool.

test/test_socket_options.cpp
Using `std::array` where possible.
Within the work on #3074.
=> [tests] Minor clean up of socket options tests.

README.md
Now using conan.io URLs directly.
=> [docs] Updated conan badge links.

srtcore/platform_sys.h
=> [MAINT] Apply conditional to setting a macro for IPv6 on Mac

CMakeLists.txt, docs/API/API-socket-options.md, srtcore/channel.cpp, test/test_env.h, test/test_reuseaddr.cpp
Fixes #3095
Changes: maintained correctly and more clearly conditions for setting IP options on the UDP socket. Prevented the "ignored" case.
Added error logs that describe the problem, should one occur.
Added test that checks if setting these options.
=> [MAINT/TEST] Clarified conditions for setting IPTOS/TTL options. Added UT for this.

scripts/srt-proxy.py, srtcore/core.cpp
Fixes #3088 
The problem: upon reception of the rogue ACK or LOSSREPORT, the procedure that should cause breaking the connection puts the connection in a "stalled" state, where every single ACK since that point on is rejected, but the connection is still maintained and keepalives are exchanged. The connection can no longer be used for transmission, but it doesn't break.
=> [core] Fix stalled connection that should break after rogue NAK/ACK reception

scripts/win-installer/README.md, scripts/win-installer/build-win-installer.ps1, scripts/win-installer/install-openssl.ps1, scripts/win-installer/libsrt.nsi, srtcore/window.cpp
When building the libsrt binary installer for Windows, also build the libraries for Arm64 target, in addition to Win32 and Win64. The build can be performed anywhere, Visual Studio can build for distinct targets. 
**Before the build on an Intel machine, make sure that your VS installation includes the build tools for Arm64. See `scripts/win-installer/README.md` for more details.**
On existing build systems, be sure to run `install-openssl.ps1` again once to make sure that the Arm64 libraries for OpenSSL are installed.
Also fixed a few harmless warnings.
The resulting libsrt Windows installer has been successfully tested using TSDuck `srt` plugin (input and output) on a Windows Arm64 virtual machine on a Mac with "Apple Silicon" CPU (ie. Arm64).
=> Added support for Windows on Arm64

scripts/win-installer/README.md, scripts/win-installer/build-win-installer.ps1, scripts/win-installer/install-openssl.ps1, scripts/win-installer/libsrt.nsi
The Windows installer provides the SRT libraries for all possible architectures. However, SRT needs OpenSSL and OpenSSL for Windows cannot install its Arm64 libraries on Intel systems. More precisely, on Arm64 systems, we may install OpenSSL libraries for x86, x64 and Arm64. However, on Intel systems, OpenSSL libraries can be installed for x86, x64 only. This is an unfortunate limitation of the OpenSSL installer for Windows.
As a consequence, when building the libsrt installer in a Windows Intel system, the installer now contains the x86 and x64 libraries only. To build a libsrt installer with the binaries for the three architectures, the build must be performed on a Windows Arm64 system.
This is not easy to achieve on automated CI systems where Windows systems are usually Intel only. …
=> Fix Windows installers

apps/transmitmedia.cpp, scripts/build-windows.ps1, testing/testmedia.cpp, testing/testmedia.hpp
=> [apps] Fixed correct bind address selection for windows multicast

srtcore/channel.cpp, srtcore/core.cpp
Fixes #3137.
Changes:
1. Unlock the mutex of m_RcvBufLock, which should guard the ACK sequence recorded by another thread. The lock is not necessary at the moment when the prepared packet is about to be sent.
2. As the nonblocking mode was set using either `O_NONBLOCK` flag (by `fcntl`) or short timeout on the socket, depending on the system, for consistency the non-blocking mode should be set in both directions. Therefore added setting also `SO_SNDTIMEO` flag with the same value.
=> [core] Fixed accidental blocking on sendmsg call

test/test_bonding.cpp, test/test_connection_timeout.cpp
Fixed tests:
1. TestConnectionTimeout.BlockingLoop
This test was incorrectly reusing once created socket to do connection failure tests. This test didn't work correctly in case when connection somehow succeeded, and it breaks the rule that a socket should be used for connection, and then whether it succeeds or not, it should be used for connection possibly, and then closed - not connected multiple times after a failure.
2. Bonding.ConnectNonBlocking
This test was often failing in Travis because it relies too much on timing: connection is expected to return an error code if it is in progress, but for this the peer (running in a thread here) should not accept the connection until this check was done. Therefore there are needed synchronization points in the form of the promise. This prevents …
=> [TEST] Fixed tests to avoid mistakes in CI

.gitmodules, scripts/abi-check.tcl
This adds a script you can run manually to do ABI checks.
You need to have the old and new version of the library first compiled in DEBUG mode.
=> [MAINT] Added script for manual ABI checks

srtcore/buffer_tools.cpp, srtcore/buffer_tools.h, srtcore/core.cpp, srtcore/stats.h
fixes #1812  - A new class was created to compute received and sent average rates for last second, independent of the call interval.
=> [core] New moving average value for sent/recv rates over last second

srtcore/api.cpp, srtcore/core.cpp, srtcore/epoll.cpp, srtcore/epoll.h, test/test_bonding.cpp
There was sometimes reported a log, sometimes with lots of flooding, which complained about event update on a socket that could not be identified. This was happening due to that a socket, which's ID has been already removed from the dispatch table, was trying to update the readiness state in epoll. Finding an already closed socket was impossible, while it was done as the last chance update so that the application picks up the error. This wasn't possible to be done simply because epoll system could not find the socket anyway.
The change was done so that the socket is immediately removed from the epoll system when it's going to be removed from the dispatch table. Note that epoll cannot operate on nonexistent sockets, so it cannot set it any readiness state if it's already closed. Hence …
=> [BUG] Fixed desynch between deleted socket and unsubscribing from epoll (misleading log flood)

.github/workflows/abi.yml, CMakeLists.txt, scripts/abi-check.tcl, scripts/get-build-version.tcl
This refactors the ABI checker CI entry in order to do the following:
1. Checks are done first on the current version. If the current version has patch version 0, meaning it's first in the line, the base version isn't installed and compiled and no ABI checks are done.
2. Building the base version and performing the checks are done in separate jobs so that they can be conditionally avoided.
3. (Pending) The resulting build artifacts - the report html file - should be made available.
=> [DEV] Updated ABI checker to use correct version ABI checks.

CMakeLists.txt
As of CMake 4.0, backward compatibility with versions of CMake older than 3.5 is removed.
This change is inspired/informed by similar changes in other projects:
- https://github.com/GrokImageCompression/grok/commit/40af3b5f2b9343d162a829e91868976ed2bbf563#diff-ddbe22569a7b36432ac7278e7a656e3e16f1e8fccbd848a5f35957affb1a90c8R13-R16
- https://gitlab.winehq.org/mono/mono/-/commit/831415edd2a578a2b4851996ca796f47dbc3f2f3#69a14f67200ae7e0007a07b7ca8633d08f812b4a_2_1
=> [build] Update for compatibility with CMake 4.x

srtcore/api.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp, test/test_bonding.cpp
Changes:
1. Fixed removal of all groups in the procedure of total removal (called from `CUDTUnited::cleanup`). That was reported as a leak.
2. Fixed access of m_QueuedSockets without m_AcceptLock.
3. Fixed usage of `CUDT::m_stats.tsStartTime` without m_StatsLock.
4. Getting option by asking the first socket: untangled the lock order of m_GroupLock and m_GlobControlLock; changed the order by attempting to extract the socket by ID after taking it from the group member container.
5. test: change variable to atomic to avoid data race.
=> [core] Fixed problems found by thread and memory sanitizers

srtcore/epoll.cpp
The loop that was rolling over the events in the container was incorrectly increasing the total counter over the number of actually filled items in the array. The loop was refactored to return the exact number of array items filled.
=> [core] Fixed bug in srt_epoll_uwait: wrong number of sockets returned

docs/API/API-functions.md, srtcore/srt_c_api.cpp
Fixes: #3184
Changes:
1. The `srt_strerror` now returns a message contained in the array of generated error messages. This is constant and reentrant.
2. The documentation was updated: the reentrancy note removed, added info about ignored parameter.
=> [core] Fixed reentrancy problem of srt_strerror
