README.md
Add a simple example of using the stransmit app to demonstrate OpenSRT.
=> README.md: Add simple stransmit example

README.md
Compiling on CentOS 6 requires the newer gcc libs provided by the SCL devtoolset chain since sample app requires C++11.
Running on CentOS 6 requires libstdc++ to be statically linked on compile, otherwise stransmit will fail to run with the following errors:
```
stransmit: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by stransmit)
stransmit: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.19' not found (required by stransmit)
stransmit: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.15' not found (required by stransmit)
```
=> Add instructions for CentOS 6

srtcore/netinet_any.h
Use an explicit static_cast in coverting a `size_t` to a `socklen_t`.
Before this fix, the warning
```
warning C4267: '=' : conversion from 'size_t' to 'socklen_t', possible loss of data
```
is produced, and now it's suppressed. This is problematic because this also produces a warning in code using SRT, which could have warnings set as errors.
=> Fix warning under MSVC

apps/stransmit.cpp
srt_startup is necessary for proper stransmit work as WSAStartup called for Windows and many other things inited.
srt_cleanup also required
=> srt_startup call required in stransmit main function

CMakeLists.txt, scripts/haisrt.pc.in
This fixes the name of a variable used in haisrt.pc.in, it was named differently in CMakeLists. Also added an alternative name `srt.pc` to the `haisrt.pc` - this wasn't an intention since the very beginning to use `haisrt.pc` name, it should be `srt.pc`. But we have to leave it currently with old name as well, for backward compatibility. It will be removed at some point in future.
=> Small fixes for build and installation

srtcore/core.cpp
This fixes #41 by making sure CUDT::processData doesn't hold two locks at the same time.
=> Fix deadlock condition

haicrypt/hc_openssl_aes.c, haicrypt/hc_openssl_evp_ctr.c
The current code doesn't bulid against OpenSSL 1.1 which is starting to be included as the default in newer Linux distributions. This patch fixes the little build issues, but I haven't done any testing.
This should resolve issue #68
=> OpenSSL 1.1 support

CMakeLists.txt
Signed-off-by: Justin Kim <justin.kim@collabora.com>
=> CMakeLists.txt: Add SOVERSION for libsrt

apps/stransmit.cpp
Initialize srt_epoll in SrtTarget non-blocking mode to correct "Invalid epoll ID".
=> Initialize srt_epoll for SrtTarget non-blocking

common/socketoptions.hpp
This was detected during development of congestion control restoration. The type of SRTO_MAXBW option handling in `CUDT::setOpt` is `int64_t`, this was an overlook. Applications using `setsockopt` with SRTO_MAXBW are not affected, although they will suffer the same problem unless they use the correct data type - `int64_t`.
=> Fixed bug: incorrect data type for maxbw option

CMakeLists.txt, common/appcommon.hpp, common/srt_compat.c, common/srt_compat.h, common/transmitmedia.cpp
This fixes the problem with reading from UDP multicast on Windows, which was using the multicast IP address for the call to `bind()`. This works on Linux, but somehow doesn't work on Windows. Specifically for Windows, the IP address that designates the network device (INADDR_ANY by default, or the address specified in `adapter` attribute) is used for binding, not the IP address of the multicast group. Note that subscription to the multicast group includes both the IGMP address and the adapter address, and it works on Linux without change, so the fix is provided for Windows and Cygwin only.
The problem was reported in issue #101
=> Fix multicast binding problem on Windows

common/socketoptions.cpp, common/utilities.h, haicrypt/hc_openssl_aes.c, haicrypt/hc_openssl_evp_ctr.c, haicrypt/hcrypt.h, haicrypt/hcrypt_ctx_tx.c, srtcore/api.cpp, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/common.cpp, srtcore/common.h, srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp, srtcore/crypto.h, srtcore/epoll.cpp, srtcore/epoll.h, srtcore/handshake.h, srtcore/logging.h, srtcore/packet.h, srtcore/queue.cpp, srtcore/queue.h, srtcore/smoother.cpp, srtcore/srt.h, srtcore/srt4udt.h, srtcore/srt_c_api.cpp, srtcore/udt.h
=> A bunch of refactoring before changes in the API

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp
Also, locking is done only after the current time is read.
Per issue #113
=> Shifted locking around drift tracer to inside the function.

.appveyor.yml, gather-package.bat
I added steps to catch resulting files from build process into Zip files for Win32 build.
This is useful, since it then provides correct pre-compiled SRT binaries without variances from local build changes or OpenSSL versions.
It also makes utilities like 'stransmit' available pre-compiled.
I also scrape up the OpenSSL and PThreads binaries, and all headers and lib files that might be needed by anyone then trying to use srt.dll in any other app from one easy pack.
Now, there might be a good reason nobody did this before - but I find it incredibly useful - and if it was merged, it actually makes my life easier to test fixes to builds without risking any variances from building patches. So I offer this request, and stand ready to answer any questions!
=> Create and bundle binaries for Win32

CMakeLists.txt, common/srt_compat.h, srtcore/srt.h
There was a fix some time ago that added `srt_compat.c` to apps due to reported linker error. The reason was rather mysterious and the need of it wasn't confirmed on Mac OS X 10.12.6. This is also impossible because the symbols provided there should be already provided through the SRT library.
=> Removed srt_compat from app sources

srtcore/api.cpp, srtcore/buffer.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/srt4udt.h
This removes the previous trial implementation of preventing too early closing the socket and an extra mutex. This was experimental and blocked. The old implementation has been removed, the new one applies only closing when the send buffer is empty, updating the checks on `waitForEvent`.
=> Fixed correctly flushing send buffers on closing a socket.

CMakeLists.txt, apps/legacy/recvfile.cpp, apps/legacy/sendfile.cpp, apps/srt-file-transmit.cpp, srtcore/api.cpp, srtcore/api.h, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/common.h, srtcore/core.cpp, srtcore/core.h, srtcore/srt.h, srtcore/srt4udt.h, srtcore/srt_c_api.cpp
These changes embrace:
1. Making the `srt_send` and `srt_sendmsg` (plus `srt_sendmsg2`) do the same thing internally. What exactly implementation is going to be done, is dependent on the `SRTO_MESSAGEAPI` flag. These functions effectively differ by the parameter set.
2. The `srt_recv` and `srt_recvmsg` are provided separately only for convenience any symmetry, they do exactly the same thing.
3. The `...msg2` API uses an extended information in the `SRT_MSGCTRL` structure for a case when an extended information is needed. This may be extended in future with extra information, upon necessity, without further changes in the API.
4. Added file-only functions `srt_sendfile` and `srt_recvfile`, and example apps `sendfile` and `recvfile`. They are ports of the same apps derived from UDT and they …
=> Applied changes in the API to make it universal

common/srt_compat.h, srtcore/common.cpp, srtcore/logging.h
1. Fixed linker errors on Windows when turned on logging (made the `LogDispatcher::Proxy` class public on Windows, as the logging API is actually used by external applications).
2. Fixed crashing time formatting on Windows (The used `%T` formatting is probably nonportable; used the equivalent on Windows `%X`).
3. Used direct constructor call when returning Proxy value from a helper function. Most likely the syntax of creating and returning a local variable was widely expanded on MSVC in debug mode, so the destructor was called in wrong place and caused that an empty message was displayed in the logs. Now when using the direct constructor call syntax, the temporary object is created outside the function so the destructor is called directly in the instruction starting from `LOGC`. This was …
=> Fixed not working logging mechanism on Windows

srtcore/channel.cpp
There was a change added to error interpretation from `recvmsg` system call, but this was unfortunately added the same way for the Windows system call of `WSARecvFrom`. It uses completely different set of error codes (this should be further studied, but the Windows implementation also needs strong refactoring, so this is temporarily put aside). Just to clear the problem, the "old way" is used on windows, that is, every error reported by `WSARecvFrom` is treated as a "potential AGAIN" situation.
=> Fixed incorrectly interpreted error from WSARecvFrom on Windows

srtcore/api.cpp
This simply turns off destruction of a condition variable in `CUDTUnited::cleanup()`, which is actually executed from within the global destructor, if not called manually.
The true reason as to why this destruction causes a hangup should be further studied. Currently this is simply blocked on Windows, which isn't the proper solution, but as this is a global object, destroyed just before the program exits, it can be temporarily tolerated.
=> Workaround for a hangup during cleanup (proper fix required)

apps/srt-live-transmit.cpp, common/transmitbase.hpp, common/transmitmedia.cpp
The new feature introduced to SRT is such that the default payload size is 1316, and the live payload size may be increased up to 1456, but it must be predeclared by SRTO_PAYLOADSIZE if it's not default, and when trying to send more than the payloadsize, srt_send* functions report an error. The chunk size in stransmit could be customized by `-c` option, but the application didn't undergo necessary readjustment after introducing this rule, that is, this nondefault chunk size should be passed to SRTO_PAYLOADSIZE option.
Fixes #130
=> Fixed passing the chunk size by transmit to SRTO_PAYLOADSIZE option

.travis.yml, haicrypt/filelist.maf, haicrypt/haicrypt.h, haicrypt/hc_openssl_evp_ctr.c, haicrypt/hcrypt-openssl.h, haicrypt/hcrypt.h, haicrypt/hcrypt_ctx.h, haicrypt/hcrypt_sa.c, haicrypt/hcrypt_ut.c, srtcore/csrtcc.cpp
SRT designed to support multiple SSLs, but the implementation still have OpenSSL specific function and macros. It makes little hard to add alternative of OpenSSL. Before adding the other SSL, I created these patches to make it more portable.
=> Remove OpenSSL specific functions and definitions

CMakeLists.txt, srtcore/srt.h, srtcore/version.h.in
Fixes Linux Static SRT build with Static OpenSSL library build.
Use CMAKE_CURRENT_SOURCE_DIR instead of CMAKE_SOURCE_DIR in the CMake project to allow the project to be used as a add_subdirectory() subproject in a larger project.
Add an autogenerated version.h that is constructed automatically by the version definitions in the CMake project.
=> Some Build Fixes

apps/srt-file-transmit.cpp, common/srt_compat.h, common/transmitmedia.cpp, common/utilities.h, srtcore/buffer.cpp, srtcore/core.cpp, srtcore/crypto.cpp, srtcore/handshake.cpp, srtcore/queue.cpp, srtcore/window.h
There was quite a mistake in the design of `ref_t` solution.
It was initially designed to make the arguments for a function call, that had to be references, passed with an **explicit** marking that these are references, not values, and not just pointers. The solution initially was done with the use of a C++11 type, `std::reference_wrapper`, so that the standard `std::ref` function can be used as the aforementioned marker, however this has been later changed in the standard to be able to accept a reference in a non-explicit constructor, which completely broke the intention. Therefore a new type has been defined, `ref_t`, which in C++11 version only derives from `std::reference_wrapper`, but applies also appropriate fixes. Still, due to interoperability problems between C++03 compiled SRT …
=> Refactored the use of ref_t. Also fixes a crash.

srtcore/core.cpp
All statistical values are initialized to 0 in `CUDT::clearData` function; the m_iTraceRcvRetrans was correctly cleared after stats retrieval, but wasn't cleared initially after socket is connected.
=> Fixed initialization of m_iTraceRcvRetrans stat

apps/stransmit.cpp
These options are available in the URI with "mcttl" and "mcloop" names respectively.
=> Added handling for IP_MULTICAST_TTL and IP_MULTICAST_LOOP options.

.travis.yml, CMakeLists.txt, configure-data.tcl, haicrypt/filelist-gnutls.maf, haicrypt/hc_nettle_aes.c, haicrypt/hcrypt-gnutls.c, haicrypt/hcrypt-gnutls.h, haicrypt/hcrypt.h, srtcore/api.cpp
To replace OpenSSL, a `hc_nettle_aes` backend is added.
This backend can be selected by using `--with-gnutls` option of `configure`.
```
$ ./configure --with-gnutls
```
=> Add support nettle AES cryptographic.

CMakeLists.txt
The version 1.2.1 has been released, but `.pc` and soname still stay 1.2.0.
So I created one more bump-up version to fix the version string.
=> Bump up SRT_VERSION to 1.2.2

srtcore/core.cpp, srtcore/crypto.cpp, srtcore/crypto.h
The so far behavior with HSv5 was such that if parties declare encryption differently (which is the same with wrong password, as well as only one side declares encryption), the connection was rejected.
This fix makes the connection accepted also under this condition, and additionally the side that declares no encryption is still capable of sending the - unencrypted, obviously - data. Sending the data is also accepted, if a party declares encryption, and its peer does not or sets wrong password, just the receiver is unable to retrieve anything.
=> Restored old behavior when parties declare encryption differently.

CMakeLists.txt, common/srt_compat.h, srtcore/api.h, srtcore/channel.cpp, srtcore/platform_sys.h
This patch is to support building with `mingw-w64` on linux.
Another side effect of this patch is that manual handling of `pthread-win32` is not required while building. If `mingw-w64` is installed on linux distribution, the building sequence is same as host build except for specifying toolchain.
=> Add support cross compilation with mingw

CMakeLists.txt, configure-data.tcl
The HAVE_CROSSCOMPILER is now removed. The check can be done also when crosscompiling, as long as you set correctly the PKG_CONFIG_PATH env and CMAKE_PREFIX_PATH variables. These two things are supplied to cmake by configure, which does also autodetection of the target path basing on the compiler command path as supplied by `--cmake-*-compiler` options of `--with-compiler-prefix` (if the path isn't specified explicitly by `--with-target-path`).
With this method, OpenSSL is successfully autodetected on a Linux-ARM crosscompiler.
=> Restored dep check for all cases. Add path autodetection and prefix supplying in configure.

srtcore/api.cpp, srtcore/buffer.cpp, srtcore/channel.cpp, srtcore/common.cpp, srtcore/core.cpp, srtcore/crypto.cpp, srtcore/logging.h, srtcore/packet.cpp, srtcore/queue.cpp, srtcore/smoother.cpp
To solve #181.
Changes:
1. The call to `CheckEnabled` is taken out of the internal functions. Instead it will be called inside the macrodefinition used for logging so that the arguments that need not be used for logging won't even be evaluated.
1. The `LOGP` macro (rarely used - this is useful only for C++11, otherwise it can take only one argument) is only added the `CheckEnabled` call inside.
1. A new `LOGF` macro is added to replace cases of `LOGC(fa.disp).form(...)`. This calls the `form` method of LogDispatcher as before, but the macro is added the `if` condition, like the others.
1. The `LOGC` macro has changed the syntax. Previous syntax:
```
LOGC(fa_specifyer.SeverityDispatcher) << arg1 << arg2 << arg3;
```
New syntax:
```
LOGC(fa_specifyer.SeverityDispatcher, arg1 << arg2 << …
```
=> Improved logging API for performance

configure-data.tcl
Actually, `!$have_openssl || !$have_gnutls` will try to find OpenSSL
if `$have_gnutls` is true and `$have_openssl` is false.
=> configure-data.tcl: Fix crypto backend check condition

srtcore/udt.h
SRTS_NONEXIS define meant to be SRTS_NONEXIST
=> Fix typo in srtcore/udt.h

apps/srt-live-transmit.cpp
Prevents crash-dump when interrupted by signal (effectively by throwing an exception from deep inside SRT).
=> Put creation under execption catch.

CMakeLists.txt, scripts/haisrt.pc.in
`Lib` field is for the link flags. If they are a list of
packages, it should be in `Requires` field.
Signed-off-by: Justin Kim <justin.kim@collabora.com>
=> haisrt.pc.in: move package names to Requires field

apps/srt-live-transmit.cpp, common/transmitmedia.cpp, common/transmitmedia.hpp
The following changes are done:
1. REQUEST INTERRUPT is printed when stransmit received SIGTERM or SIGINT. In this case there's also no error message printed (except possible log message, if turned on).
2. INTERRUPT ON TIMEOUT is printed when stransmit was interrupted on timeout, which may happen due to:
* Transmission inactivity through the timeout specified in `-t` option (default 30s, -1 turns off)
* Time elapsed as specified in `-d` option (alias: `-stoptime`), in which case `-t` option is ignored.
The new option `-d` allows to exit after given time, including the final 5s clean timeout if a transmission was started. So, for example `-d:30` causes that the application exit after 30s, although if the media included SRT in listener mode:
* it's waiting for connection and if a connection …
=> Added -stoptime option. Improved exit predictability.

CMakeLists.txt, scripts/haiUtil.cmake
Otherwise cmake 3.0.2 required.
This is required because in cmake 2.8 the `$<TARGET_FILE_DIR:...>` expression is correctly resolved in the makefile, but not resolved in `cmake_install.cmake`.
It's also much better when if symlinks are supported, they are used for stransmit, as copying was a little bit overkill. Symlinks fortunately don't require any paths to be resolved, as a `file -> file` binding suffices (and this also shouldn't be a problem on Cygwin, even though the source would have the `.exe` suffix). Therefore on platforms where symlinks are supported, cmake 2.8 may work by this way.
On platforms where symlinks are not supported, cmake 3.0.2 is minimum required, as earlier versions have problems with proper resolving the expression that extracts the installation path from …
=> Changed stransmit form to symlink on platforms where supported.

apps/srt-multiplex.cpp, srtcore/api.cpp, srtcore/common.cpp, srtcore/core.cpp, srtcore/logging.h, srtcore/srt.h, srtcore/srt_c_api.cpp, srtcore/udt.h
This should speed up checking if log FA is enabled.
One of the improvements were also removed mutex-locking around checking the level and fa. The fields that are being read are considered read atomically (free of a risk of broken data consistency) because:
- level is implemented basing on 32-bit integer type internally
- FA bitset is set to be of explicit size = 32, which should make it a 32-bit integer
Note that writing to these variables is still protected by a mutex, so this solution is also free from the potential read-modify-write race conditions. The risk of reading a value that was simultaneously changed by the application thread is negligible - worst case scenario, it will apply the log filtering effectively a little bit later than the change has actually happen.
The FA symbols …
=> Changed FA selection imp to std::bitset. 

srtcore/logging.h
Fix compile error seen with gcc version 4.4.1:
```
srtcore/logging.h:184: error: a class-key must be used when declaring a friend
srtcore/logging.h:184: error: friend declaration does not name a class or function
```
=> Fix compile error seen with gcc version 4.4.1

CMakeLists.txt, common/srt_compat.h, common/win/wintime.h, scripts/haisrt.pc.in, srtcore/platform_sys.h
This PR is created to support MinGW version 4 and 5,  and VLC and GStreamer on Win32.
- `localtime_s` function is missing in MinGW 4, but MinGW 5 has the function.
- Using different implementations of pthread. 
- Fixing windows-specific header location
=> Support win32 by MinGW

common/srt_compat.c, srtcore/logging_api.h
It seems to depend on headers that are not present on these platforms
=> Fix headers for iOS & Android builds

apps/srt-live-transmit.cpp
The check for stoptime option value incorrectly checked it without checking first if the option was specified at all. In result this forced the option to be specified.
Additionally, the application was crashing when -1 was specified, which is unexpected.
=> Fixed bug in checking stoptime option

srtcore/core.cpp
This prevents calling `updateCC(TEV_INIT, ...)` after altering any of `SRTO_MAXBW`, `SRTO_INPUTBW` and `SRTO_OHEADBW` flags, when the socket isn't connected. This doesn't make sense because when the socket is not connected, then the smoother object doesn't exist yet and this will always end up with error. This error message is misleading because when the smoother object is finally created (`setupCC` called), the values from these three options will be read at this time, so the synchronization will still happen. Checking `m_bConnected` is ok because this flag is set always after successful creation of the smoother.
=> Blocked updateCC after altering MAXBW/OHEADBW/INPUTBW flags.

CMakeLists.txt, common/threadname.h, srtcore/api.cpp, srtcore/core.cpp, srtcore/queue.cpp
Fixed ThreadName constructor to restore old thread name in destructor (issue #202).
Added CMake options to map THREADHCHECK macros to application's functions.
Synched THREADCHECK and prctl thread names.
=> Threadcheck and threadname fixes

apps/stransmit.cpp
As reported in #220 - the fix was there on dev branch, backporting to master.
=> Setting reuseaddr always on UDP socket (fix backport)

CMakeLists.txt, configure-data.tcl
Fixed broken --with-target-path handling: the configure-data.tcl script did not handle it properly at all.
Changed OpenSSL detection on linux to handle broken cross-compiler pkg-config. This handles the found case of a crosscompiler, which uses /usr prefix for in openssl.pc, making this way the values for `-I` and `-L` options to be reported incorrectly.
Also, the autodetection of OpenSSL, although it works perfectly in most of the cases, doesn't behave as required when a crosscompiler-specific version should be found. Therefore, when `--use-openssl-pc` flag is set (turns into `-DUSE_OPENSSL_PC=1` for cmake), the autodetection is made always through pkg-config. And when so, additionally, if the `CMAKE_PREFIX_PATH` is set (which is done by configure-data.tcl), it is expected that the …
=> Fixed broken crosscompiler support

CMakeLists.txt, apps/srt-live-transmit.cpp, common/logsupport.cpp, common/logsupport.hpp, common/transmitmedia.cpp, configure-data.tcl, srtcore/core.cpp
Changes made:
1. The overall definition of the libraries are split into "virtual" (object-only) part and then both static and shared libraries are driven out of it.
2. By default, both static and shared library is to be built. You can use `--disable-static` or `--disable-shared` to turn off particular type.
3. All applications link against the **static** version of the library, unless it's turned off, in which case they link against the shared library.
4. The `--enable-separate-haicrypt` still works the same way, just note that in this case a shared libsrt is dependent on shared libhaicrypt and similarly for static.
There are two minor fixes that have been detected here:
A. Added lacking info about `--enable-debug=2`
B. Fixed a compiler warning that appears in some configurations.
=> Made common source shared and static libraries. 

apps/srt-file-transmit.cpp, apps/srt-live-transmit.cpp, common/transmitbase.hpp, common/transmitmedia.cpp, srtcore/core.cpp
Hi,
This patch has some cleanups of the stats prints in the "stransmit" tool. Futhermore, it adds the functionality for printing the STATS in the SENDER (and not only in the RECEIVER). Now, the STATS are more Human Readable.
The problem of incorrect/fake STAT values will be corrected in the future.
=> stransmit cleanup stats and print sender

apps/srt-live-transmit.cpp, apps/srt-multiplex.cpp, common/transmitbase.hpp, common/transmitmedia.cpp, common/transmitmedia.hpp
The proposed changes in this PR are to:
fix non-blocking API usage
fix known stransit/srt-live-transmit hard crashes, particularly on shutdown
fix exiting on signal
fix timeout option
disable blocking API usage, at least for the moment
disable exceptions handling attempting to mask crashes
disable file source/destinations except stdin/stdout
disable bandwidth monitor/guard
add non-verbose messaging to report high-level events by default
add quiet mode, default normal reporting mode
add auto-reconnect mode, on by default
add simple periodic report on received/sent/lost data
=> srt-live-transmit stability fixes and improvements

common/utilities.h
The `ref_t` no longer takes the address of the referred object by using `&` operator directly, instead it does it through `T&` -> `char&` -> `char*` -> `T*`. This walks around any definition of `T::operator&`.
=> Changed direct & to walk around user-defined operator

README.md
Homebrew support `srt` formula since 78c807ddbbad43b815a9765034176a5f6dc50b8f.
Signed-off-by: Justin Kim <justin.kim@collabora.com>
=> README.md: Add homebrew installation option for Mac

srtcore/srt_compat.c
The value to be passed as the last argument to `strncpy` is the maximum number of characters to be copied. This must include the spare size of one character for zero termination.
Also added a "fallback message" when the XSI-compliant function returns an error.
=> Fixed potential problem with non-NUL-termination of error message string.

configure-data.tcl, docs/build_iOS.md, scripts/iOS.cmake
Created toolchain file and build instructions for build SRT code for iOS per #266 
Updated configure script to prevent specifying explicit SSL path if toolchain used.
=> Added toolchain file and build instruction for iOS

srtcore/common.cpp
This is the fix for #291 - difference in base between timestamps returned by CTimer::rtdsc and CTimer::getTime caused to errors in timestamps comparison. For other platforms returned values of both functions are the same, so we decided to do similar for OS X/iOS.
=> Calculate time from ticks on Apple platforms (macOS, iOS, Apple TV)

scripts/iOS.cmake
Add debug information for lldb (Xcode debugger) if `--enable-debug` or `--cmake-build-type=Debug` options were provided.
=> Build with debug information for lldb on iOS platform

haicrypt/filelist-gnutls.maf, haicrypt/filelist.maf
It may cause runtime problems on non-windows platforms
depending on the linker.
=> Do not build the unit test in the main library

CMakeLists.txt, configure-data.tcl, srtcore/api.h, srtcore/queue.cpp
Displaying the rev-resolved hostname requires `--enable-getnameinfo` option.
=> Made SockaddrToString use only numeric string by default

CMakeLists.txt
Differences at least noticed is that srt.pc doesn't have any mention to pthreads since pthread is an implicit library at least in MSYS2 mingw-w64 GCC.
Also tested in MSVC 2017 with both shared and static compilations.
=> mingw-w64 fixes

CMakeLists.txt, srtcore/logging_api.h
So I saw that some work had been done on the dev branch. But the pthread finding code in the CMakeLists was still broken, so I ported the code I made for the other branch onto there. The big different is still to let the cmake code do its job instead of trying to second guess it on Linux. Also it seems that <sys/syslog.h> is not canonical and it doesn't exist on Android.
=> Android build for dev

apps/srt-file-transmit.cpp, apps/uriparser.cpp
- Adjust SRT file transmit application to work in non-blocking mode.
- Support caller and listener modes for either side of the transfer
- Add interrupt signal handling
=> Adjust SRT file transmit app to work in non-blocking mode

srtcore/channel.cpp
Fix code violating C++ Standards. It is possible to transfer in a block, but not in a way that bypases declarations with initizialization. The previous code was ill-formed per the standard even tho the variable is a POD type 3.9, but it is being initialized.
=> Fix C++ Standards Violation

srtcore/core.cpp, srtcore/srt_compat.h
WIN32/MINGW do not support %zu as a format macro for printf. They use %Iu . So make and use a macro in srt_compat.h to use for that purpose.
=> Use the correct printf format macros for WIN32/MINGW for size_t

CMakeLists.txt
Fix windows build when only building the static library. In which case ${TARGET_srt}_shared is not a valid target and CMake generates an error.
=> Fix windows build when only building the static library.

CMakeLists.txt
Like CYGWIN, MINGW generates libsrt.a and libsrt.dll.a when building both shared and static libraries. Actually it works correctly building lib${SRT_NAME}.a and lib${SRT_NAME}.dll.a just fine.
=> Do not use different names for the static and shared libraries in the MINGW builds

common/filelist_win32.maf, common/win/wintime.h, common/win_time.cpp, srtcore/api.cpp, srtcore/platform_sys.h
Do not expose internals unneeded by the external API. Also do not export global symbols in the SRT library with names like gettimeofday, clock_gettime, and timeradd as these are standard symbol names that may clash for the library user. This PR makes them static implementations to the library for internal use only and does not expose them to the public include and API. This also removes the wintime.h from the public API which may also, unnessarily cause clashes for the external library user.
=> Do not expose internals unneeded by the external API

CMakeLists.txt
This parameter helps in problems found in several platforms, in this case, when `-lrt` is option needed to supply functions that normally are contained in libc.
=> Added --with-extralibs build parameter

testing/srt-test-live.cpp, testing/srt-test-relay.cpp, testing/testmedia.hpp
This makes two changes that restore old behavior for two *testing* applications only: `srt-test-live` and `srt-test-relay`:
- make the default channel for `-v` option stdout (unlike `apps` applications)
- allow for setting verbose to stderr by `-v:2`
=> Added support for -v:2 for verbose to stderr and make -v stdout by default

srtcore/channel.cpp, srtcore/common.cpp, srtcore/epoll.cpp, srtcore/srt_c_api.cpp
TARGET_OS_IOS and TARGET_OS_TV are always defined as 0 or 1 in Apple SDKs
This fixes dead loop in CEPoll::wait() when running on OSX because CTimer::waitForEvent() is never called.
=> Fix TARGET_OS_IOS and TARGET_OS_TV usage

apps/srt-live-transmit.cpp, apps/transmitbase.hpp, apps/transmitmedia.cpp
This PR adds a json print format for the statistical (`-s`) output, activated by a `-pf:json` option. I've left the code fairly general to allow for other print formats to be added in the future. As I said in the issue, the existing format is not very parser-friendly. I have not touched the default print format, so there is a disparity between them regarding the amount of monitoring data from they convey.
The change is only for the `srt-live-transmit`/`stransmit` app because I do not use and thus cannot properly test the file transfer option.
=> Added -pf option with values json and default (#345)

apps/transmitmedia.cpp
The receiver mode in stransmit did not respect the json print format
request.
=> Update receiver bandwidth print to respect pf:json

srtcore/core.cpp
The following problems are solved:
- It could happen that the `CUDT::createSrtHandshake`, called from within `CUDT::updateConnStatus` when a new handshake packet comes in, did not made itself aware yet that the peer is HSv4. The recognition is added and for that case it is made sure that the handshake is crafted exclusively according to the HSv4 rules, that is:
- Version is 4
- Type is 2 (`UDT_DGRAM`), not a bit flag combination used for HSv5.
- Handling the `CONN_REJECT` case, which still is possible for various circumstances in which this function is being called
- Added a comment for prospective fix in future: the `m_ConnRes` field should be rather always filled by the incoming handshake and `m_ConnReq` by the handshake that is prepared to be send to the peer. This is currently not …
=> Fixed bug when crafting HS response after received waveahand version 4

srtcore/core.cpp, srtcore/core.h
Fixes:
- corrected handling and result specification to make handshake response provide extensions under stable conditions
- corrected specification of the REQ-RSP direction for the result of `rendezvousSwitchState`
=> Fixed internal problems in Rendezvous HSv5 FSM

srtcore/core.cpp, srtcore/crypto.cpp, srtcore/crypto.h
Changes:
1. The `CCryptoControl::decrypt` function had incorrect error handling and didn't check if the current receiver encryption status is SECURED before attempting to decrypt. This was leading to passing NULL to `HaiCrypt_Rx_Data` in case of NOSECRET state, fortunately caught inside the function, but still the decryprtion shall not be attempted if the state isn't SECURED because it will always fail regardless of the status of other data.
2. There's a field introduced in `CCryptoControl` to keep track of whether the error was already reported. The encryption failure shall be reported as Error-level log, but not with every incoming packet, only once per KM refresh period.
3. Removed no longer necessary error logging outside `CCryptoControl::decrypt` function.
=> Preventing an attempt for decryption when already failed

srtcore/api.cpp, srtcore/api.h, srtcore/core.cpp, srtcore/core.h, srtcore/handshake.cpp, srtcore/queue.cpp, srtcore/queue.h, srtcore/srt.h
Fixes:
- the rejection case in `startConnect` was catching a not possible behavior. The condition stayed, but it is turned into just an IPE error message.
- added case when the processing ended with `CONN_REJECT` and was not properly handled - this adds the exception info
- removed calls to `removeConnector` previously applied when the process gets broken due to rejection. Instead the removal is done only in case when this function is about to finish and throw exception due to any case of abnormal result.
- in `processRendezvous` the "response" packet is checked if it contains data (otherwise payload size is set to -1). There were cases when a non-received payload packet was passed to this function and was interpreted as infinite-size content causing a crash
- made the `updateConnStatus` …
=> Fixed problems in handshake handling

srtcore/core.cpp, srtcore/queue.cpp
This fixes the problem that arisen when the KMX process failed due to either no password set or bad password. The transmission should fail anyway, but the connection should be still set up correctly, and the transmission should send the packets - they shall be only unable to be decrypted. In the opposite direction the transmission should be allowed anyway. It should also show correct encryption state. This fixes the problem that in case when BADSECRET or NOSECRET situation the repeated handshake attempt was trying to extract the recorded key from previous KMREQ, which wasn't recorded due to that error, and it resulted in rejection instead of sending back the 1-word KMX failure status, if there's no key possible to be sent. The peer should receive the KMX failure, but only setup a failed …
=> Fixes for unusual rendezvous connection rejection cases

testing/testmedia.cpp
SrtModel constructor (used by file transferring apps) is effectively breaking with error when listener mode is used (instead of breaking on undefined mode vaule).
=> Fixed handling of 'mode' parameter when listener in SrtModel

srtcore/buffer.cpp, srtcore/common.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/epoll.cpp, srtcore/queue.cpp, srtcore/smoother.h, srtcore/srt.h, srtcore/udt.h
The `long long` type, although supported by most compilers, is not a part of C++98/C++03 standard, together with `LL` suffix for integer literals and the `%ll`-based formats. This PR fixes the use of them. The `uint64_t` and `int64_t` types continue to be used, but in the form defined by the compiler (e.g. some older Microsoft compilers don't support `long long` type, but they do support 64-bit type using `__int64` extension).
=> Fixing noncompliant longlong

CMakeLists.txt, scripts/haiUtil.cmake
* Now changes in MAF files are tracked and reconfigure step is done
* Minor change: removed the use of MafRead (legacy) so that the change can be done directly in MafReadDir
=> Make MAF files dependencies of CMakeLists

apps/socketoptions.hpp, srtcore/core.cpp, srtcore/core.h, srtcore/srt.h
This option influences the condition under which the SND-DROPPING happens (dropping packets already at the sender side when it would be useless as the receiver will drop them anyway due to coming too late).
This option defines an extra delay time that can be applied to check, if sending wouldn't be too late, or may even disable SND-DROPPING completely if set to `-1`. The unit is, like latency, in ms. An important treat of this option is that, in contrast to `SRTO_LATENCY` and `SRTO_TLPKTDROP`, this option may be altered also when the socket is connected, that is, the application may manipulate this option during transmission.
=> Added new option: SRTO_SNDDROPDELAY

docs/API.md, srtcore/channel.cpp
set IPv6_UNICAST_HOPS when setting SRTO_IPTTL on IPv6 socket
set IPV6_TCLASS when setting SRTO_TOS on IPv6 socket
=> Fix IP options (TTL and ToS) on IPv6 sockets

CMakeLists.txt, srtcore/api.h, srtcore/platform_sys.h
Some small fixes.
Make sure the windows headers are only installed in win/ so as to not pollute the main namespace. Actually, I wonder if all the pbulic headers shouldn't be included as srt/.. and then you don't need to include -I/usr/include/srt at all.
Also removed the use of inet_ntop() for the more portable getnameinfo() with the numeric flags which does the same thing.
And only include the MSC headers when MSC is used to build. With those, I can build SRT 1.3.1 in the VLC Windows build, so I think they're all candidates for a 1.3.2
=> Build fixes for Windows / MingW

CMakeLists.txt
It seems that pthreadGC2 is deprecated and it should prefer
winpthread. Also remove all of the commented out stuff.
The set() call seems to be superfluous with the find_library() calls. VLC had to change the "-lpthreadGC" to "-lpthread" in their build.
=> cmake: Try winpthread before pthreadGC2

srtcore/cache.cpp, srtcore/cache.h
I found a potential crash point in CCache::update.
See codes there:
```
++ m_iCurrSize;
if (m_iCurrSize >= m_iMaxSize)
{
// Cache overflow, remove oldest entry.
T* last_data = m_StorageList.back();
int last_key = last_data->getKey() % m_iHashSize;
item_list = m_vHashPtr[last_key];
for (typename ItemPtrList::iterator i = item_list.begin(); i != item_list.end(); ++ i)
{
if (*last_data == ***i)
{
item_list.erase(i);
break;
}
}
last_data->release();
delete last_data;
m_StorageList.pop_back();
-- m_iCurrSize;
}
```
`item_list` is a reference to `m_vHashPtr[key]`, so
`item_list = m_vHashPtr[last_key];`
will copy list from `m_vHashPtr[last_key]` to `m_vHashPtr[key]`, which is not we expected.
=> Fix potential crash in CCache::update

CMakeLists.txt
target_link_libraries just needs the libraries' name, not the -l or the .lib part.
pkg-config files only work with GCC syntax (with '-l' before the libs). If you are
using pkg-config for MSVC afterwards, just add the ``--msvc-syntax`` flag
to get the 'libname.lib' format back without having to break GCC compilation.
=> CMakeLists: more MinGW fixes

srtcore/channel.cpp
treating WSAECONNRESET as a fatal error for UDP socket causes IPE when e.g. trying to connect to not responding SRT peer.
=> do not treat WSAECONNRESET as a fatal error (#468)

CMakeLists.txt
- default to pkg-config method of finding OpenSSL
- fallback to find_package(OpenSSL) if pkg-config method fails
- use find_package(OpenSSL) if OPENSSL_ROOT_DIR is defined
- use pkg-config method if USE_OPENSSL_PC is defined
- only include OpenSSL in .pc definitions if pkg-config was used to find it
=> Rework OpenSSL find routine to use pkg-config method by default

srtcore/channel.cpp
Previously we set the minimum recv timeout to 1ms on Windows, but there is an undocumented minimum receive timeout of 500ms, according to some sources online[1](https://social.msdn.microsoft.com/Forums/en-US/76620f6d-22b1-4872-aaf0-833204f3f867/minimum-timeout-value-for-sorcvtimeo?forum=windowsgeneraldevelopmentissues) a result, some packets were lost for srt, but were still received by wireshark. This commit sets the socket to non-blocking via ioctl, which causes all packets to be correctly received.
=> Made WinSock non-blocking #383

CMakeLists.txt, apps/apputil.hpp
It may be missing in mingw32, but not in mingw-w64.
Fixes #474 .
=> Fix redefinition of inet_pton with mingw-w64

apps/verbose.cpp
This fixes a problem with that the expression like:
Verb() << "Processing... " << VerbNoEOL;
is not printed at all because the stream used for verbose is occasionally line-buffered. With this fix, the buffer is forcefully flushed to make sure the destructor of `Verbose::Log` forces it printed.
=> Flushing the output in case of buffered stream and no EOL requested

apps/transmitmedia.cpp
The default stdout mode on Windows is TEXT. This way the output file has extra carriage return–line feed (CR-LF) bytes, that make a TS stream file unreadable, when created with **file://con**.
`srt-live-transmit srt://:4200?mode=listener file://con > received.ts`
The solution is to set the binary mode to the stdout and stdin.
=> Set binary mode for stdin and stdout on Windows

srtcore/logging.h
Logging stream is accumulating logs and not getting flushed . So, flushing log stream so that if we can see logs even if we have only one log line while debugging.
=> Update logging.h for flushing log stream

apps/socketoptions.hpp, srtcore/api.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp, srtcore/crypto.h, srtcore/srt.h
This adds a new option `SRTO_STRICTENC`. When set to true, in case of abnormal encryption settings, the connection is rejected.
Abnormal encryption settings are when:
- only one side sets encryption
- both sides set different passwords
The non-strict encryption behavior (this flag off, the so far behavior) was that:
- the side that set no encryption could still send unencrypted payload
- the side that set encryption is allowed to send encrypted payload, just uselessly, because it can't be decrypted
The value for `SRTO_STRICTENC` is true by default. This means that the old behavior must be explicitly enforced by clearing this flag.
=> Applied changes for strict encryption

srtcore/core.cpp, srtcore/queue.cpp
Send UMSG_SHUTDOWN when caller closes the connection after reject on HS conclusion.
Without this fix the listener thinks the connection is established, and starts sending packets (in sender mode). The sending stops after the connection timeout event.
Sending UMSG_SHUTDOWN by the caller helps the lister to knows the connection was closed by the caller, and to stop the data transmission earlier.
=> Send UMSG_SHUTDOWN when caller closes the connection

srtcore/api.cpp, srtcore/core.cpp
- Conditional jump in `CUDT::sendCtrl` depends on uninitialised value of `m_bTsbPdAckWakeup`.
- Lost dynamically allocated `CUDTException`, stored in `CUDTUnited::m_TLSError`.
=> Fixed memory issues.

srtcore/channel.cpp
This fixes the high CPU load issue on Windows with non-blocking sockets (after PR #483).
Fixed type casting warnings in channel.cpp.
=> Added ::select to Windows sockets.

.travis.yml, CMakeLists.txt, docs/build_iOS.md
#475 broke the ios build. pkg-config should be disabled explicitly, because it returns host openssl libraries instead of ios ones.
I would like to set USE_OPENSSL_PC to False inside scripts/iOS.cmake, not in root CMakeLists.txt, but this will force me to set OPENSSL_ROOT_DIR also to some non empty value to override "NOT OPENSSL_ROOT_DIR" condition.
@rndi please advice how can we disable pkg-config better then direct "NOT IOS" condition
=> Fix ios build.

CMakeLists.txt
Due to security issues, described in #499, a new CMake option ENABLE_RELATIVE_LIBPATH (default OFF) is introduced. When switched on, `-rpath,.,-rpath,../${CMAKE_INSTALL_LIBDIR}` are passed to the linker on LINUX.
Additional CMakeLists adjustments in this PR:
- Added ENABLE_STATIC or ENABLE_SHARED check.
- Tabs used instead of spaces (previously they were mixed).
- If static linking is used, then rpath is ignored.
=> Relative library path as a separate option

apps/socketoptions.hpp
`SRTO_TRANSTYPE` should be set first, because it resets some other options like `SRTO_MESSAGEAPI`.
=> app: SRTO_TRANSTYPE should be set first

CMakeLists.txt, test/test_strict_encription.cpp
**TESTING SCENARIO**
Both peers exchange HandShake v5.
Listener is sender   in a non-blocking mode
Caller   is receiver in a non-blocking mode
**BONUS TESTS**
1. Test password length (length should belong to [10, 80]).
2. Check set/get SRTO_STRICTENC.
=> Added unit tests for strict encryption

CMakeLists.txt, test/filelist.maf
Calling `find_package()` to find system google tests. If not found, then fetch from GitHub.
One note is that the `find_package` seems not to properly check the version of google tests. It just shows the message about the version required.
Fixes #500
Minor things:
- Added `MafReadDir` to list the source files for unit tests
=> cmake: use system googletest if available

common/win/wintime.h
Including pthread.h is a workaround for a bug in the MinGW headers,
where pthread.h (which defines _POSIX_THREAD_SAFE_FUNCTIONS)
has to be included before time.h so that time.h defines
localtime_r correctly, wich depends in _POSIX_THREAD_SAFE_FUNCTIONS
being defined previously.
Compilation error:
[...]srt_compat.h:78:9: error: 'localtime_r' was not declared in this scope
=> Fix build with MinGW v6.0.0

srtcore/api.cpp, test/test_strict_encription.cpp
The fatal error was showing if a socket was created, but nothing was done with it due to trying to find the unitialized muxer.
Example output for one of the test cases:
```
[ RUN      ] TestStrictEncryption.SetGetDefault
F
12:41:03.855723!!FATAL!!: SRT.c: IPE: For socket %29262716 MUXER id=-1 NOT FOUND!
```
There should not be a fatal error in this case. Added a check for muser id equal to `-1` to avoid this.
*Additional changes*: extra spaces on empty lines are removed.
=> Don't search for uninitialized muxer ID on removeSocket

srtcore/api.cpp, srtcore/api.h, srtcore/channel.cpp, srtcore/common.cpp
`s_UDTUnited` is a static instance of `CUDTUnited` with dynamic initialization (calling this constructor), while `CTimer` has a static member `s_ullCPUFrequency` with dynamic initialization. The order of initialization is not guaranteed.
`gettimeofday` is now used to initialize the pseudo-random number generator.
Fixes #507 in common.cpp. Some minor code cleanup in other files, with respect to the discussion in PR #510.
Closes #515.
=> Don't use CTimer in CUDTUnited's constructor.

srtcore/api.cpp
Fixes #508. Closes #527.
The `CUDT::postConnect` behavior, which sets `s->m_pUDT->m_bConnecting` to `false` several steps before the `CUDTSocket::m_Status` is changed to `SRTS_CONNECTED` in `s_UDTUnited.connect_complete(m_SocketID);`.
This makes the `getStatus()` function to wrongfully return `SRTS_BROKEN` due to the following check.
```if ((s->m_Status == SRTS_CONNECTING) && !s->m_pUDT->m_bConnecting)```
The check is to handle the case of connection timeout. When a socket's TTL is expired, `CRendezvousQueue::updateConnStatus()` sets `m_pUDT->m_bConnecting = false;` (connection timeout). But the status of CUDTSocket remains SRTS_CONNECTING until the connection is closed.
Adding additional check for `m_bConnected` improves the handling of this state.
=> Fixed TTL status handling by getStatus() funcion

README.md
Everywhere I look the technology is described as open source. I think this is a mistake in the README.
=> Incorrect wording in README

CMakeLists.txt, test/test_strict_encription.cpp
The tests for strict encryption behavior now check both non-blocking and blocking modes.
For this case the C++11 support is now required by the testing module, so the corresponding check is added to the `CMakeLists.txt`.
One concern is that for blocking mode there are two sleeps (`50 ms`) before checking the status of the accepted socket, because in several test cases (e.g. B2-B4) the state will be changed from `SRTS_CONNECTED` to `SRTS_BROCKEN` when the listener processes the KM response from the caller.
=> Tests: strict encription tests for blocking mode

test/test_connection_timeout.cpp
Also added credits to Max Tomilov for the initial version of the test in #468.
=> [tests] Added +/-30 ms confidence interval for connection timeout check

README.md
The SRT slack channel is currently for SRT alliance members only. So this link is invalid.
Fixes #543
=> ReadMe.md: Deleted invalid SRT slack channel link.

srtcore/channel.cpp
Just a small fix. HLOGP is actually called. If ENABLE_HEAVY_LOGGING is not defined, then those calculations, that follow, are not used.
=> Replaced ENABLE_LOGGING with ENABLE_HEAVY_LOGGING

srtcore/buffer.h, test/test_connection_timeout.cpp, test/test_strict_encription.cpp
- Deleted unimplemented CRcvBuffer::isReadyToPlay(...)
- ConnectionTimeout test. Epoll wait confidence interval increased to +/-50 ms
=> Deleted unimplemented function CRcvBuffer::isReadyToPlay(...)

docs/live-streaming.md
People get often confused about the maximum payload size in SRT when trying to send RTP over SRT; this could be at least as a reference information what to be aware of in this case.
=> Added information about maximum payload size

docs/API-functions.md
This completes the API description with all required details concerning API functions.
A controversial thing here can be an inevitable statement used sometimes that there are still bugs or design flaws in the area of error types returned; it would be desired that these bugs are fixed ASAP, but if they are not, and not mentioned here, they might be quickly forgotten.
=> Created a detailed documentation for SRT API functions 

srtcore/core.cpp
`m_ullTraceRcvBytesLoss` was never cleaned in stats.
=> [core] Fixed m_ullTraceRcvBytesLoss clearing

apps/logsupport.cpp, apps/logsupport.hpp, apps/srt-file-transmit.cpp, apps/srt-live-transmit.cpp, apps/srt-multiplex.cpp, srtcore/api.cpp, srtcore/buffer.cpp, srtcore/channel.cpp, srtcore/common.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp, srtcore/crypto.h, srtcore/logging.h, srtcore/logging_api.h, srtcore/packet.cpp, srtcore/queue.cpp, srtcore/smoother.cpp, srtcore/srt_c_api.cpp, srtcore/udt.h, testing/srt-test-file.cpp, testing/srt-test-live.cpp, testing/srt-test-relay.cpp
This fix provides the following changes:
1. All log-related global objects are put into `logging` namespace. This should keep away any name conflicts with other libraries. This exactly case was believed to cause problems when added to ffmpeg linked to OBS Studio.
2. The `blog` logger is commented out (it was the one caught with suspected name conflict). This isn't in use, but it was commented out just so that the existing FA can be reused for something else in future.
3. The use of `std::string` was removed from the initialization of the global objects. Although it wasn't causing problems with building OBS Studio, as it was initially suspected, keeping the solution using only C standard library keeps it safe against any future problems concerning the order of initialization.
=> Putting global objects with short names under a namespace

apps/transmitmedia.cpp, testing/testmedia.cpp
- `srt_bstats(...)` is calls only when needed
- Extra socket options setup calls
- cout was used instead of `*Verbose::cverb`
=> [apps] Minor fixes of the sample applications.

docs/Android/Compiling.md, docs/Android/mkall, docs/Android/mksrt, docs/Android/mkssl, docs/Android/mktoolchains, docs/Android/packjni, docs/Android/prepare_build
Update for Android NDK, Revision r19 (January 2019). Standalone toolchains are now unnecessary.
=> Android build scripts for NDK r19

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/common.h, srtcore/queue.cpp, srtcore/queue.h
CRcvBuffer and CRcvQueue were accessing and modifying state of the CUnitQueue directly (friend classes). Now they do it via public functions.
=> [core] CUnitQueue access via functions.

srtcore/srt.h, srtcore/srt_c_api.cpp
- Replaced TABs with 3 spaces (like the rest of the header file).
- Functions are `extern` by default - deleted extern keywords.
- `srt_connect_debug(...)` function had slightly different prototype in srt.h, than its implementation in `srt_c_api.c`.
=> Formatting srt.h. Extern keyword deleted (default).

apps/socketoptions.hpp, apps/transmitmedia.cpp
`extract()` can fail, but `apply()` will still try to apply the option, causing a program to crash.
=> [apps] Handle invalid options values properly.

apps/srt-live-transmit.cpp
The fix makes it possible to receive the connection event on the client (caller) socket. The following conditions have to be met:
- The epoll should have `SRT_EPOLL_OUT` flag set.
- When you call `srt_epoll_wait(...)`, the `writefds` argument has to be passed.
Fixes #410
=> [apps] Receive the connection event on the client (caller) socket

apps/srt-live-transmit.cpp
Add an option (`-taoc`, `-timeout-abort-on-connect`) to cancel the timeout (as set with `-t`) after a client is accepted. This allows for `srt-live-transmit` to run in listener mode and wait for a limited amount of time (timeout) for a client to connect.
Due to the paired tx/rx operation of `srt-live-transmit` and the fact that a sender process may not accept multiple clients, should one want to operate such a server they would need to devise a way to spawn sender processes as necessary. In such a case sender processes spawned in listener mode wait for the client to connect; it then becomes important to enforce a timeout so the sender process does not wait forever. You already have the `timeout` option for `srt-live-transmit`, but that works as an unconditional exit timer. This patch …
=> srt-live-transmit: add option to cancel timeout

CMakeLists.txt, examples/make-test-c.sh, examples/recvfile.cpp, examples/sendfile.cpp, examples/test-c-client.c, examples/test-c-server.c, examples/testcapi-connect.c
This it's an upgrade from original PR #21 
Take into account that the file `examples/make-test-c.sh` assumes the structure of `examples/include/` and `examples/lib/` described in #265.
Regards.
=> C examples update

srtcore/channel.cpp, srtcore/core.cpp
This fixes OSX Builds for SDK pre 10.8 which does not support C++11 and some IPV6 features. Tested with my application using OpenSRT on iBookG4 on OSX-10.5 and PowerBook on OSX-10.7. Works with and without encryption.
=> Fix OSX Builds SDK pre 10.8.

apps/srt-live-transmit.cpp
After PR #597. Sender-listener. `tar->GetSRTSocket()` returns bind socket at the start, but then the accepted socket when connection happens. While the bind socket is still in the srtrwfds list of polled sockets.
=> Fixed epoll connection issue.

srtcore/core.cpp
`CTimer::triggerEvent()` should be called after `m_EPoll.update_events(...)` to notify epoll about the change of state. Otherwise it will continue waiting until the periodic trigger event.
=> Notify epoll the data is available to be read

apps/transmitmedia.cpp, srtcore/core.cpp, srtcore/core.h
Statistics, which is obtained through `srt_bstats()`, has no thread lock. The implication was that `srt_bstats()` locks the receiving thread, thereby achieving the sustainability of the data. But the sending stream is not blocked during a call to `srt_bstats()`. Therefore, in some situations, statistics for sent packets, bytes, etc. may not be reset. A reset occurs in `srt_bstats()`, if at this time another thread increases the value of the variables, then a reset will not succeed.
- [core] Added core statistics access mutex 
- [apps] Fixed stats clearing condition
- [core] Renamed internal stats variables
=> Added statistics mutex to sync read/write

test/test_strict_encription.cpp
Wrong condition was making the check of the accepted socket to be skipped in the non-blocking mode.
=> [tests] Fixed strict encryption check for accept in non-blocking mode

CMakeLists.txt
Fix such an error:
```
PKG_CONFIG_PATH="/tmp/ffmpeg-static/lib/pkgconfig" ./configure --prefix="/tmp/ffmpeg-static/target" --disable-shared
NOTE: --disable-shared changed into --enable-shared=0
Running: cmake . -DCMAKE_INSTALL_PREFIX=/tmp/ffmpeg-static/target -DENABLE_SHARED=0
[...]
make
[...]
[ 95%] Linking CXX executable srt-live-transmit
/tmp/ffmpeg-static/target/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/tmp/ffmpeg-static/target/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x344): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x402): undefined reference …
```
=> Fix static linking error for apps

haicrypt/hcrypt_tx.c
```
int pad_factor = (HCRYPT_CTX_MODE_AESECB == crypto->ctx->mode ? 128/8 : 1);
ASSERT(NULL != crypto);
```
In the code above, if `crypto` is NULL, ASSERT isn't helpful to guard null pointer access.
=> Move ASSERT to guard possibly null pointer access

apps/srt-live-transmit.cpp, srtcore/api.cpp, srtcore/common.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/packet.cpp, srtcore/queue.cpp
The crash observed during closing the program with non-blocking and working linger was due to collision of the global object destruction.
This fix provides fair call of srt_cleanup() at the end, as it should be, and some smaller fixes to avoid possible collisions around global variables in the future.
=> Fixed crash found with non-blocking linger in srt-live-transmit

srtcore/core.cpp
`m_stats.startTime` is given a value only when a socket is being opened. Therefore no need to lock access to it from other threads.
Maybe `CUDT::clearData()` should not lock `m_StatsLock` mutex at all, as being called on opening new connection?
Fixes #630
=> [core] Not locking m_stats.startTime

apps/srt-live-transmit.cpp, docs/API.md, srtcore/api.cpp, srtcore/channel.cpp, srtcore/channel.h, srtcore/core.cpp, srtcore/core.h, srtcore/queue.h, srtcore/srt.h
Add SRTO_IPV6ONLY to SRT_SOCKOPT for setting the IPV6_V6ONLY sockoption before the ::bind call
Also delete a "performance warning" in Visual Studio (srt.h)
=> Add SRTO_IPV6ONLY option

apps/srt-file-transmit.cpp, apps/srt-live-transmit.cpp, apps/srt-multiplex.cpp, apps/transmitbase.hpp, apps/transmitmedia.cpp, apps/transmitmedia.hpp
Fixed `srt-file-transmit` issue, introduced by #598.
`Source::Read(…)` now returns int and does not throw exceptions.
Fixes #645
=> [apps] Fixed srt-file-transit (issue #645)

CMakeLists.txt
When `CMAKE_BUILD_TYPE=Debug` is specified, the `ENABLE_DEBUG` will be set to `ON` (line 48).
Leading to `set (CMAKE_BUILD_TYPE "Release")` because `ON != 1`:
```
if (ENABLE_DEBUG EQUAL 1)
set (CMAKE_BUILD_TYPE "Debug")
elseif (ENABLE_DEBUG EQUAL 2)
set (CMAKE_BUILD_TYPE "RelWithDebInfo")
else()
set (CMAKE_BUILD_TYPE "Release")
endif()
```
After the fix the condition is:
```
if (ENABLE_DEBUG EQUAL 2)
set (CMAKE_BUILD_TYPE "RelWithDebInfo")
elseif (ENABLE_DEBUG) # 1, ON, YES, TRUE, Y, or any other non-zero number
set (CMAKE_BUILD_TYPE "Debug")
else()
set (CMAKE_BUILD_TYPE "Release")
endif()
```
=> [build] Fixed CMAKE_BUILD_TYPE=Debug processing

srtcore/core.cpp, srtcore/utilities.h
Fixes #634.
The protocol definitions stays as before (that is, characters in StreamID and Smoother are fourwise inverted). There's a fix made especially for big endian machines, which turns them to the "little endian convention" for the sake of transport.
=> Fixed StreamID and Smoother name swapping for big endian machines

srtcore/api.cpp, srtcore/queue.h
Fixes #652.
The problem was that the socket was closed while the queues might be using it, so the system operation on the socket simply returned an error, and the queues reported it as a fatal error, unaware that this is because they are going to be closed in a while.
The fix sets both queues m_bClosing flag before closing the socket so that they treat this error as expected.
=> Silencing the queues before closing the UDP socket

srtcore/core.cpp, srtcore/core.h
When trying to re-transmit a packet from the `m_pSndLossList` (a packet considered or reported lost), but later on was yet acknowledged, the sending function `packData()` returns and does not reschedule the sending queue for next operation. Instead it goes into waiting for some event that is expected to change the sending buffer state (e.g. ACK).
Instead the processing in `packData()` should go further through the list of reported lost packets or end up sending a new packet from the buffer.
This PR adds the `CUDT::packLostData()` function that iterates through packets in the loss list and tries to construct an SRT packet. On success the payload size is returned. If it fails to construct a retransmission packet, then 0 is returned, it the parent function `packData()` tries to prepare a new …
=> [core] Fixed packet retransmission

srtcore/channel.cpp, srtcore/core.cpp
Set IPv4 TOS and TTL when setting IPv6 TCLASS and HOPS to set accepted IPv4 socket of IPv4mapped-IPv6 addresses. Also fixed some compiler warnings.
An IPv4 accepted socket of an IPv6 listening socket (IPV6_V6ONLY=0) will not have TTL and TOS set  if only the IPv6 socket is set. This fix has been tested with the v1.3.1 code, this commit seems to enable IPV6_V6ONLY by default. (incoming IPv4 call never connect to the IPv6 listener).
=> Set IPv4 TOS and TTL for accepted IPv4 socket of IPv4mapped-IPv6

apps/apputil.hpp
When space character is used as a separator, empty `""` value is added to the list of values.
=> [apps] Fixing space char handling in ProcessOptions

test/test_epoll.cpp
Added a unit test to check if listener is notified on the caller closing the connection via epoll.
A caller connects to a listener on a localhost. A listener accepts the connection and ads the accepted socket to epoll.
Then the caller closes the connection, and listener is expected to be notified about connection break via polling the accepted socket.
=> [tests] Added epoll NotifyConnectionBreak test

apps/srt-multiplex.cpp
Fixed unused variable in srt-multiplex, partially fixing the read result check.
=> [apps] Fixed unused variable

apps/transmitmedia.cpp
Due to differing function prototypes GetSysSocket() was not being overridden properly.  This causes problems in the poll loop in srt-live-transmit
Signed-off-by: Patrick Felt <patrick.felt@sling.com>
=> - GetSysSocket() was not being properly overridden

apps/srt-live-transmit.cpp, docs/live-streaming.md, examples/suflip.cpp, scripts/srt-ffplay, srt-ffplay, testing/srt-test-live.cpp
Seems like at some point `stransmit` got renamed to `srt-live-transmit`. I noticed this when trying to use the `srt-ffplay` script. This PR renames the few remaining references to `stransmit`. Hopefully this is helpful.
=> Remove legacy references to stransmit

apps/socketoptions.hpp, docs/API.md, srtcore/core.cpp, srtcore/core.h, srtcore/srt.h
New option: `SRTO_RSPTIMEO` allows to configure "response time", that is, the longest tolerable time during which agent receives no packets from peer. Upon passing of this time the connection is considered broken.
=> Add option for configuring connection response timeout

test/test_epoll.cpp
Transition of a socket state after it is closed by peer is the following: `BROKEN` -> `CLOSING` -> `CLOSED` -> `NONEXIST`. And finally a socket is removed from the list and becomes `NONEXIST`. Status of the socket depends on the time, when it is requested. We can assume, that current test can have `BROKEN`, `CLOSING` or `CLOSED` socket state, because the state is expected to be asked almost immidiatelly after a peer has closed the connection.
=> [tests] Improved epoll connection break test

apps/socketoptions.cpp, apps/socketoptions.hpp
In `socketoptions.hpp` the `linger` option is commented, because this list is for general loop over the options. And we can't do a general loop, because linger is a struct, not an integer, therefore requires special handling. But still added to the structure to show to the user that this option will be handled.
=> [apps] Added linger URI socket option

haicrypt/haicrypt_log.cpp
The action to rename `logging` namespace to `srt_logging` skipped parts that were conditionally compiled with `--enable-haicrypt-logging` build option. This fixes it.
=> Fixed after renaming logging to srt_logging

docs/API.md
=> Added description of 4 lacking options

srtcore/core.cpp
SRT is a great piece of software and we've had a really good time working with it. However, occasionally it was freezing for us and we decided to dig a little bit.
When closing an SRT socket with `srt_close`,`CUDT::releaseSynch()` is eventually called, and it calls pthread_join for the TspPd thread. If the connection happens to be broken/dead, `CUDT::releaseSynch()` may also be called from a different thread (from `CUDT::checkTimers()`).
Now, according to pthread_join's manpage: _If multiple threads simultaneously try to join with the same thread, the results are undefined_.
What we've experienced in practice is that one of the threads calling `pthread_join` is released after the thread completes, but the other is blocked forever. After this happens, usually other SRT's threads get …
=> Synchronize pthread_join on TspPd

srtcore/core.cpp
`CUDT::open` sets initial values for timers. However the connection itself is established later. Need to update the timers.
For example, wrong value of `m_ullLastRspTime_tk` influences the LATEREXMIT functionality at the start (before PR #741). With FileCC this stops the slow start period too early and triggers exsessive packet retransmission.
```
17:02:01.904791: CUDT::open
17:02:03.200710: Connection established
17:02:03.310795: ENFORCED LATEREXMIT by ACK-TMOUT (scheduling): 6985342-6985356 (15 packets)
17:02:03.310809: FileCC: CHKTIMER, SLOWSTART:OFF, sndperiod=62500us AS mega/rate (rate=16)
```
=> [core] Update timers on connection established.

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp
Possible crash (division by 0) in section measuring input bitrate.
crash observed on long term tests.
=> Fix possible FPE (Zero Divide)

CMakeLists.txt, haicrypt/cryspr-gnutls.c, haicrypt/cryspr-gnutls.h, haicrypt/cryspr-openssl.c, haicrypt/cryspr-openssl.h, haicrypt/cryspr.c, haicrypt/cryspr.h, haicrypt/filelist-gnutls.maf, haicrypt/filelist.maf, haicrypt/haicrypt.h, haicrypt/hcrypt.c, haicrypt/hcrypt.h, haicrypt/hcrypt_ctx.h, haicrypt/hcrypt_ctx_rx.c, haicrypt/hcrypt_ctx_tx.c, haicrypt/hcrypt_rx.c, haicrypt/hcrypt_sa.c, haicrypt/hcrypt_tx.c, srtcore/crypto.cpp
Preparatory work to use mbedTLS instead of OpenSSL or GnuTLS.
Cryspr/4SRT is to HaiCrypt what crispr/cas9 is to DNA.
Documentation will follow.
=> CRYSPR/4SRT: CRYpto Service PRovider for SRT

apps/uriparser.cpp, apps/uriparser.hpp
* Make property accessors const.
* Proto is converted to lower case. The current code assumes a lowercase
proto and will fail if the input is not lowercase.
* Type now supports all existing types.
* Type RTP added.
* Test code no longer crashes when called with no args.
* Fixed layout removing extraneous empty lines.
=> UriParser improvements

srtcore/utilities.h
Allows usage of `noexcept`, `constexpr`, `override` and `final` starting from Visual Studio 2015 [14.0].
[List of MSC_FULL_VER](https://dev.to/yumetodo/list-of-mscver-and-mscfullver-8nd)
=> [core] MSC C++11 attributes support.

srtcore/core.cpp, srtcore/core.h
As reported by a user, there is an issue in the file mode. When transfering a big file via SRT file mode, the connection may be idle forever before all data have been transferred.
In the method `CUDT::checkTimers()`, for the file mode, the loss packets retransmission will be delayed by the time calculated by the following:
`exp_int_tk = (m_iEXPCount * (m_iRTT + 4 * m_iRTTVar) + COMM_SYN_INTERVAL_US) * m_ullCPUFrequency;`
The loss packets will be retransmitted at the time:
`next_exp_time_tk = m_ullLastRspTime_tk + exp_int_tk;`
This time will never be reached if `exp_int_tk > (COMM_KEEPALIVE_PERIOD_US  * m_ullCPUFrequency)`. Because `m_ullLastRspTime_tk` may be updated by keepalive packets every `COMM_KEEPALIVE_PERIOD_US` microseconds.
Further investigation showed, LATEREXMIT packet …
=> LATEREXMIT now uses LastACK timer, instead of connection expiration timer

apps/srt-file-transmit.cpp, apps/srt-live-transmit.cpp, apps/transmitbase.hpp, apps/transmitmedia.cpp
I'm building an application similar to srt-live-writer and ran into a couple of issues with implementing custom  stats output. This PR attempts to make custom application stats logging possible without making major changes to the code.
With this PR consumers of the library can implement the `SrtStatsWriter` interface to create their own custom stats output and set `stats_writer` so get custom stats output. Because both the live and file transmit applications use this I've replaced the existing code with `SrtStatsWriterFactory` to configure the existing apps. Other applications can replace the factory with their own code to set `stats_writer`.
I can think of other approaches to solving this problem. I largely picked this one because it results in fairly minimal code changes.
=> Refactor stats config to allow applications to write custom stats

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/congctl.cpp, srtcore/core.cpp, srtcore/core.h
Fixing bandwidth limitation mode with automatic input bitrate R<sub>input</sub> calculation. Configuration `SRTO_MAXBW=0`, `SRTO_INPUTBW=0`, live transmission mode.
In this mode the bandwidth limit is R<sub>input</sub> * (1 + OHEAD), with R<sub>input</sub> calculated based on the number of packets added to the sender's buffer (via srt_send*).
The desired behavior of the input rate calculation:
1. **Fast start** period of **0.5 sec** or 2000 packets to accumulate enough statistics. Meanwhile use default MAXBW + overhead.
2. If 0.5 seconds have passed or 2000 packets have been sent, calculate input rate R<sub>input</sub>. Update MAXBW = R<sub>input</sub> * (1 + OHEAD). Switch to RUNNING mode with input rate update every 1 sec.
3. In RUNNING mode update R<sub>input</sub> every second and …
=> [core] Improved input rate calculation.

srtcore/common.h, srtcore/congctl.cpp, srtcore/core.cpp
Related to issue #552. 
The limitation still exists, but it is increased to make more sense for the regular user.
Previous value was 30 Mbps.
=> [core] MAXBW infinite value updated to 1 Gbps.

README.md
- Added license badge.
- Travis badge shows Linux and macOS label.
- AppVeyor's badge shows Windows label.
- Added latest release badge.
Screenshot:
=> Updated status badges in README

srtcore/core.cpp
`CTimer::getTime()` is used for a packet timestamp, except for this one place. This PR fixes it.
=> [core] Fixed HS response timestamp

.travis.yml
Travis CI for MinGW fails for current master, probably after [this commit](https://github.com/openssl/openssl/commit/e32bc855a81a2d48d215c506bdeb4f598045f7e9) in OpenSSL 1.1.0.
Updated OpenSSL to 1.1.1.
=> [build] Travis MinGW: updated OpenSSL to 1.1.1

haicrypt/cryspr.c
Leftover when CRYSPR was introduced. GnuTLS build tested on a system with openssl installed.
Developers building SRT 1.3.3 with GnuTLS or mbedTLS may encounter issue#778.
Fixes #778
=> Fix issue#778: removed unnecessary openssl include in a cryspr

haicrypt/cryspr-gnutls.h, haicrypt/cryspr.c
To suppress compilation warnings
=> Add headers to let compiler know functions and structures.

.travis.yml
To avoid re-compiling homebrew dependencies.
=> travis: bump up osx_image version to 10.2

srtcore/README.md, srtcore/api.cpp, srtcore/buffer.cpp, srtcore/handshake.cpp, testing/testmedia.cpp
Fixed a few warnings
* Avoid copying exception, rethrow instead.
* Excluded variable, not used in case HEAVY logging is off.
* `srt-test-live` fixed handling of medium.
=> Fixed a few warnings

CMakeLists.txt
Mattew created this patch for cerbero(GStreamer build aggregator), and it is ported to srt 1.3.3.
Refer to
https://gitlab.freedesktop.org/gstreamer/cerbero/commit/8ca02e6fe8bb151496dd6eb9961692c39894ec82
=> CMakeLists.txt: Allow building using gnustl

srtcore/api.cpp
Channel is used by recv and send queues and possible blocked in I/O
operations.  Closing the channel while it is still in use causes
problems with the recv and send queues and may cause problems in other
threads of the application.
Fixes #306.
=> close Channel after stopping recv send queues

ATTIC/srt-multiplex.cpp, apps/transmitmedia.cpp, examples/suflip.cpp, testing/srt-test-multiplex.cpp, testing/testmedia.cpp
Hi,
SRT is preventing the usage of system reserved/priviledged ports, following IANA standards. There is an error in the implementation of the standard, preventing the usage of port 1024 that should not be reserved.
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
```
System Ports (0-1023),
User Ports (1024-49151),
and the Dynamic and/or Private Ports (49152-65535)
```
This PR is here to allow the usage of port 1024.
Hope it helps,
=> Fix system priviledged port range, excluding port 1024 that is not reserved

srtcore/common.cpp
The sleeping time for the SRT sending queue is 10 ms, and it is discrete.
That means, if a thread wants to sleep for 5 ms, it will sleep for 10 ms.
If a thread wants to sleep for 15 ms, it will sleep for 10 ms, and then again for another 10 ms, that will make a total sleep time of 20 ms.
This behavior is incorrect and unnecessary.
Fixes #673.
**Accuracy of the new sleepto()**
**Accuracy on Windows**
**Live mode sending accuracy**
**File mode sending accuracy**
In pseudocode, the `sleepto` function works like this:
```
CTimer::sleepto(nexttime) {
m_ullSchedTime = nexttime;
rdtsc(now);
while (now < m_ullSchedTime) {
condTimedWaitUS(&m_TickCond, &m_TickLock, (m_ullSchedTime- now));
rdtsc(now);
}
}
```
`CTimer::sleepto(nexttime)` waits on a CV `m_TickCond`. 
The function `CTimer::tick()` …
=> Improving sending queue sleepto() accuracy

srtcore/core.cpp, srtcore/core.h
When accepting an incomming connection, the copy constructor was not copying the `m_iMaxReorderTolerance` setting from the ancestor.
TODO:
Fixes #735.
=> [core] Fixed SRTO_LOSSMAXTTL setting on accepted socket. Fixes #735.

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/utilities.h
Fixes #776.
In `CRcvBuffer::getRcvReadyMsg`, the number of removed packets/bytes is counted inside the loop. After the loop, the countBytes() is called. But the function might return inside the loo, thus not calling `countBytes()`.
Fixes partially #836 issue 1
`countBytes()` is called for the part of the packet actually read, not the real size. Furthermore, if there is no more space in the buffer, the reading will continue, but a call to countBytes() will be skipped.
and TSBPD log messages from TODO list.
=> Fix CRcvBuffer::countbytes()

srtcore/congctl.cpp, srtcore/core.cpp, srtcore/core.h
Improving FileCC. Mainly bearing with losses below 2%. Also reduced reaction on losses.
Experiments have shown that the bandwidth estimation value `BW = m_parent->bandwidth()` is not reliable enough. However, it was used to determine the highest possible sending bitrate in FileCC.
The value `B` determines the difference between the estimated bandwidth `BW`, and current sending rate `R=1000000/m_dPktSndPeriod` (packets per second):
B = BW - R (pkts/s)
The new sending rate will be increased exponentially the higher the value of `B` is.
In case BW is overestimated, the increase wll be too rapid and will instantly fall into network congestion.
Therefore, in this PR the last point where the loss was detected is used. The value of that is multiplied by two so that the increased value hits the …
=> [core] FileCC improvements

README.md
Just a little badge showing the version currently in Debian Testing. It links to the package in the archive.
=> Add badge linking to the Debian Testing package

CMakeLists.txt
`-std=c++11` flag is added to `CFLAGS_CXX_STANDARD` regardless of the `ENABLE_CXX11` option.
So the flag may be set even if `ENABLE_CXX11=OFF`.
=> [build] Fixed -std=c++11 flag usage with HAVE_COMPILER_GNU_COMPAT

configure-data.tcl, docs/API-functions.md, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/channel.cpp, srtcore/common.h, srtcore/congctl.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/packet.cpp, srtcore/packet.h, srtcore/queue.cpp, srtcore/utilities.h, test/test_connection_timeout.cpp, testing/utility-test.cpp
List of fixes:
=======
* Added official (lacking) option `--enable-unittests` to `configure-data.tcl`
* Formatting fixes and new log entries
* Added testing entry in `channel.cpp` to allow configure a fake packet loss
* Extra comments
* Better use of conditional `IF_HEAVY_LOGGING` for evaluations used for heavy logging only
* Fix: added error handling for `setupCC` that results in rejection
* Refax: packet content reporting function for logs
* Log support improvement: pairs and containers displayed with `Printable`
* New `BufferStamp` functions that allows putting a short string in the log that can report contents of a larger payload
* Minor new utilities
=> {FEC} Random refactoring and small bugfixes during FEC works.

srtcore/utilities.h
Fix build Linux GLIBC-2.8 and earlier. Tested on CentOS5 and GLIBC-2.5. Tested on both 32 and 64 bit.
=> Fix build Linux GLIBC-2.8 and earlier.

docs/API-functions.md, docs/API.md, srtcore/srt.h
Fixes #661 
There was a mistaken description of msgttl suggesting that the message will be waiting in the sender buffer for a chance to be sent and discarded completely after TTL passes. It was a wrong statement suggesting that the message may be not sent at all even once, which isn't true - the message is always sent at least once. The TTL value is considered only in the function that is used for retransmission.
=> Fixed correct description for msgttl

CMakeLists.txt, configure-data.tcl
When built with `ENABLE_CODE_COVERAGE=ON`, code coverage report for tests can be collected.
```
cmake -DENABLE_CODE_COVERAGE=ON -DENABLE_UNITTESTS=ON -DCMAKE_BUILD_TYPE=Debug ./
cmake --build . --config Debug -- -j $(nproc)
```
=> [build] Added code coverage option to CMake

docs/handshake.md
Closes #479 
Changed the previous "Smoother" name. Updated reference to Access Control in handshake.md.
=> Updated doc with proper description

CMakeLists.txt, haicrypt/cryspr-openssl.c, haicrypt/cryspr.c, haicrypt/cryspr.h, test/filelist.maf, test/test_cryspr.cpp
Fixed returned values of fallback kmwrap and kmunwrap methods
Made cryspr.h header C++ compatible (for unittest prog)
=> Unittest for cryspr methods

apps/srt-live-transmit.cpp, apps/transmitbase.hpp, srtcore/channel.cpp, srtcore/common.h, srtcore/congctl.cpp, srtcore/congctl.h, srtcore/core.cpp, srtcore/core.h, srtcore/fec.h, srtcore/packet.h, test/test_epoll.cpp, test/test_strict_encription.cpp
- m_ullACKInt_tk used at initialization
- Removed unused `m_iACKPeriod` from FileCC
- ACK event variant type changed to signed integer
- `SrtCongestionControlBase`: renamed `ACKInterval()` -> `ACKMaxPackets()`
- `SrtCongestionControlBase`: renamed `ACKPeriod()` -> `ACKTimeout_us()`
- Added `ATR_OVERRIDE` to `FECFilterBuiltin::arqLevel()`
Fixes #253 - no warnings during build in Travis.
=> [core] Minor ACK variables clean up.

CMakeLists.txt, test/filelist.maf, test/test_enforced_encryption.cpp
=> Rename unit tests

srtcore/congctl.cpp
Fixes #887 
`pktsInFlight` could be 0, and when so, the division by this without checking led to crash
=> Prevented 0 pktsInFlight to be used in calculation for loss percentage

srtcore/api.cpp, srtcore/buffer.cpp, srtcore/core.cpp, srtcore/core.h
Changes by this PR:
* **Fix: catch an exception by reference**
* Minor refactoring of `CRcvBuffer::getRcvDataSize()`
* Renamed `CUDT::unlose(from, to)` to `CUDT::dropFromLossLists(from, to)`
=> Minor refactoring and CUDT::unlose renaming

srtcore/buffer.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/packet.cpp, srtcore/packet.h
When the lite ACK is received, the sender's loss list is better to be updated as well to prevent retransmission of already acknowledged DATA packets.
Therefore, created the `CUDT::updateSndLossListOnACK()` function to handle this in one place.
Protected by `CUDT::m_RecvAckLock` mutex.
In short, [this epoll update](https://github.com/Haivision/srt/blob/master/srtcore/core.cpp#L6984) call does not really check the state of the sender's buffer.
It is expected that [`m_pSndBuffer->ackData(offset)`](https://github.com/Haivision/srt/blob/master/srtcore/core.cpp#L6908) removes some packets from the buffer, thus providing free space to add more packets.
However, after that `ackData()` in the receiving thread, the sender's buffer can be filled with all the remaining packets from …
=> [core] Update SND loss list on lite ACK

apps/transmitmedia.cpp, srtcore/api.cpp, srtcore/api.h, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/queue.cpp, srtcore/queue.h
* [core] Refactored `CSndQueue::worker(...)`. Deleted unused `m_ExitCond` from `CSndQueue` and `CRcvQueue`
* [core] Refactored `CRcvBuffer::isRcvDataReady(...)`
* [core] Renamed timestamp to timestamp_us in `CRcvBuffer::getTsbPdTimeBase(uint32_t timestamp_us)`
* [core] Renamed `CUDTSocket::m_TimeStamp` to `m_ClosureTimeStamp`
* [apps] Merged collapsible "if" statements 
* [core] Applied clang-format on "srtcore/queue.cpp"
* [core] Applied clang-format on "srtcore/core.cpp"
=> Refactoring of CSndQueue::worker(...), CRcvBuffer::isRcvDataReady(...), etc.

srtcore/fec.cpp
I met some crash when playing with this library.
FEC filter may access item out of range in rcv.cells.
FEC filter may access item out of range in rcv.rowq.
=> [core] Fix crash case in FEC filter

srtcore/queue.cpp
There are two triggers to check timers on a receiving socket.
The first one is to check timers on every packet received. It is done in `CRcvQueue::worker_ProcessAddressedPacket(…)`.
The second place to check the timers is by a timeout in `CRcvQueue::worker(…)`.
The condition was to check the timers if the time of the last check for that socket was at least 100 ms in the past.
However, the timer needs to be checked every 10 ms, in accordance to the communication synchronization interval.
Having a 100 ms check does not impact live transmission mode, because the receiver has a constant stream of incoming packets, that trigger timers check.
On the contrary, in file mode the sender first sends 16 packets and waits for an ACK packet from the receiver. And the waiting time might be 100 ms, that …
=> [core] Fixed checkTimers interval (100ms -> 10 ms)

docs/API-functions.md, srtcore/epoll.cpp, srtcore/epoll.h
`CEPollDesc::m_iID` was not initialized in the constructor.
In the code it was initialized right away, after the object is created.
=> CEPollDesc::m_iID is now initialized in the constructor

srtcore/api.cpp
I met a problem that the srt_socket will drop into deadlock in srt_close if the remote server close the connection yesterday.
During debugging I found it's because cmake is misconfigured and the NMakefile generated not contains /EHsc option for MSVC, thus lockguard wasn't destructed when exception thrown.
Since SRT not work in an environment without unwind, I suggest treat C4530 as error in MSVC, preventing people from the same mistake.
=> [core] prevent compile if stack unwinding when exception handling is off in MSVC

srtcore/api.cpp, srtcore/utilities.h
This is the first portion. More problems are reported on `dev-pktinfo` branch. This at least solves some warnings as reported by gcc 8. Note that this compiler compiles in C++14 mode by default.
=> Fixed some problems reported by gcc 8

docs/API.md, srtcore/core.cpp, test/filelist.maf, test/test_socket_options.cpp
- Fixed `srt_getopt(...)`: `optlen` is not set in some cases.
- Added `SRTO_LOSSMAXTTL` to `srt_getopt()`
- Added a test case for `SRTO_LOSSMAXTTL`. Checks issue #735.
=> Add GET for SRTO_LOSSMAXTTL

srtcore/common.cpp, srtcore/common.h
Use high accuracy busy waiting to wait only the remaining 1 ms (10 ms on Windows) of the waiting time.
Reduces idle CPU from around 20% to almost zero on Windows machines at low bitrates.
The solution is taken from #673, proposed by @oviano.
=> [core] Use busy wait only to refine below 1 ms.

srtcore/common.cpp
Add monotonic clock to `CTimer::sleepto(...)`
Another PR #929 adds monotonic clock for the rest of such waits as well:
- `CTimer::waitForEvent()`
- `CTimer::condTimedWaitUS()`
=> [core] Use monotonic clock in CTimer::sleepto()

docs/AccessControl.md
Based on the discussion with @justinjoy, adding a short description of the SRT Access Control Guidelines to specify the use case in short, before going into the details.
=> [docs] Add short description of access  control.

CMakeLists.txt, README.md, configure-data.tcl, docs/BuildOptions.md
Fixes #885
Added build options description: `BuildOptions.md`.
Added entry info in README.
Removed unnecessary description in CMakeLists.txt in comments; the new file is a more appropriate place for this description.
Fixed duplicated enable-unittests in `configure-data.tcl`.
=> Added description for build options.

srtcore/buffer.cpp
As discovered by @jeandube, `countBytes(...)` is called twice when `readMsg(...)` is called.
This wrongfully counts packets as removed twice, leading to faulty statistics on the number of acknowledged packets.
First removal happens on line 1696:
```
if (pktlen > 0)
countBytes(-1, -pktlen, true);
```
=> [core] Fixed repeated use of countBytes

srtcore/buffer.cpp, srtcore/logging.h
Lacking definition of `IF_HEAVY_LOGGING` for a case with `--disable-logging` caused treating it as a potential function call and caused compile error at use time.
=> Added lacking IF_HEAVY_LOGGING for logging off. Removed duplicated def

srtcore/common.cpp
Replaced two `if` statements with a single one.
=> [core] Minor CTimer::sleepto improvement

CMakeLists.txt, srtcore/filelist.maf
Fixing version.h reference in filelist.maf. Wrongfully added in #639.
@lewk2 please review if the build is still ok.
=> [build] Removed version.h direct include

apps/srt-tunnel.cpp
`close(fd)`, `write(fd, ...)` and `read(fd, ...)` are not suitable for socket operation in Windows.
I have changed them to `closesocket`, `send` and `read`, while use `read/write` for other platforms to prevent sigpipe signal.
why use shutdown for tcp_close:
that is what `udpcommon` class in transmitmedia.cpp does.
=> [apps] Fix broken TcpMedium of srt-tunnel in windows

srtcore/core.cpp
Periodic NAK report is a mechanism for the receiver to periodically resend reports on the current loss list. Roughly, NAK interval equals to `max(300ms; RTT / 2)`. More precise description is [here](https://github.com/Haivision/srt/issues/701#issuecomment-508121973).
Periodic NAK report timing **has several minor issues**. They are mainly described in #701.
Those issues can be split into two groups:
1. Periodic NAK report is triggered too early after a LOSS report for this very range of packets was already sent.
2. Newly detected loss is added to the general receiver's loss list, and sent too soon with all the previous packets detected as lost.
`CUDT::checkNAKTimer()` is called with every incoming packet. Previously it was only checking if it is time to send NAK report. But if the …
=> [core] Improved periodic NAK report timing

srtcore/fec.cpp
The problem was that the criteria for whether the vertical FEC control packet should be emitted were based on a comparison against the earliest top FEC group base sequence, which was written in the characteristic data of the horizontal source group. As horizontal was checked first, after it was decided that the FEC control packet is required, it updated the base, as required for a case when an FEC control packet was shipped. This base, however, was also used for vertical groups to check, which column the given sequence number belongs to. Unfortunately, after updating the base for the horizontal groups, the effective group offset was negative (in the past), in which case the check for a necessity for a vertical FEC control packet was avoided, in result the FEC control packet wasn't shipped …
=> Fixed bug: vertical FEC/CTL packet was missing when both H/V were to be done

.travis.yml
- OSX: explicitly list openssl homebrew addon package dependency
- OSX: explicitly set PKG_CONFIG_PATH environment variable
=> Fix TravisCI OSX build

srtcore/api.cpp, srtcore/api.h, srtcore/core.cpp
`CUDTUnited::connect_complete(...)` can throw an exception. It has to be handled. Refer too issue #971.
Alternative fix in #972 produces more changes, that can impact normal operation mode (without exception).
Further improvement of the socket closure while handshake is being processed should  be performed.
This PR only fixes obviously uncaught exception.
=> [core] Catch exception from connect_complete.

srtcore/core.cpp, srtcore/list.cpp, srtcore/list.h
- Renamed `CSndLossList::getLostSeq()` to `popLostSeq()`
- Minor refactor of CSndLossList::insert()
- Extra check for length in `CSndLossList::popLostSeq()`
Suggested review method: by commit.
=> CSndLossList::getLostSeq() renamed to popLostSeq()

examples/recvlive.cpp, srtcore/srt.h
Fixes #986 
Changes:
1. Deprecated options use different solutions in C and C++:
- C++: usual static const of the same type as other options
- C: a separate enum type for these options, with deprecation marker
2. Fixed: public attributes available now for both C and C++ for GNU-compatible compilers
3. Fixed build break in an example: `srt_logging` namespace should be used
=> Fixed deprecated option declarations to work in C mode

examples/recvlive.cpp, srtcore/srt.h
Reverts Haivision/srt#988
Changes are incomplete:
- deprecated enums don't work with GCC < 6
- there is a typo in SRTO_TWOWAYDATA definition
=> Revert "Fixed deprecated option declarations to work in C mode"

CMakeLists.txt
Due to that this effective `"GNU MATCHES "GNU|Apple...etc"` old cmake was trying to match the `GNU` **variable**, not the variable out of which `GNU` came out. This, again, contained 0 or 1, probably, and didn't match the pattern.
Due to this problem, gcc compiler wasn't recognized as GNU and therefore requiring `-std=c++11` option for applications and `srtsupport_virtual` target, and this way caused a build break.
=> Fixed: old cmake wrong syntax for MATCH

srtcore/channel.cpp, srtcore/packet.cpp, srtcore/packet.h
=> [core] htonl and ntohl moved to CPacket

srtcore/buffer.cpp, srtcore/buffer.h
Changes:
* added two simplification functions:
- freeUnitAt: should be used always when a unit is going to be removed from the buffer (and freed for later use)
- `shift` group ( + `_forward` and `_backward`): shortcut for advancing and demoting a rolling number that is an index to a circular buffer
* Some improvements in comments
* Improvements in debug logs
* Refax of the debugging stuff (`debugJitter` taken out the function to improve readability)
=> Short Functions: freeUnitAt, shift. Minor log improvements and refax.

srtcore/api.cpp, srtcore/buffer.cpp, srtcore/cache.cpp, srtcore/channel.cpp, srtcore/channel.h, srtcore/common.cpp, srtcore/congctl.cpp, srtcore/core.cpp, srtcore/crypto.cpp, srtcore/epoll.cpp, srtcore/handshake.cpp, srtcore/list.cpp, srtcore/packet.cpp, srtcore/packet.h, srtcore/platform_sys.h, srtcore/queue.cpp, srtcore/srt_c_api.cpp, srtcore/srt_compat.h, srtcore/window.cpp
Changes:
1. Removed all platform-related includes from everywhere - replaced by `#include "platform_sys.h"`
2. The platform include file is armed with all possible platform-related include files.
=> Made order in includes

apps/transmitmedia.cpp, docs/stransmit.md, testing/testmedia.cpp
Fixes #956.
This changes also the existing behavior, as now if you specify the `adapter` parameter for `udp` URI, the socket used for sending will be also bound to this address. Please review if this change is acceptable.
=> Added binding a socket used for multicast to the adapter address, if adapter was specified

srtcore/netinet_any.h
Added construction from sockaddr and in_addr.
Added family override.
Fixed address comparison for Mac.
=> Improvements and fixes in sockaddr_any

srtcore/common.cpp, srtcore/congctl.h, srtcore/udt.h, testing/testmedia.cpp
Fixes #1019, #1018 
(part of the fixes are provided additionally on #1006)
Changes:
1. Added copy-assignment operator for `SrtCongestion`.
There was a hidden problem there, as the copying was predicted to copy just the name, but the pointer to the managed object was set to 0. This copy constructor wasn't used, however, when copying was made through the `CUDT` copy constructor, which was using simple assignment inside, and this one was using a generated assignment operator, which was copying the pointer value as well. **Fortunately** nothing wrong happened, as the newly spawned socket for accept was then processed by `CUDT::acceptAndRespond` which was calling inside `CUDT::setupCC` that was calling `configure` on this object, which was overwriting the pointer value anyway, just relying on …
=> Added fixes for assignment copy compliance

.travis.yml, scripts/collect-gcov.sh, sonar-project.properties
This PR adds integration with SonarCloud for static code checks and test coverage.
SonarCloud project URL: [https://sonarcloud.io/dashboard?id=srt](https://sonarcloud.io/dashboard?id=srt)
Condition `TRAVIS_REPO_SLUG == "Haivisio/srt"` should disable this checks if built in forks.
Potentially can use some environment variable like `RUN_SONARCUBE` to disable SonarQube check from Travis project config, without changing the yaml file.
Turned out SonarCloud analysis in Travis is only supported for internal pull requests.
[Documentation](https://docs.travis-ci.com/user/sonarcloud/#analysis-of-internal-pull-requests)
[Travis Issue](https://github.com/travis-ci/travis-ci/issues/8379)
SonarCloud for GitHub Actions ([link](https://github.com/SonarSource/sonarcloud-github-action)) is not recomended …
=> Added SonarCloud integration

srtcore/logging.h
1. Removed one constructor. Using default arguments it was able to shortcut them both into one.
2. Added initialization of fields that weren't initialized
=> Fixed initialization in LogConfig

srtcore/queue.cpp
Microseconds were wrongfully treated as milliseconds.
Introduced in PR #929
=> [core] Fixed frequency of timers checking

.clang-format
Added `AllowShortFunctionsOnASingleLine: Inline` 
This allows only an empty function body and functions defined inside a class to be on the same line as the function declaration.
Refer to **AllowShortFunctionsOnASingleLine** in [Clang Format Style Options](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
Example formatting of a code block of sync.cpp (this PR):
```
long long srt::sync::count_seconds(const steady_clock::duration& t)
{
return t.count() / s_cpu_frequency / 1000000;
}
srt::sync::steady_clock::duration srt::sync::microseconds_from(long t_us)
{
return steady_clock::duration(t_us * s_cpu_frequency);
}
```
Formatting of the same block with the current `.clang-format` from master:
```
long long srt::sync::count_seconds(const steady_clock::duration& t) { return t.count() / …
```
=> [build] clang format short func alignment

apps/transmitmedia.cpp, apps/transmitmedia.hpp, srtcore/api.cpp, srtcore/common.cpp, srtcore/common.h, srtcore/congctl.h, srtcore/udt.h, srtcore/utilities.h, testing/testmedia.cpp, testing/testmedia.hpp
Unfortunately `CUDTException` class is very hard to tear off the current code, so the following was done:
1. The CUDTException class was moved to `common.h`, which means that it is internal now.
2. The `UDT::getlasterror()` legacy API function is actually useless. It still returns the same reference to CUDTException, but this time you need additionally `common.h` to be included in order to access the returned object. Note that UDT legacy API is currently treated as deprecated - instead of this function you should use `srt_getlasterror()` and `srt_getlasterror_msg()`.
3. The `m_strMsg` field is turned `mutable` as it functions only as a cache for message string. Note that the major/minor fields are not intended to be altered during this object's runtime.
Fixes #861
=> Fixes for CUDTException class. Derived from exception, moved out of the API.

srtcore/buffer.cpp, srtcore/congctl.cpp, srtcore/congctl.h, srtcore/core.cpp, srtcore/sync.cpp, srtcore/sync.h, test/test_sync.cpp
The following chang (1st commit) fixes #1033 
* `microseconds_from(long t_us);` ->`microseconds_from(int64_t t_ms);`
* `milliseconds_from(long t_us);` ->`milliseconds_from(int64_t t_ms);`
* `seconds_from(long t_us);` ->`seconds_from(int64_t t_ms);`
`m_tsTsbPdTimeBase += microseconds_from(uint64_t(CPacket::MAX_TIMESTAMP) + 1);`
changed to 
`m_tsTsbPdTimeBase += microseconds_from(int64_t(CPacket::MAX_TIMESTAMP) + 1);`
`CPacket::MAX_TIMESTAMP` = 0xFFFFFFFF` (UINT32_MAX)
1. Removed excessive usage or `srt::sync` namespace resolution.
2. Added unit test for "duration from" functions.
=> Fix of sync duration from long

srtcore/udt.h
PR #1023 has changed
`typedef CBytePerfMon TRACEBSTATS;` --> `typedef class CBytePerfMon TRACEBSTATS;`
while `CBytePerfMon` is declared as a struct in srt.h.
This PR fixes the type definition.
=> [core] Fixed CBytePerfMon typedef in udt.h

srtcore/api.cpp, test/test_cryspr.cpp
1. When SRT library is built with `ENABLE_ENCRYPTION=OFF`, CRYSP test should be excluded.
2. Fixed warning "catching polymorphic type by value" (CUDTException)
=> Minor fixes: crysp test and catch exception by value

.travis.yml, srtcore/api.cpp, srtcore/sync.cpp, srtcore/sync.h, test/test_sync.cpp
CVs that can use monotonic clock are 
* `CUDTUnited::m_GCStopCond` 
* `CTimer::m_TickCond`
Other CVs use regular clock, as in v.1.4.1. 
Therefore, `srt::sync::rdtsc(...)` function does not use MONOTONIC_CLOCK, but always uses regular clock. This is required for other waits on CVs to work properly.
Fixes #1034
Added `ENABLE_MONOTONIC_CLOCK=ON` build configuration to Travis.
Added `SyncEvent.WaitForMonotonic` test case that is built when the monotonic clock is enabled.
This is a fix to have the current master version working with the monotonic clock as in v.1.4.1.
To be revised in PR #800.
=> Fixed monotonic clock build option

srtcore/core.cpp, srtcore/queue.cpp
`CUDT::packData(pkt)` returns a pair of result + next send timestamp.
This timestamp should be used to insert the socket back to `CSndUList` to reschedule.
But the value was ignored, and the current time was used instead.
Introduced in PR #929
=> [core] Fixed next send time (CSndUList)

srtcore/api.cpp, srtcore/api.h
Renamed a field that had the same name in `CUDTSocket`. This could cause confusion especially for thread logging.
=> Renamed CUDTUnited::m_ControlLock

srtcore/core.cpp
This fix restores the fallen-out update of the last response timer watchdog in the control packet handler. Without this, it it would break the connection at the sending side as it receives no data and control packets wouldn't reset it.
It also restores the code that was there before.
=> Restore mistakenly removed connection watchdog timer in control packets

CMakeLists.txt
Fixes #1041
Removal due to problems for CMake with empty targets, and haicrypt_virtual becomes empty when encryption is off.
=> Removed haicrypt_virtual

apps/apputil.cpp, haicrypt/hcrypt_ctx_tx.c, haicrypt/hcrypt_tx.c
> 'break' will never be executed
> The right-hand operands of && and || should not contain side effects
=> Removed excessive break statements and fixed side effects

srtcore/api.cpp, srtcore/api.h, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/cache.h, srtcore/common.cpp, srtcore/common.h, srtcore/core.cpp, srtcore/core.h, srtcore/epoll.cpp, srtcore/epoll.h, srtcore/list.cpp, srtcore/list.h, srtcore/logging.h, srtcore/packetfilter.cpp, srtcore/queue.cpp, srtcore/queue.h, srtcore/sync.cpp, srtcore/sync.h, srtcore/window.cpp, srtcore/window.h, test/test_sync.cpp
This is the second subset of PR #800 on the way to C++11 support.
`srt::sync::Mutex` class is introduced. The class wraps pthread mutex.
In future it is expected to be directly mapped to `std::mutex` in case SRT is built with C++11 threads.
1. Introduced `srt::sync::Mutex` class that wraps pthread mutex.
2. Replaced `CGuard` with `ScopedLock` and `UniqueLock`. Added CGuard typedef to reduce the number of renaming until #1049 is merged.
3. Renamed `CRcvQueue::m_PassLock` to `CRcvQueue::m_BufferLock`
4. Renamed `CRcvQueue::m_PassCond` to `CRcvQueue::m_BufferCond`
5. Replaced `CTimer::sleep()` by `srt::sync::SleepFor(const Duration&)`
Blocks #1049
=> Introducing sync Mutex wrapper class

srtcore/core.cpp
During the tests that have been involving closing the socket being members of a group in various unsynchronized conditions it has happened sometimes that a socket was attempted to be closed while it was during the process of closing. Normally all mutexes protecting internal data were preventing any clashes that could result from it. In the case of closing the crypto control object it was happening, however, that one has closed the crypto without having all flags updated, so it was happening that the crypto wasn't closed and therefore deferred the close up to the destructor (which was unwanted in cases when the destruction was called together with the application) or was attempted to be twice destroyed.
The fix has made this destruction relying on the object that represents the real state …
=> Bugfix: close the crypto under correct conditions

srtcore/core.cpp, srtcore/list.cpp
The reason for this change is that the case of the "stale loss report" so far wasn't handled at all.
The UDT handler provided only a case when a loss report covers PARTIALLY the already dismissed range from the sender buffer, but hooks up at least to some packets that are in the sender buffer. This normally should never happen, but the socket group code involving sequence number resynchronization has made this more probable to happen.
This fix only increases the probability to fix things up (as a UDP packet can still be lost), but it's required to not make the receiver hang around uselessly in case when it tried to recover packets that have never be predicted to be sent.
The signal to TSBPD in case when the dropping is received is required because otherwise TSBPD may hangup forever when …
=> Bugfix: properly handle cases of stale loss report

apps/srt-tunnel.cpp, srtcore/api.cpp, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/channel.cpp, srtcore/common.cpp, srtcore/common.h, srtcore/congctl.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp, srtcore/epoll.cpp, srtcore/epoll.h, srtcore/handshake.cpp, srtcore/list.cpp, srtcore/logging.h, srtcore/netinet_any.h, srtcore/packet.cpp, srtcore/packet.h, srtcore/platform_sys.h, srtcore/queue.cpp, srtcore/srt_compat.h, srtcore/sync.cpp, srtcore/utilities.h, test/test_epoll.cpp
Recommended turning off whitespace difs for review.
=> Added cosmetix from the pre-group-refax

test/filelist.maf, test/test_list.cpp
This is asubset of changes from PR #1012. Extracted unit tests part.
The following tests are failing due to #1000:
- CSndLossListTest.InsertHeadNegativeOffset01
- CSndLossListTest.InsertFullList
- CSndLossListTest.InsertFullListNegativeOffset
They are marked as disabled for now, to fix in the future.
=> [tests] Added CSndLossList tests

docs/API-functions.md, docs/API.md, srtcore/api.cpp, srtcore/api.h, srtcore/core.h, srtcore/epoll.cpp, srtcore/epoll.h, srtcore/srt.h
Summary of changes:
1. Introduced handling of the edge-triggered-only events. Normally events can be level-triggered or edge-triggered, depending on extra flag `SRT_EPOLL_ET`. Some others can be only edge-triggered and no flag is needed to mark it (this is also what exists in kevent and Linux epoll).
2. Added a new edge-only event type, `SRT_EPOLL_UPDATE`. This will be used in the group code in a situation when a new connection is added to the group while the group as a whole is still considered connected. This event is required to update groups of types that allow member connections to be idle (currently: backup group).
3. Added new functions for clearing out socket subscriptions, be it everything at all or just those ready.
4. The error code for a case when a waiting function has been …
=> Epoll improvements necessary for socket groups external implementation

CMakeLists.txt, haicrypt/haicrypt.h
After #1047 HaiCrypt is no longer a separate target. `HAICRYPT_EXPORTS` sometimes makes a mess from a build on Windows.
=> [build] HaiCrypt exports deleted from cmake

srtcore/api.cpp, srtcore/core.cpp, srtcore/srt_c_api.cpp
The '0' value should not be used as a "no ISN number", as it can be as well a valid sequence number.
=> Bugfix: use -1 as no-forced-isn

srtcore/core.cpp, srtcore/core.h
This actually isn't any bugfix here, but this change is required so that the TSBPD setting managed for the socket groups can be set correctly.
=> Fixed: move tsbpd state setting to correct place

srtcore/core.cpp, srtcore/core.h
Pulled `processCtrlLossReport()` func out of the bigger `processCtrl()` function.
No changes in the function body. Direct copy.
=> [core] Minor: pulled processCtrlLossReport() func out

apps/apputil.cpp, testing/srt-test-live.cpp
Mistake: The "<argument but not terminated mistakenly" was the only effective way to enforce ARG_ONE type of option argument. The case "<argument> Specified properly" was then leading to ARG_NONE.
Also fixed the `-v` option in srt-test-live, which allows to optionally specify the channel used for verbose messages.
Another fix is that when an option was already specified the argument the old way, like `-v:2`, then the argument that follows that specification is always considered the next argument, regardless of the argument type of the option. The problem was that previously if you specified `-v udp://:9999 srt://:5555`, it was definitely specified incorrectly, but with `-v:1 udp://:9999 srt://:5555` it should consider the argument for `-v` option already specified, so the following …
=> Fixed <*> case handling in helptext-type-parser and -opt:val case

srtcore/channel.cpp
A general log message is too expensive here. Switched to heavy log.
=> [core] Changed log level to heavy in CChannel::sendto

.travis.yml
This change fixes macOS CI builds at the cost of increased build time (~2min increase).
This change should be revisited once the [TravisCI issue](https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296) is addressed in their macOS images.
Further information:
- https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296
- https://github.com/Homebrew/homebrew-bundle/issues/646
=> Enable brew update with macOS builds as a workaround to a TravisCI issue

srtcore/list.cpp, srtcore/list.h, test/test_list.cpp
1. Added several unit tests.
2. Minor refactoring of the `CSndLossList::insert(..)`.
3. Improved `CSndLossList::insert(..)` for the serial element.
Example of the improvement. Three insert operations:
```
insert(1, 2);
insert(4, 4);
insert(3, 3);
```
The state of the list after every insert operation was (**format** `pos:[seqstart, seqend]`):
```
0:[1, 2]
0:[1, 2], 3:[4]
0:[1, 2], 2:[3], 3:[4]
```
After this PR:
```
0:[1, 2], 
0:[1, 2], 3:[4] 
0:[1, 4] 
```
Taken from `TEST_F(CSndLossListTest, InsertCoalesce)`
=> Small improvements of CSndLossList::insert

apps/transmitmedia.cpp
Added the possibility to set the buffer size of the UDP socket.
It turned out at high and bursty data rates (~60 Mbps) the `epoll_wait(udp_socket)` is not fast enough to signal about the possibility to read from a socket. It results in loosing data when there 
Waiting on a UDP socket with `::select(...)` works perfect, but we can't use it in the current implementation of the `srt-live-transmit`.
UDP socket needs a bigger buffer to store incomming data. For example, setting 64 MB buffer seems to workaround the issue #933.
```
$ cat /proc/sys/net/core/rmem_max
212992
$ sudo sysctl -w net.core.rmem_max=26214400
net.core.rmem_max = 26214400
$ cat /proc/sys/net/core/rmem_max
26214400
```
Example URI:
```
"udp://:4200?rcvbuf=67108864"
```
Example full URI:
```
./srt-live-transmit …
```
=> srt live transmit UDP buffer size config

srtcore/api.cpp, srtcore/epoll.cpp, srtcore/epoll.h
Separated UPDATE and ACCEPT (that is, IN) event subscription as UPDATE is edge-triggered only and this would mix level- and edge-triggered.
=> Fixed: UPDATE and ACCEPT cannot be mixed

srtcore/fec.cpp
For rebuilt packets, * FEC * may still report it as a lost packet. This happens in `row-only` mode.
The following transmission is configured as `cols:10,rows:1,layout:even,arq:onreq`:
```
UDT type: data seqno: 90 msgno: 91
UDT type: ack  seqno: 90
UDT type: ack2
UDT type: data seqno: 91 msgno: 92
UDT type: ack  seqno: 92
UDT type: ack2
UDT type: data seqno: 92 msgno: 93
UDT type: data seqno: 93 msgno: 94
UDT type: ack  seqno: 93
UDT type: ack2
UDT type: ack  seqno: 94
UDT type: ack2
UDT type: data seqno: 94 msgno: 95
UDT type: data seqno: 95 msgno: 96
UDT type: data seqno: 96 msgno: 97
UDT type: ack  seqno: 97
UDT type: ack2
UDT type: data seqno: 98 msgno: 99
UDT type: data seqno: 99 msgno: 100
UDT type: data seqno: 99 msgno: 0
UDT type: ack  seqno: 100
UDT type: ack2
UDT type: data …
```
=> [core] Avoid reporting packets rebuilt by FEC as lost.

apps/srt-file-transmit.cpp, apps/srt-live-transmit.cpp, docs/API-functions.md, srtcore/common.h, srtcore/srt.h, srtcore/srt_c_api.cpp
- Added `uint32_t srt_getversion();`
- Added description to the API docs
- Added usage in apps
Fixes partially #1016 (does not provide a git commit info)
=> Add srt_getversion API function

srtcore/api.cpp, srtcore/buffer.cpp, srtcore/common.cpp, srtcore/common.h, srtcore/core.cpp, srtcore/epoll.cpp, srtcore/queue.h, srtcore/sync.cpp, srtcore/sync.h
Introducing `sync::CEvent` and `sync::CGlobEvent` to replace static functionality of the `CTimer`
The global CEvent g_Event is now used for synchronization.
Static CV and mutex were used in the previous implementation that is to be replaced. A static CV can't be initialized to use a monotonic clock. Therefore, switched to a global CV.
1. Problem: the CV of the global CEvent g_Event should be initialized with `PTHREAD_COND_INITIALIZER`. Otherwise, it fails on Windows.
2. `CTimer::triggerEvent()` is being replaced with `g_Sync.notify_one()`  according to the previous implementation of the `triggerEvent()`. Although to me notify_all() makes more sense.
3. `CTimer::waitForEvent()` is being replaced with `g_Sync.wait_for(milliseconds_from(10))` according to the implementation of the …
=> [core] Introducing sync::CEvent

docs/API.md, test/test_enforced_encryption.cpp
That's simply a copy of `TestConnect` method with removed unused parts replaced with always using blocking mode and without encryption. The time spent by accept is measured with 10ms resolution. Normally it should collect just one case of 10ms waiting, but it waits until the boolean flag is set that marks the last instruction in the thread and finished call to `srt_accept`.
=> Added a note in docs regarding accept time and failing accept-timeout tests

srtcore/api.cpp, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/core.h, srtcore/srt.h, srtcore/srt_c_api.cpp
First portion of changes for balancing groups. Included:
- `getFlightSpan` utility
- new Group container (maintains the "last used link" pointer)
- the "configure" function (for balancing groups it is used to set the balancing algorithm)
- previous refax for Backup groups slightly changed to be also useful for Balancing
=> BALANCING GROUPS: prefax and utilities

srtcore/core.cpp, srtcore/core.h, srtcore/packet.h, srtcore/srt_c_api.cpp
1. Default ("trap") value for msgno is -1 (0 is reserved for PacketFilter control packet).
There's a new feature added that affects also single sending that the msgno can be enforced. But "do not enforce" value is checked as -1, so this should be the default value.
2. The definition of `MsgNo` based on `RollNumber` should use N-1 value as the furthest bit number up to which the occupied bits spread (N is the number of these bits).
The problem: `RollNumber` gets the N value so that it can use it with `Bits` template, which requires the left size argument the first bit of the used series. This represents the maximum value for the rolling number (after crossing which it should revert back to the minimum value). What should be the maximum value of the message number, please refer to the …
=> Bugfixes for balancing groups

srtcore/api.cpp, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/common.h, srtcore/core.cpp, srtcore/core.h, srtcore/fec.cpp, srtcore/list.cpp, srtcore/list.h, srtcore/packetfilter.cpp, srtcore/srt.h, srtcore/srt_c_api.cpp, srtcore/window.cpp, srtcore/window.h, testing/testmedia.cpp
Depends: #1184
This turns the values of:
* -1 - meaning a nonexistent seqno
* -1 - meaning a nonexistent msgno
* 0 - meaning a control msgno (used in packet filter)
This does not:
* Fix stupid msgno values used for special meaning (the behavior and actual values are preserved)
* Change into constant in cases when -1 is used as a special value for "no index" or "no offset"
=> Added constants for "trap" representations for msgno and seqno

docs/API-functions.md, srtcore/srt_c_api.cpp
Hi,
I notice that C API srt_rendezvous() returns value such as "5003". To be SRT API compliant, it should return "CUDT::APIError" instead. This PR fixed srt_rendezvous() returned value.
I also add missing information on srt_rendezvous() API.
Regards,
=> srt_rendezvous

docs/API-functions.md, srtcore/srt.h
Fixed typos: permon -> perfmon.
=> Minor fixes of typos (permon -> perfmon)

CMakeLists.txt
When the automatic download of GTest is not specified, but gtest is installed in another location, find_gtest.cmake is able to find it successfuly, but the code fails to build, as the include directories were not added to the test-srt list.
WIth this commit, code builds and unit tests pass when gtest is not installed in the system root.
=> Fix GTest include dirs

docs/API-functions.md, docs/srt-live-transmit.md, srtcore/srt_c_api.cpp
- Small improvements of srt-live-transmit doc regarding rendezvous mode parameters.
- `srt_rendezvous(..)` in API.md has the following note: "The port value shall be the same in `local_name` and `remote_name`." Deleted.
- `srt_rendezvous(..)` function has a port check: remote should match to local. Removed.
- Fix API-functions.md: return value INVAL is missing
- Check why srt-live-transmit allows to configure a different rendezvous port
`"srt://192.168.178.182:4200?adapter=192.168.1.237&port=4201"`
* PR #1198 Fixed rendezvous handling
=> Removing rendezvous restriction for matching local and remote ports

apps/srt-tunnel.cpp
The problem: somehow by unknown reason one pipe is closed due to closed connection, but the other remains open. This leads to a behavior that one side of the connection gets the error report from the reading function, but the other stays hanged up forever, and there's completely no way to force the thread to resume while it hangs on `recv` call, even if you close the socket from which this function is reading.
This is slightly worked around by having a 1 second timeout on reading from the socket so that there's a check once per 1 second whether the Engine object is declared broken. If it's not broken, the reading attempt is simply repeated, otherwise it's reported just like any other read error. This at least gives it a chance to interrupt the reading thread and join it.
The problem was …
=> Fixed tunnel bug: hangup when killing a dead tunnel

srtcore/core.cpp, srtcore/handshake.h
The call to `NextExtensionBlock` should have been placed there in the beginning. In the form before the fix it theoretically does nothing dangerous, except that it potentially calculates a length between NULL and a valid pointer, which isn't fortunately used for anything, but technically is wrong.
Additionally these functions for block extraction are used only there, while the functionality for extracting extensions is potentially needed in further extensions, external programs, as well as callbacks.
=> Fixed correct usage of next-exp in extension loop. Exposed functionality to extract extensions

srtcore/api.cpp, srtcore/api.h
Fixes #1234 
The problem was that newly introduced function `makeClosed` was used in more places than it was necessary and therefore it was setting the `m_bBroken` flag too early. This caused inability to dispatch incoming packets and rejected any other transmission, which then led to closing the connection before the file can be completely transmitted.
=> Fixed bug: setting broken flag too early. Breaks too early data transmission

srtcore/api.cpp, srtcore/api.h, srtcore/core.cpp, srtcore/core.h, srtcore/queue.cpp, srtcore/queue.h, srtcore/sync.cpp, srtcore/sync.h
This PR introduces `srt::sync::CTimer` class to wrap threads operations:
1. CThread is directly mapped to C++11 threads if C++11 is enabled.
2. CThread wraps pthreads if C++11 is disabled.
See the roadmap #1103
=> C++11 Threads Part 7: Added CThread Wrapper

CMakeLists.txt
This PR adds support for three more `CMAKE_SYSTEM_NAME` values that may be present for iDevice cmake toolchains and can be tested with https://github.com/leetal/ios-cmake.
=> Broaden Darwin check to include iOS, tvOS and watchOS

srtcore/core.cpp
This function is unused, only exposed for external users that might want to extract extension information manually.
The size of  the whole extension block was set incorrectly, as the size is measured since the first word behind the TYPE/SIZE block, while the `+1` at the first argument was shifting already by 1 towards the beginning. So should have been the end shifted.
=> Fixed: copy whole size of the block for an extension

docs/srt-live-transmit.md
=> [docs] Added a note on UDP buffer size in srt-live-transmit

srtcore/api.cpp, srtcore/core.cpp
A set of changes extracted from #1244, that does not affect the functionality. Code improvement.
The second commit contains minor fixes of some issues reported by [SonarCloud](https://sonarcloud.io/project/issues?createdAfter=2020-03-01&createdBefore=2020-04-23&directories=srtcore&id=srt&open=AXDKvvUnZJZS4c4MaLuj&resolved=false) static analyzer.
=> [core] Use APIError in more places

srtcore/api.cpp, srtcore/api.h, srtcore/sync.cpp, srtcore/sync.h, srtcore/sync_cxx11.cpp
Added thread-local storage wrapper for C++11 and pthreads.
C++11 keyword `thread_local` can be used only at a static or extern scope, and can't apply to a regular class member. Therefore, `m_TLSError` was removed from `CUDTUnited` and places as a static object of `srt::sync` module.
=> [core] Thread-local error for C++11 and pthreads

srtcore/buffer.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/sync.cpp, srtcore/sync.h, srtcore/window.h
During the development, some parts of the SRT sync lost their compatibility with the corresponding STD chrono API.
This PR brings compliance back.
It mainly changes checking for empty (zero) timepoint.
Changes extracted from #1266 that introduces C++11 STD chrono build option.
=> [core] Minor adjustments for sync timing compliance

test/test_sync.cpp
This PR mainly adds an additional check for CLang compiler that works well with regex.
Therefore, Sync.FormatTime unit tests can be enabled.
=> [tests] Sync FormatTime test enabled on MacOS

srtcore/api.cpp, srtcore/core.cpp, srtcore/crypto.cpp, srtcore/fec.cpp, srtcore/packet.cpp
1. Demoting Error logs into Warn or Note in case when it potentially might be spread very often and harm the processing. Removed also SND-DROPPED log that is repeated then by Debug and may be spread lots of times during the transmission.
2. Minor cosmetic fixes:
- using stable expression of "enforced encryption"
- Removed commented-out encrypt/decrypt functions that have been once moved to `CCryptoControl` (detected during the search for Error logs).
=> Demoted too heavy error logs into warnings

apps/srt-live-transmit.cpp
Fixes #817 
The problem was that the reading part of the loop didn't check if the source medium is ready to read from. For a case of both-listener it made that after handling the target listener the loop was stated as capable of running, without checking if the source medium is ready for reading - which wasn't the case when the source was also an SRT listener and not yet accepted a connection.
=> Fixed not-read-ready case in srt-live-transmit

testing/testmedia.cpp, testing/testmedia.hpp
1. The application supports the syntax for group type as "TYPE/CONFIG". Whether any config is supported by the group, it depends on the group type.
2. Introduced a new app-only SRT attribute `groupconfig`, which resolves into setting the `m_group_config` field, applied onto the configuration.
3. A configuration extracted from "TYPE/CONFIG" syntax is applied on the newly created group in caller mode.
4. A configuration extracted from `groupconfig` attribute is applied on the newly accepted group on the listener side.
=> Added support for the new group API

apps/verbose.hpp, common/win_time.cpp, srtcore/channel.cpp, srtcore/epoll.cpp, test/test_connection_timeout.cpp, test/test_file_transmission.cpp, test/test_listen_callback.cpp
Fixes #1081
1. The `noeol` field in `ErrLog` class was actually a bug. This field exactly was generating the warning, while there weren't any announced functions in this class, so it was unused indeed. The field in use was the one derived from `Log` class, derived together with functions that use it.
2. I added the "fake usage" for the argument. This is better than adding `ATR_UNUSED` marker because maybe at some point we will provide some implementation using Windows API.
3. The warning for not implemented `add_ssock` on some platforms is intended and should appear. The only true way to eliminate it is to provide the implementation that is lacking.
=> Added MinGW warning fixes

docs/API-functions.md, srtcore/common.cpp, srtcore/core.cpp, srtcore/queue.cpp, srtcore/srt.h, testing/testmedia.cpp, testing/testmedia.hpp
=> Added timeout reason. Updated correctly reject reason on timeout

docs/API-functions.md, srtcore/api.cpp, srtcore/core.cpp, srtcore/srt_c_api.cpp
`srt_group_data(..)` now returns group size (via argument `inoutlen`) even if no output array to fill is provided.
This behavior can be used to retrieve the size of the SRT socket group without providing any array to fill with group data.
| in:output | in:inoutlen    | returns      | out:output | out:inoutlen | Error |
|-----------|----------------|--------------|-----------|--------------|--------|
| NULL      | NULL           | -1           | NULL      | NULL         | `SRT_EINVPARAM` |
| NULL      | ptr            | 0            | NULL      | group.size() | ✖️ |
| ptr       | NULL           | -1           | ✖️         | NULL         | `SRT_EINVPARAM` |
| ptr       | ≥ group.size   | group.size() | group.data | group.size | ✖️ |
| ptr       | < group.size   | -1           | ✖️         | …
=> srt_group_data(..) returns group size even without output array

docs/API.md, srtcore/core.cpp, srtcore/core.h, srtcore/srt.h, testing/srt-test-live.cpp
Changes:
1. Added field that will be assigned the group type extracted from the handshake extension.
2. Added a socket option: `SRT_GROUPTYPE`, read only.
Tested: the listener callback for `groupcheck` correctly extracts the group type through this option and can make decisions basing on it.
=> Extracting group type from the incoming handshake for listener callback

srtcore/buffer.cpp, srtcore/utilities.h
There was a mistake in the calculation of the moving average values of msRcvBuf and msSndBuf.
Note. Initial values of `m_iCountMAvg`, `m_iBytesCountMAvg` and `m_TimespanMAvg` are zero.
It means, at the start, the update will be:
```
m_iCountMAvg      = (int)((0 + (count * elapsed_ms)) / 1000);
```
Probably better to initialize with `-1` and set the initial value to the instant value.
@mbakholdina What do you think?
Fixes #1272
=> [core] Fixed MAVG msRcvBuf and msSndBuf

apps/apputil.cpp, srtcore/api.cpp, srtcore/core.cpp, srtcore/core.h, testing/testmedia.cpp
The group support for `srt_bstats`.
The statistics structure gets filled with the following fields:
* `msTimeStamp` - updated just like normally, the time distance towards start time
* `pktSentUnique` (also `byte*` and `*Total`) - packets sent to the group by the application
* `pktRecvUnique` (also `byte*` and `*Total`) - packets received from the group by the application
* `pktRecvDrop` (also `byte*` [estimated from average] and `*Total`) - packets skipped in delivery to the application (dropped by all connections that were supposed to transmit it)
All other fields are set to 0.
There's also added an infrastructure that could allow for later rework of the internal statistics structure, and some fields (*Discard) that could be added to the report later.
=> Added group support for stats probing

srtcore/sync.h
`int` is replaced by `int64_t`
=> [core] Fixed sync C++11 duration from

srtcore/api.cpp, srtcore/core.cpp, srtcore/utilities.h
Fixes #1113
Write accessors have an extra `set_` prefix added to the name.
=> Added set_ prefix to write property accessors

srtcore/api.cpp, srtcore/core.cpp, srtcore/core.h
Fixes #1182 
Closes PR #1193 
The problem was with `packData` that the internals (including mainly `m_pCryptoControl`) could be modified by the `CUDT::close` (now `closeInternal`) while `packData` was running in a separate thread (receiver worker). The `CUDT::close` acquires `m_ConnectionLock` for that purpose, which is used normally only during the connection process and not used afterwards. Obviously the processing cannot do data pack-and-send and connection attempt for the same socket, so this lock is for free use in the `packData` function and this lock will not interfere with any other process. The only part that will interact simultaneously with this lock is `CUDT::close` (now `closeInternal`), which locks this for the time of modifying the internal data.
Actually `closeInternal` …
=> Added fixes to prevent crash when close-and-pack

srtcore/core.cpp
This might lead to potential problems; although the result in the form of exception that interrupts the sending or receiving function prematurely, is still a fair enough reaction on the fact that the group got empty after closing all its member sockets, at least the error details could be misleading.
This fix adds a check if the epoll container is empty before calling `swait` and report the connection closed error in response.
Impact: Significant because: this changes the type of error reported to the application, although it fixes a problem of reporting the wrong code.
=> Fixed: prevent calling swait on an empty epoll

scripts/srt-dev.lua
Fixed an problem when Stream ID over 16 bytes failed to parse, add methods to parse SRT_CMD_FILTER and SRT_CMD_GROUP.
=> Add methods to parse SRT_CMD_FILTER and SRT_CMD_GROUP

examples/test-c-client-bonding.c, examples/test-c-server-bonding.c, srtcore/api.cpp, srtcore/api.h, srtcore/common.cpp, srtcore/common.h, srtcore/core.cpp, srtcore/core.h, srtcore/netinet_any.h, srtcore/srt.h, srtcore/srt_c_api.cpp, testing/testmedia.cpp, testing/testmedia.hpp
Changes:
1. Structures for configuring group connection and getting group status have been separated. Common fields are only the socket and target address.
2. For the status structure, there's renamed `status` into `sockstate` and added `memberstate`.
3. The `memberstate` type has been exposed to the API.
=> Reworked the structures for config and status for groups

srtcore/api.cpp, srtcore/core.cpp
TODO:
Extracted from #1253.
Some const-correctness issues are reported by [SonarCloud](https://sonarcloud.io/project/issues?createdAfter=2020-03-01&createdBefore=2020-04-23&directories=srtcore&id=srt&open=AXDKvvUnZJZS4c4MaLuj&resolved=false) static analyzer.
Maxim Sharabayko
Add a converting function similar to bool_int_value(..)  in core.cpp.
Mikolaj Malecki
That would definitely make sense.
If this is setting the option, so reading from variable, there could be even made a dedicated conversion function that will take both optval and optlen, and will possibly throw CUDTException with INVAL when the conversion cannot be properly done (due to invalid length, for example).
Maxim Sharabayko
Maybe even a template function.
Mikolaj Malecki
Of course that's what I meant
This bool_int_value has …
=> Const void cast

apps/srt-file-transmit.cpp, apps/uriparser.cpp, apps/uriparser.hpp
Fixes #1301 
The problem: the `transtype` option sets up flags (this concerns then also `tsbpdmode` `rcvlatency` `peerlatency` `tlpktdrop` and `nakreport`) that are written into the state in `CUDT::clearData` as a part of `CUDT::open` that is called either at the time of self-binding (when you do `srt_connect`) or directly in `srt_bind`. Therefore this option cannot be altered after binding.
The application was trying to set the `transtype=file` parameter on the socket after the creation function (`Source::Create` or `Target::Create`) has already been called, and pre-options already set, and also does the binding. Therefore setting the `transtype` option couldn't happen neither before nor after this call.
The only way to enforce the `transtype` setting was to add this to the list of …
=> [apps] Fixed bug in srt-file-transmit: setting transtype=file at the right place

srtcore/queue.cpp, srtcore/queue.h, test/filelist.maf, test/test_unitqueue.cpp
This is one set of bugs related to #486 
`CUnitQueue::getNextAvailUnit()` has several issues. They are described in the review comments to the code.
This PR consists of three commits:
1. Minor chage: add `size()` and `capacity()` getters to `CUnitQueue`. Needed for unit tests.
2. Added three unit tests describing issues with the current implementation of `CUnitQueue`.
3. Fix of `CUnitQueue::getNextAvailUnit()`
=> Fixed  getting next available unit from CUnitQueue

srtcore/core.cpp, srtcore/core.h
This PR protects access to `CRcvBuffer::readMsg(..)` with `m_RcvBufferLock`.
Together with #1333 fixes #486
In case of the receiver, there are two threads accessing `CUnitQueue`.
Both of these threads were protecting access to `CRcvBuffer` and eventually to `CUnitQueue` with **different** mutexes, meaning there was **no protection from simultaneous writing** via `makeUnit*(..)` functions. 
The thread that receives packets from the network has the following call stack:
- `CUDT::processData(CUnit* in_unit)`
locks `m_RcvBufferLock`
- `CRcvBuffer::addData(CUnit* unit, int offset)`
- `m_pUnitQueue->makeUnitGood(unit, "addData")`
Another thread is the application thread that reads data from the buffer.
Call stack:
- `CUDT::receiveMessage(..)`
locks `m_RecvLock`
- `CRcvBuffer::readMsg(..)`
- …
=> [core] Protecting RCV buffer access

srtcore/core.cpp
This fix changes restrictions on options that are being taken into account only at the function that is called during binding - both self-binding done on an unbound socket used for `srt_connect` and the manual binding by `srt_bind`. When these options were altered between `srt_bind` and `srt_connect` the option setting would be ignored without making the user aware.
=> Fixed restrictions on pre-bind only options

srtcore/buffer.cpp, srtcore/core.cpp
Fixes #1192
This removes the call to `triggerEvent` when it's considered excessive - that is, the `triggerEvent` call is still present in every imaginable execution path that passes through these places where it is removed. The idea for `triggerEvent` is to forcefully release the waiting in `waitForEvent`, which releases the epoll waiting function, so it should be done only if it follows updates in the socket readiness bits.
=> Removed triggerEvents from all cases but after readiness update

srtcore/core.cpp, srtcore/sync.h
Minor fixes of implicit conversion from int64_t to double as reported by SonarCloud
=> [core] Minor fix of implicit conversion

srtcore/buffer.cpp, srtcore/buffer.h
Both Receiver and Sender buffers share the same logic of the moving average calculation of the buffer state (packets, bytes, timespan).
This PR moves this logic into a separate class, which is used as aggregation by both buffers.
Didn't use inheritance to avoid virtual tables.
Fixes #1272
=> [core] Shared moving average calc for RCV and SND buffers

test/test_list.cpp
Some minor changes, mainly adding additional chack on `CSndLossList::insert(..)`
Related to #1000
=> [tests] SndLossList: expect result from insert

apps/apputil.cpp, apps/apputil.hpp, apps/socketoptions.hpp, apps/srt-tunnel.cpp, apps/transmitmedia.cpp, testing/srt-test-live.cpp, testing/srt-test-mpbond.cpp, testing/testmedia.cpp
1. CreateAddrInet -> CreateAddr
2. Updated applications to use the new functions
3. Drop-in: added lacking ipv6only option handling in apps.
=> Replaced CreateAddrInet with CreateAddr that handles IPv6

docs/API-functions.md, docs/API.md, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/srt.h
Added source time extraction in SRT sender.
`SRT_MSGCTRL::srctime` represents the time since epoch in microseconds of the internally used steady clock.
It allows to pass the time from the receiver to the sender.
```c++
// Receive
SRT_MSGCTRL ctrl_rcv;
srt_recvmsg2(srt_sock_rcv, (char*) data, (int) len, &ctrl_rcv);
// Send
SRT_MSGCTRL ctrl_snd = srt_msgctrl_default;
// Take time from the source
ctrl_snd.srctime = ctrl_rcv.srctime;
srt_sendmsg2(srt_sock_snd, (char*) data, (int) len, &ctrl_snd);
```
Addresses #930
=> [core] Added source time check in sender

srtcore/core.cpp, srtcore/list.cpp, srtcore/list.h, test/test_list.cpp
It also has changes from `clang-format` applied on `list.h` (in a separate commit).
Fixes #1093
=> Renamed CSndLossList::remove to removeUpTo

docs/API-functions.md, srtcore/api.cpp, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/core.h, srtcore/srt.h, srtcore/srt_c_api.cpp, srtcore/sync.cpp, srtcore/udt.h
This PR adds SRT API functions to get SRT internal clock timestamp for the current time and SRT connection start time.
Both these functions can be used for SRT Source Time functionality.
List of changes:
Fixes #930
Closes #937
=> [core] Added SRT time API

.gitignore, test/test_sync.cpp
This is mostly a workaround to avoid CI failures. A proper fix is required further on.
Refers to #1321
=> Fixing spurious wake ups in sync unit tests

srtcore/srt.h
Using the void keyword in function declaration to fix the build
warning when enable libsrt in FFmpeg, the warning like"
in file included from libavformat/libsrt.c:24:
srt.h:736:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
736 | SRT_API       SRTSOCKET srt_create_socket();
| ^~~~~~~
srt.h:778:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
778 | SRT_API SRT_SOCKOPT_CONFIG* srt_create_config();
| ^~~~~~~
srt.h:941:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
941 | SRT_API uint32_t srt_getversion();
| ^~~~~~~
srt.h:943:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
943 | SRT_API int64_t srt_time_now();xs"
Signed-off-by: Jun Zhao <barryjzhao@tencent.com>
=> [core] using the void keyword in function declaration

CMakeLists.txt, scripts/haiUtil.cmake, scripts/maf.vim, srtcore/filelist.maf
Fixes #920
Changes:
1. Added support for conditional MAF.
Sections can be defined multiple times (can be merged) and condition can be added by adding ` - ` after the name, followed by an expression, currently possible as a variable, possibly with `!` at the end. The variable needs to "resolve to true" (the way how the interpreter defines it - in cmake case it's the reaction on `if()` condition), `!` inverts the condition.
2. Added conditionally C++11 sync and the windows resource file in MAF.
3. Removed old and obsolete `MafRead` function.
=> Added support for conditionals in MAF syntax

srtcore/epoll.cpp, srtcore/srt.h
Fixes #1405
Two bugfixes:
1. Subscription wasn't taking into account that some flags passed together with the others are always edge-triggered, while edge-triggered version for those that support both wasn't requested. This made an unwanted situation when an always-edge-triggered event was subscribed in level-trigger mode.
2. The operator & was defined incorrectly and actually it didn't do the job it was intended to do, instead caused a bug that resolved the flag & operation into a boolean, then interpreted as 1.
=> Fixed wrong definition of enum operator that lead to misinterpreting the result and mistaken edge update

apps/srt-live-transmit.cpp, apps/srt-tunnel.cpp, docs/bonding-intro.md, testing/srt-test-mpbond.cpp, testing/srt-test-multiplex.cpp
The function `CreateAddrInet` was replaced by `CreateAddr`.
The bonding intro document, as well as some comments in the code, still had those references.
Now fixed.
=> [docs] Replaced CreateAddrInet with CreateAddr

apps/socketoptions.hpp, docs/API.md, srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/core.h, srtcore/srt.h
Fixes #701
Improve periodic NAK handling by the sender.
Each unit of the sender buffer now has a retransmission timestamp. It allows tracking the time elapsed since the last retransmission of a certain packet. If a packet is retransmitted, the sender will not get ACK earlier than after 1xRTT from the retransmission time, therefore sender can ignore periodic NAK of those packet retransmissions that are still in flight.
=> [core] Added snd loss rexmit time check

srtcore/api.cpp, srtcore/api.h, srtcore/buffer.cpp, srtcore/cache.h, srtcore/core.cpp, srtcore/core.h, srtcore/epoll.cpp, srtcore/list.cpp, srtcore/packetfilter.cpp, srtcore/queue.cpp, srtcore/sync.h, srtcore/window.h
Addresses an item in #1103.
`CGuard` was used as a temporal solution to avoid too many merge conflicts with the bonding functionality.
Now most of that functionality is merged, so it is relatively safe to replace `CGuard` with the corresponding lock: `ScopedLock` or `UniqueLock`.
=> [core] Replaced CGuard with corresponding lock: UniqueLock or ScopedLock

docs/AccessControl.md
The first commit fixes document formatting.
The second commit adds the following changes:
- All single-letter key definitions are reserved for future use.
- Users can add their keys with `user_*` or `companyname_*` prefixes.
- Users are not allowed to extend existing values.
Addresses #1342
=> [docs] Access control guidelines: reserve single-character keys

testing/testmedia.cpp
The problem was that epoll-waiting for accept was done in the `PrepareListener` function, so installing a listener callback has been done AFTER the connecting socket came in, which was too late and ineffective. This also took out the superfluous twice printed "accepting" on verbose output.
=> [devel] Fixed epoll-waiting for accept to the right place - in `srt-test-live`

apps/srt-file-transmit.cpp, apps/srt-live-transmit.cpp, apps/transmitbase.hpp, apps/transmitmedia.cpp, apps/transmitmedia.hpp, docs/srt-live-transmit.md, testing/srt-test-live.cpp
Add source time passthrough to srt-live-transmit.
Note also #1350.
Be in sync with `srt-test-live` CLI changes in 59f617f304d3e292913ab9b1e7c170886a88ee35.
See previous implementation in [this branch](https://github.com/Haivision/srt/compare/master...maxsharabayko:feature/source-time-app).
=> [apps] Added source time to sample apps

apps/srt-live-transmit.cpp, docs/srt-live-transmit.md
Add buffering config command-line option to `srt-live-transmit`.
Fixes #1350
=> [apps] Added buffering command-line option to srt-live-transmit

srtcore/core.cpp
`CRcvLossList::remove()` is called in the `CUDT::tsbpd` thread, whereas the other `CRcvLossList` functions are performed in the `CRcvQueue::worker` thread.
As described in #1352:
`CRcvLossList::remove()` is called in the `CUDT::tsbpd` thread. While `remove(..)` modifies the list, `getFirstLostSeq(..)` is called from the `CRcvQueue::worker` thread. This could, while removing the last entry, result in `m_iLength` still being 1 but `m_iHead` being already -1 which would allow `m_caSeq[m_iHead]` to be accessed with a negative index.
This PR adds mutex protection to access `CRcvLossList::getFirstLostSeq(..)` and `CRcvLossList::getLossArray(..)`.
Fixes #1352
=> [core] Improved CRcvLossList protection from concurrent access

srtcore/core.cpp, srtcore/core.h
The comparison was always false because of `len >= 8` due to the check above: `if (len < SRT_CMD_HSREQ_MINSZ)`.
So it should actually be (3 + 1) times `uint32`.
=> [core] Fixed HS tbbpd flags check

apps/srt-tunnel.cpp
wrong addr length leads to build failed on Mac
=> [apps] use the correct length for bind

configure
add -h short option support as common practice.
Signed-off-by: Jun Zhao <barryjzhao@tencent.com>
=> [build] add -h short option support

srtcore/api.cpp
Problem: the sockets weren't removed from the roll list and could make the EID empty without noticing it. Two fixes:
1. Checking if all sockets from the list after applying a lock for group if they exist and are not broken. If not pass this test, remove them ALSO from the list of sockets to review. If this makes the container empty, the loop will interrupt at the next iteration.
2. Checking the return code from `srt_epoll_wait` call. It could have happened that it returns error in case when EID container is empty, which should be handled. No other error than that is predicted to happen; the error log is displayed in case when it would happen.
3. Removal from the EID container immediately when found out that the socket is broken so that this doesn't get probed again in this loop.
=> Fixed removing sockets from group members' rolled list after parallelly closed.

apps/socketoptions.hpp, docs/API.md, srtcore/core.cpp, srtcore/core.h, srtcore/srt.h
Renamed `SRTO_RETRANSMISSSION_ALGORITHM` to a shorter version: `SRTO_RETRANSMITALGO`.
The shortened version is more consistent with the names of other socket options.
We can safely rename it as this option was only added recently and will first appear in not yet release v1.5.0.
=> [core] Renamed SRTO_RETRANSMISSSION_ALGORITHM to SRTO_RETRANSMITALGO

apps/socketoptions.hpp, docs/API.md, srtcore/core.cpp, srtcore/core.h, srtcore/srt.h
The intent of the `SRTO_DRIFTTRACER` socket option is to provide a way to enable or disable the time drift tracing module.
Addresses #753 and #984.
=> Added SRTO_DRIFTTRACER socket option

srtcore/core.cpp
This provides two fixes:
1. When a data packet is coming in, the link turns IDLE -> RUNNING. Even if the packet is going to be effectively rejected. This is important because RUNNING links will not get updated the reception sequence when the buffer is empty. Updating this sequence while data packets were received was causing the "runaway train" effect, that is, while every incoming packet would come with increasing sequence, the synchronization was pushing the sequence forward in the meantime, which caused that incoming packets were seen as belated virtually forever.
2. Turning link to IDLE on sender state in case when keepalive has come and the link is outside the "temporary activation" state. The second condition prevents the link from being treated as IDLE in case when it was just …
=> Update group member status basing on packet type

apps/srt-tunnel.cpp
Hi, I found and fixed a problem about TCP ::connect failure for 'srt-tunnel' on macOS. The reason is that the size of 'sockaddr_any' may be incorrect when using '::connect'. 
I have tested the fix on macOS and CentOS, and it worked well.
=> [apps] Fixed TCP ::connect for macOS

.travis.yml
Build time is reduced by Ninja, but no that much.
* Linux Debug build with Ninja: 50 sec -> 35 sec.
* Linux Debug build with `-j$(nproc)`: 50 sec -> 34 sec.
* Overall Linux debug job with Ninja: 125 sec -> 107 sec.
The MinGW build takes 4 minutes in both cases, so the overall CI process is anyway blocked.
The build config file becomes more complicated.
Trying `make -j$(nproc)` instead.
=> [build] Reverted Ninja build from Travis.

srtcore/core.cpp, srtcore/core.h, srtcore/utilities.h
This fix make the stability criteria take into account the problems that arise while stopping transmission and prevents flipping instability that was seen too soon.
The new criteria make it clear that during the "temporary activation" time no check for the stability is being made, as well as the ACK last time is taken into account in order to clear the situation when the ACK hasn't yet come at all. Even though the ACK timer is initialized to "now" at the open time and also it's being updated beside the ACK reception in one place, it is considered that it's enough to state that ACK predates activation time to confirm that we are speaking about a stopped and restarted transmission (or not yet started after connection). If this is detected, the stability check will not be done at all.  This …
=> Fix the activation and stability check criteria

docs/bonding-intro.md
This is a minor change that changes the field name into the correct one.
=> Fixed after .status was renamed to .sockstate

srtcore/common.h, srtcore/list.cpp, srtcore/list.h, test/test_list.cpp
Work in progress.
Probably `CSndLossList::insert(..)` should return `-1` on failure, but then it needs to be properly handled in `CUDT`.
Related to #1000.
Suggestion by @ethouris 
> In file mode you just have to stop sending new packets, until retransmissions are successful enough and enough losses are covered
In live mode I don't think it's possible to live up to the live stream requirements with a large number of losses (or it's not a problem because sender drops would solve the problem earlier).
Meaning, if sender drops are working, this won't be a problem - or at least sender dropping could be enforced with a large number of drops. But we also have an option to turn sender drops completely off - in this case the only way to go is to close the connection.
=> [core] Fix CSndLossList::insert with negative offset

srtcore/core.cpp
Fixes #1469
The list is sorted alphabetically and some settable options are also added in comments to explain why they are not allowed as per-member socket option.
=> Completed the list of per-member socket options

apps/srt-tunnel.cpp, srtcore/api.cpp, srtcore/api.h, srtcore/channel.cpp, srtcore/core.cpp, srtcore/netinet_any.h, srtcore/queue.cpp, test/test_many_connections.cpp, testing/testmedia.cpp
Using `sockaddr_any::str()` instead of `SockaddrToString(sockaddr_any&)`.
To consider:
Printing the address of `sockaddr` or `sockaddr_storage` now can't be done implicitely.
=> [core] Using sockaddr_any::str()

srtcore/api.cpp, srtcore/api.h
1. Complete the error-sensitive data in the SOCKGROUPCONFIG structure. Report the early error in `errorcode` correctly.
2. Introduced translation for a single member connection. Now `srt_connect` call can be checked for early errors on a single connection.
=> Fixed error handling in group connect

srtcore/queue.cpp, testing/testmedia.cpp
1. The fix for the case when the connection process ended up in rejection, but it was running in background (async). In this case the SRT_REJ_TIMEOUT code was set forcefully, even though this execution path was due to a TTL timer reset to zero, which means that it wasn't an expired timeout, but forceful break due to rejection. The fix: for a case with zero TTL, the reject reason is set only in case when it wasn't set (unlikely, but just as a safety fallback), and in general it's believed that the correct rejection reason is set already.
2. A small fix in reporting the error by `srt-live-transmit`: as with introducing the forced error code (case of non-blocking mode connect), the `srt_getlasterror_str` call is also not correct. Instead the message for the possibly enforced error code …
=> Fixed bug: wrong reject reason on async connect

srtcore/channel.cpp
=> Fixed bug: check for IPv4 ONLY if BindToDevice is requested

srtcore/core.cpp
This adds a detection as to whether a member socket is in the broken state, before doing battle-test on it by trying to send a packet over it. Such a link is prematurely qualified as broken, just as if the operation was done on it and it failed.
=> Improved broken member link detection

apps/apputil.cpp
Added absolute time in CSV stats of `srt-live-transmit`.
The first column of CSV stats:
```
Timepoint
--
19.08.2020 09:40:10.619482 +0200
19.08.2020 09:40:10.724653 +0200
```
Example CLI:
```shell
./srt-live-transmit srt://:4200 udp://127.0.0.1:4201 -pf csv -statsout rcvstats.csv -s 100
```
Note: GCC before v5.0 is not supported.
Fixes #1218
=> [apps] Added absolute time in CSV stats of srt-live-transmit

srtcore/buffer.cpp, srtcore/buffer.h
1. Fixed: the actual sending time is available back after calling `sendmsg2`. If no source time supplied, this field will be written with the value of "origin time" (time when the packet was scheduled for sending). This way the next call in the group sender will pick up the time rewritten by the previous call and supply identical time for the same packet sent over a different link.
2. Formula fixed for `getSourceTime`: the `m_tsOriginTime` was actually reduced in this equation making false impression that this value participates in the equation.
=> Fixed bug: write back actual sending time if no source time supplied

scripts/generate-logging-defs.tcl, srtcore/srt.h
This improves the logging FA generation for `srt.h` file. Instead of generation a fragment, now the whole file is generated basing on existing contents, with only the interesting fragment with FA definitions replaced.
Also added "safe generation" - the generated is first temporary file, and then renamed to the target file, if there were no errors in the meantime.
=> Changed generation of the SRT header file FA section

srtcore/sync_posix.cpp
There is no `pthread_cancel()` on Android.
It was used in production build to terminate the thread if its handler is overwritten. This situation should not normally happen in SRT.
To work the missing `pthread_cancel()` around on Android the thread is just detached in the production build.
@fallenhaivision Could you please check this fix as well?
=> [core] A workaround for pthread_cancel on Android

docs/API.md, docs/srt-live-transmit.md
Added a table with socket options available in URI query of `srt-live-transmit` to `srt-live-transmit.md`.
There is also a separate commit that fixes header levels and formatting of the document.
Fixes #1402.
=> [docs] Add a full list of URI socket options in srt-live-transmit.md

test/test_many_connections.cpp, test/test_sync.cpp
Fixes #1321 
1. Decreased the number of simultaneously created connection to be quickly failed to 100. Not every platform withstood 200 and this was also the reason of test failures in CI.
2. The WaitForTwoNotifyOne test has been redesigned. The general idea is that:
* We start two threads, that is "clients".
* We expect them both to timeout in a short time, as we didn't signal them.
* Then, we apply `notify_one` on the CV on which they are both waiting.
* The thread that got the notification first, does a simulated "resource requisition", that is, it adds a value to the vector with its id. Then sets the resource availability flag to false in order to avoid a spuriously woken up thread to get advantage of it.
* The thread that reports the "ready" status is expected to also have added its …
=> Added fixes for failing tests

.travis.yml, test/filelist.maf, test/test_muxer.cpp
This is a refactored test provided in #1499 by @rexvl 
The test creates two listening SRT sockets bound to IPv4 and IPv6 local IPs with the same port number.
Travis Trusty does not support IPv6.
- [Travis Issue 8891](https://github.com/travis-ci/travis-ci/issues/8891)
- [Travis IPv6 Tests](https://github.com/njh/travis-ipv6-test)
=> [tests] CMuxer behavior with IPv4 and IPv6 listeners bound to the same port

apps/srt-tunnel.cpp, srtcore/netinet_any.h, testing/testmedia.cpp
This adds a possibility to easily specify the forwarder for the `len` field in `sockaddr_any` usable with system functions.
The SRT API is using `int` type for length of the address specified by `sockaddr*`, whereas system functions use `socklen_t` on Linux (which resolves to various combinations) or `int` on Windows. To satisfy normal needs, the `len` field is of `int` type, but this way it can't be passed to system functions by pointer.
This makes it possible to pass a pointer to a system length type, as the system function require, and transparently bind it to the `len` field.
=> Added length type wrapper in sockaddr_any for convenience.

testing/srt-test-live.cpp, testing/testmedia.cpp
1. Fixed "uri smuggling" from the node settings to the overall group URI and "recovering" before URI parsing for given node.
The idea for "URI smuggling" was that all `&` characters that separate the URI parameters are changed into `?`, then the list of nodes is joined with comma and set as `nodes` parameter in the group URI. The problem was that the `?` wasn't turned back to `&` after unpacking the "smuggled" URI and it was incorrectly interpreted later.
2. Fixed lacking `source` parameter specified address to `srt_prepare_endpoint`.
The `source` parameter after being correctly extracted from the "smuggled" node URI wasn't passed at all to `srt_prepare_endpoint`. After the fix it has been tested that the `srt_connect_group` function does effectively call `srt_bind` on the socket with the …
=> [apps] Test app fixed group parameter handling

docs/srt-live-transmit.md
The option was missing in the `srt-live-transmit.md` document as it was added not so long ago.
=> [docs] Added URI query option drifttracer

docs/API-functions.md, srtcore/api.cpp, srtcore/core.cpp, srtcore/group.cpp, srtcore/group.h
Things found during the review:
1. Synchronization group data with the socket data at the caller side:
* wrong reaction on isn == 0 (0 is a perfectly legal sequence value), which likely was remaining after the fact that a freshly created group has recorded scheduling sequence undefined
* the right "undefined sequence" value is -1, but this no longer makes sense because the group is now always initialized the schedule sequence number due to another bugfix
* the intention was to synchronize the latency value for the group from the value taken from the first socket in case when the group didn't get this information yet. The condition to do it was then changed to simply checking if the group is empty. Also the synchronization done at the caller side has been changed to not perform the …
=> Fixed some problems in group code found during review

srtcore/core.cpp, srtcore/group.cpp, srtcore/group.h, srtcore/queue.cpp, testing/testmedia.cpp, testing/testmedia.hpp
Also fixed the group-connection procedure in`srt-test-live` application in order to:
1. Wait for async connection, if non-blocking mode was set
2. Get the success or failure statement from the waiting function
3. Delete the configuration only when the link table is destroyed (immediate destruction would crash async connection).
=> [BUG] Fixed: if all group connection failed, E epoll event should be set on the group

docs/API.md, docs/APISocketOptions.md
In response to [PR#1378](https://github.com/Haivision/srt/issues/1378), I have removed the socket options sections from API.md, and incorporated them in the new document APISocketOptions.md. Both files have been edited and require technical review.
=> Added modified API.md and new APISocketOptions.md

testing/testmedia.cpp, testing/testmedia.hpp
This splits the `Connection` into a part that should contain copyable data and the part the contains only the real object state and pointed permanent object that should be uniquely pointed. For the right object, the move-only copying is the only allowed.
=> [devel] Fixed crash by having destructor but not copy rules in srt-test-live

docs/API-functions.md, srtcore/group.cpp, srtcore/srt.h
This adds the `weight` value to the `SRT_GROUPDATA` structure and retrieval of this value from the internal member data.
As on the caller side it shouldn't be a problem because the weight is set by the caller requester and the application should have this value in its connection table, on the listener side there's no way otherwise to know this value, as the listener keeps such connections that are reporting in, together with their settings decided at caller side.
=> [FR] Added retrieving weight setting in group data

srtcore/core.cpp, srtcore/group.cpp, srtcore/queue.cpp
This fix sandwitches new blocking functions between THREAD_PAUSED/THREAD_RESUMED macros for application specific thread watchdog.
The application sets the SRT THREAD_XXX() macros to implement a thread watchdog. new blocking functions were added in the development toward 1.5.0 causing the thread watchdog to detect stalled threads that were legitimately blocked on event or timer and not gone wild in an infinite loop or slow callback.
By default the THREAD_XXX() macros are not defined so unless added in a multi-lines if or loop construction with no braces they can do no harm to most applications.
=> Fix application specific thread watchdog

docs/APISocketOptions.md, srtcore/core.cpp
These changes are extracted from #1383.
Socket options `SRTO_INPUTBW` and `SRTO_OHEADBW` are made readable via `srt_getsockopt(..)` and `srt_getsockflag(..)`.
=> [core] Made SRTO_INPUTBW and SRTO_OHEADBW readable

test/test_enforced_encryption.cpp
The following changes have been applied:
1. Use `srt_epoll_uwait` for epoll-waiting, as this function reports in more comfortable way and doesn't require complicated checking rules. The result is an array of ready sockets together with events on which it is ready.
2. As only the accepted socket is checked for readiness, epoll is subscribed only for listener socket, for IN and ERR. The latter should never be a case, but the subscription remains in order to catch that case should it occur.
3. changed the rules of checking in tests B2-B4. Actually in this test the state on the listener side is a matter of good luck, although the stable rules mandate that it should either result in no connection reporting, or if the connection was reported it should report as broken just after the connecting …
=> Refax of TestEnforcedEncryption to keep on the stable results

srtcore/core.cpp, srtcore/core.h, srtcore/srt.h
These changes are extracted from #1383.
Added readonly `SRTO_ESTINPUTBW` socket option available via `srt_getsockopt(..)` and `srt_getsockflag(..)`.
=> [core] Added SRTO_ESTINPUTBW option to get estimated input bitrate

srtcore/api.cpp, srtcore/api.h, srtcore/group.cpp, srtcore/group.h, testing/testmedia.cpp
Fixes #1506
Changes:
Removal from group of a socket is given a separate parameter that confirms that it was so because the socket was broken. If so, additionally the group will be set the UPDATE event.
Applications: changed the code for non-blocking mode case that tests also the case for the UPDATE event.
=> Added UPDATE event raised when a member connection broken

srtcore/group.cpp, srtcore/group.h
Fixed problem: in sending function for backup and broadcast there was a "manual" procedure to fill group data, different than the one used in receiving. Updates after introducing new fields were not added. This adds a common procedure for copying the data from internal member structure to the user group data, to be called in every case.
=> [BUG] Filling group data now done by a common procedure

srtcore/core.cpp, srtcore/srt.h
The socket option was introduced in PR #1537 recently to allow getting the estimated input bitrate value.
However, it should not be a socket option, but more a statistics entry.
Furthermore, there is already the [mbpsMaxBW](https://github.com/Haivision/srt/blob/master/docs/statistics.md#mbpsMaxBW) statistic that depicts the estimated input bitrate value (when the corresponding mode is used `SRTO_INPUTBW=0` and `SRTO_MAXBW=0`) as estimated value multiplied by (100% + `SRT_OHEADBW`).
Therefore removing the option.
=> [core] Removed SRTO_ESTINPUTBW

CMakeLists.txt, srtcore/channel.cpp, srtcore/fec.cpp
The changes introduced in PR #1465 might require more feedback regarding building on different platforms.
This PR adds the `ENABLE_SOCK_CLOEXEC` to allow to use the proposed changes, and at the same time to allow to disable the usage if a platform has issues using the `SOCK_CLOEXEC` or related flags (`FD_CLOEXEC`, `FIOCLEX`).
Enabled by default.
- Enabled the `ENABLE_SOCK_CLOEXEC` build option by default.
- Changed the `set_cloexec` definition to fix the build warning (fixes #1532).
- Fixed build warning regarding the unused `CellMark` function.
=> [build] Added ENABLE_SOCK_CLOEXEC build option enabled by default

apps/srt-live-transmit.cpp, srtcore/api.cpp
Fixes issue #1568.
srt-live-transmit tries to process the same socket twice.
This PR is a bit hacky. It removes a socket ID that is to be processed from the array to process.
- Also changed the IPE message
=> [apps] Fixed stransmit processing a socket twice

docs/API-functions.md, docs/APISocketOptions.md
Fixed the 'since v1.5.0' field in the docs to 'since v1.4.2' for non-group API changes.
The following socket options are to be added in 1.4.2 instead of 1.5.0:
- `SRTO_DRIFTTRACER`
- `SRTO_RETRANSMITALGO`
- `SRTO_BINDTODEVICE`
Group-related options remain for v.1.5.0.
Fixes #1515
=> [docs] Fixed the 'since v1.5.0' field in the docs

srtcore/group.cpp, srtcore/group.h, testing/srt-test-live.cpp
Main problem:
The problem was in the procedure that needed to make sure there are any links that could be used for sending a packet, in case when it wasn't sent over any stable links. The procedure was checking the links wrong way and was effectively waiting for another link to become ready to write except links that are running currently. In a situation when one and the only running link was considered unstable, it was effectively trying to find and activate another link and WAIT FOR IT by `swait` call until any was found, hence the hangup on the call to `srt_sendmsg2`.
Things fixed additionally:
1. The group characteristic data are also extracted in case when the function could end up with "again", as the group information is required in this case as well, and also it was lacking for a …
=> [BUG] Fixed: all-unstable situation responded with wait-for-ready link caused a hangup

apps/logsupport.cpp
Resolve the following compilation error on Windows 10 with VS 14 2015 :
`'back_inserter': identifier not found`
=> Add #include <iterator> to compile on Windows VS 14 2015

README.md
Just a quick fix on the readme of a href-typo stumbled upon
=> Readme: Fix cookbook link pointing to threads chapter instead of index page

docs/API-functions.md
`INVALID_SOCKET` is not part of the C API.
=> docs: INVALID_SOCKET -> SRT_INVALID_SOCK

srtcore/core.cpp, testing/testmedia.cpp
Fixes #1577 
Changes:
1. Fixed lacking check in the HSRSP parsing (caller side) that didn't check the incoming peer version against the set up minimum version. Also fixing the rejection code that was unnecessarily overridden when it was set elsewhere already.
2. Fixed option fields derivation when deriving options from listener to the accepted socket - minversion wasn't derived and therefore the `minversion` option was ineffective on a listener
3. Added extra parsing possibility for the `minversion` option in the testing application so that it can also interpret a usual version string specification.
=> [BUG] Fixed: SRTO_MINVERSION didn't cause rejection on too old version

srtcore/platform_sys.h
This fixes SRT build for BSD targets. Tested with FreeBSD, TrueOS, and OpenBSD.
=> Fix BSD builds.

apps/srt-tunnel.cpp, srtcore/cache.cpp, srtcore/cache.h, srtcore/common.h, srtcore/core.cpp, srtcore/group.h, srtcore/packetfilter.h
Fixes #1447 
This PR currently prepares the solution, but it must be also tested:
1. Single socket transmission with restarting transmission (use `srt-live-transmit` for testing)
2. For Backup groups, with transmission stopped and restarted over a running connection. One link suffices.
3. srt-tunnel with connection established and broken several times
=> Fixed reports from LGTM

docs/APISocketOptions.md
This PR improves the description of latency related SRT socket options:
- `SRTO_LATENCY`
- `SRTO_RCVLATENCY`
- `SRT_PEERLATENCY`
It also fixes some minor mistakes in the APISocketOptions.md.
- Some occurrences of "msec" is renamed to "ms".
- "8192 buffs" is changed to "8192 payloads (`SRTO_RCVBUF`, `SRTO_SNDBUF`, `SRTO_UDP_RCVBUF`).
- Added missing "Return to list" hyperlink to the `SRTO_CONGESTION` section.
- Fixed list formatting in the `SRTO_MAXBW` section.
Closes #1210
=> [docs] Improved latency description in APISocketOptions

srtcore/buffer.cpp, srtcore/common.h, srtcore/core.cpp, srtcore/core.h, srtcore/list.cpp, test/test_seqno.cpp
In short, SRT sender may hang up under certain conditions if the receiver does not send loss reports periodically.
It means the receiver is either SRT version prior to v1.3.0 (didn’t have PeriodicNAK) or disables Periodic NAK explicitly (SRTO_NAKREPORTS option).
The issue found by @CommonsNat in #1000 was introduced in PR #1181 (Mar 17, 2020) with the new `getFlightSpan()` utility function. The function was later modified in #1190.
Only SRT v1.4.2 is affected by the bug which this PR fixes.
The lowest value returned by the `getFlightSpan()` was `1`, while `0` is expected if there are no packets in flight.
The fixed version:
```c++
/// Returns the number of packets in flight (sent, but not yet acknowledged).
/// @returns The number of packets in flight belonging to the interval [0; ...) …
```
=> [core] Fixed getFlighSpan function and rexmit bug

srtcore/api.cpp
Fixes #1608 
The `removeFromGroup` could be called in the meantime or somewhere from inside `connectIn` call, possibly also in the receiver worker thread as a reaction on connection timeout. The call that has caused a crash was in the exception handler, which stated that the `m_IncludedGroup` field is still valid as set before. To prevent things like this from happening, this function now rewrites the `m_IncludedGroup` and reads it under protection. The following call to `CUDTGroup::remove` is also protected by a group mutex and can be called multiple times (the call on an already removed socket is ignored).
=> Added mutex protection and null check for removeFromGroup

docs/APISocketOptions.md, srtcore/core.cpp
The `SRTO_RETRANSMITALGO` was previously only writable, but not readable.
However, it is worth making it readable as well to verify that the setting was applied, especially on the accepted socket (inheriting from listener socket).
Updated the docs.
=> [core] SRTO_RETRANSMITALGO becomes readable

apps/srt-tunnel.cpp, test/test_sync.cpp
The test confirms that `CThread` instance:
1. is joinable even after the thread has finished its execution;
2. is no longer joinable after `join()` was done.
Comes together with this PR:
- Added missing `override` statement in `srt-tunnel`. Was generating a warning. Overrides `Medium::CloseInternal()`.
=> [tests] Added CThread::joinable() unit test

.appveyor.yml
To reduce build times applications were only built for VS 2019 Release in AppVeyor. See PR #1346.
However, regardless of build times, CI is needed to verify that nothing is broken both in the library and in sample applications to avoid, e.g. #1587 build failures.
Therefore this PR enables building application for VS 2019 Release and VS 2015 Release and VS 2013 Release.
Unit tests are enabled for VS 2019 Release and VS 2015 Release.
=> AppVeyor: Build applications not only in VS 2019 configuration

srtcore/api.h, srtcore/core.cpp, srtcore/epoll.cpp
Three issues are fixed in this PR.
It is likely that there are no system sockets signaled in the event, which makes `ed.m_sLocals` empty.
Then the following becomes a declaration of a zero-length array
```c++
const int max_events = ed.m_sLocals.size();
struct kevent ke[max_events];
```
This PR adds a check for an empty `ed.m_sLocals`.
There was a right shift operation that was dropping bits due to the insufficient size of the `int32_t` type.
Initialization was missing from the constructor.
=> [core] Fixed undefined zero length array in epoll

srtcore/core.cpp, srtcore/core.h
This is a rework of #1620. Fixes #1622.
Closes #1606. Closes #1620.
1. `CUDT::m_RecvDataLock` is removed, as it was wrongfully used together with `CUDT::m_RecvDataCond` in some places. `CUDT::m_RecvDataCond` is assumed to be used with `CUDT::m_RecvLock`.
2. Added `CUDT::m_RcvTsbPdStartupLock` to prevent a race in creating and joining the TSBPD thread from different threads.
Reusing any of the existing mutexes complicates the code, unfortunately.
=> Fixed race starting and joining TSBPD thread

srtcore/core.cpp, srtcore/core.h, srtcore/sync.h, srtcore/sync_posix.cpp, test/test_sync.cpp
As a part of the #1610 the ACK sending code was moved to a dedicated function `CUDT::sendCtrlAck(..)`.
The body of the function has no changes except for `break` statements that are replaced by `return`.
=> [core] Moved ACK sending to CUDT::sendCtrlAck

docs/APISocketOptions.md
- Fixed heading formatting.
- Removed redundant bullets.
- Removed extra blank lines and trailing spaces.
- Fixed table of contents.
- **No content changes!**
=> [docs] Formatting of APISocketOptions.md

apps/apputil.cpp, srtcore/common.cpp, srtcore/crypto.cpp, srtcore/crypto.h, testing/srt-test-live.cpp, testing/srt-test-mpbond.cpp, testing/testmedia.cpp, testing/testmediabase.hpp
Changes summary:
1. Fixes for compiling with ENABLE_LOGGING=OFF that got a build break (some may additionally follow in the application files):
* srtcore/common.cpp
* srtcore/crypto.cpp
* srtcore/crypto.h
2. Small bugfixes and improvements in the test application, mainly connected with ability to test with unusual scenarios:
* apps/apputil.cpp  -- Bugfix for correct handling -1 numbers in option arguments
* testing/srt-test-live.cpp  -- Added retry option
* testing/srt-test-mpbond.cpp  -- Fixed build break when logging is on
* testing/testmedia.cpp -- Fix for proper handling async group connection; handler for retry
=> [test] Test apps improvements + build break fixes with logging off

apps/apputil.cpp
Fixes #1618.
New format:
```
2020-11-06T13:11:13.532194+0100
```
Old format:
```
06.11.2020 13:11:13.532194 +0200
```
Checked Python parsing:
```python
df = pd.read_csv("./gen-snd.csv")
df['Timepoint']= pd.to_datetime(df['Timepoint'])
print(type(df.Timepoint[0]))
print(df.Timepoint[0])
print(df.Timepoint[1])
print(df.Timepoint[1] > df.Timepoint[0])
```
Output:
```shell
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
2020-11-06 13:11:02.522656+01:00
2020-11-06 13:11:03.522864+01:00
True
```
=> [apps] CSV stats timepoint now follows ISO 8601 format

README.md
Code coverage is also visualized in [SonarCloud](https://sonarcloud.io/dashboard?id=srt).
But codecov provides a more convenient view. Plus it checks external PRs.
=> [docs] Added codecov badge

apps/srt-live-transmit.cpp, docs/srt-live-transmit.md
If a functional area or several areas are provided, the list has to be reset before adding those FAs.
=> [apps] Fixed logfa handling in srt-live-transmit

srtcore/common.h, srtcore/core.cpp
Fixes #1665 
1. Changed the construction of EventVariant.
This likely wasn't exactly understood as intended by the compiler and some weird copying rules were likely used, which resulted to stack override. Instead a simpler and more straightforward form was provided: construct by explicit constructor and explicit call to EventVariant was therefore needed at the call to `updateCC`.
2. Fix in `processSrtMsg` - missing the function call protocol
The protocol mandates that this function return `true` if the message was understood and `false` if not, while no matter if it encountered an error or succeeded, it should return true, just do no response call, or respond with error, depending on a situation. In case of failed KMREQ message it was simply returning false, which was wrong behavior.
=> [BUG] Fixed wrong reaction on failure KMREQ and unsafe construction of EventVariant

.codecov.yml, .travis.yml
Master build fail on uploading test coverage report to `codecov`, while PRs succeed.
The only difference is that PRs do not execute sonarcloud scan.
This P changes the order of codecov upload and sonarcloud scanning in case sonar scanner deletes reports.
=> [build] Run codecov before sonar-scanner

srtcore/api.cpp, srtcore/common.cpp, srtcore/common.h, srtcore/core.cpp, test/filelist.maf, test/test_common.cpp
While converting IPv4 mapped to IPv6 there was an error in the IPv4 index.
Fixes #1663 
Added unit test for the case.
=> Fixed IPv4 to IPv6 mapping in CIPAddress::pton(..)

srtcore/core.cpp
Fixes #1662 
The problem is that the check for empty Receiver Loss List was done without locking, so potentially the loss list could be purged between the check and getting the contents. This way the getFirstLoss function might potentially return SRT_SEQNO_NONE (-1) and then take this value further down the processing path without checking.
=> [BUG] Data race when TLPKTDROP while checking loss for ACK candidate

srtcore/api.cpp, srtcore/congctl.cpp, srtcore/core.cpp, test/test_listen_callback.cpp
- C4101 - local variable never used (2).
- C4129- 'character' : unrecognized character escape sequence (1).
- C4305 - truncation from 'type1' to 'type2' (1).
Related to #1646
=> [core] Fixed some compiler warnings.

srtcore/core.cpp
The value of ACK is taken as a good deal, while it might potentially be a value out of allowed range for sequence numbers. It should be checked first if it isn't out of the range, and only then operations could be performed on it.
Fixes #1662
=> [core] Fix: check incoming ACK value in case of a rogue peer

docs/Android/Compiling.md, docs/Android/mkall, docs/Android/mksrt, docs/Android/mkssl, docs/Android/packjni, docs/Android/prepare_build
Now builds .so files into jniLibs/[target-architecture] folders.
Updated instructions in case the issues that I faced are experienced. specifically using ndk-19 and latest cmake seemed to work for me.
=> [docs] Fixing the android build script

srtcore/common.h, srtcore/core.cpp
Fixes 19 warnings C4275 - DLL-interface class 'class_1' used as base for DLL-interface class 'class_2'.
See #1646
In particular,
> Warning	C4275	non dll-interface class 'std::exception' used as base for dll-interface class 'CUDTException'	srt_virtual	srtcore\common.h	98
=>  [core] CUDTException is no longer exported in DLL

srtcore/api.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/queue.cpp, srtcore/queue.h, srtcore/sync.h, test/test_enforced_encryption.cpp
The problem:
There was detected a deadlock and therefore the `synchro` parameter introduced, which passes down the call with a requirement to not lock the mutex, while it was causing a deadlock.
After a deep mutex analysis it turned out that the deadlock was actually caused by a mutex lock ordering violation, which has started from the `CRendezvousQueue::updateConnStatus`, which is called whole under a lock for `m_RIDVectorLock`. The extra update calls introduced for HSv5 required extra locking, which was in lock ordering violation against this mutex. The problem has been solved by collecting all sockets, that need to be updated in this function by these lockable calls, in a separate container, and then call the updates outside of the lock.
=> [core] Moved post-hs-update locking code out of mutex; untangled lock order around RIDVector

srtcore/buffer.h, srtcore/core.cpp
_A work within #1674 to reduce changes when integrating the new receiver buffer._
=> [core] A change in setupCC to access CUnitQueue via CRcvQueue instead of CRcvBuffer

srtcore/core.cpp
The proposed message format:
```shell
W:SRT.br: RCV-DROPPED 1 packet(s), packet seqno %625560260 delayed for 0.707 ms
```
instead of
```shell
W:SRT.br: RCV-DROPPED packet delay=0ms
```
Fixed fractional part formatting in the heavy log.
Fixes #1659.
=> [core] Improved RCV-DROPPED log message

srtcore/group.cpp, srtcore/group.h
The problem: CheckValidSockets called CUDTGroup::remove (locked version) for a socket that it couldn't find in the global container. This, however, might cause that a socket already moved to ClosedSockets will be left with a dangling iterator to the group container entry.
=> [core] CheckValidSockets no longer remove sockets from group, this was causing inconsistency.

srtcore/core.cpp
The problem:
Write-readiness was set before the group state was upgraded from PENDING to IDLE. This brought a risk that the connecting function could exit before this state is changed and also the sending function might start the operation, catching all links PENDING, which resulted in error, even though the links are connected and the sending operation should at least try to send.
=> [core] Fixed order of group member state change before write ready

srtcore/common.h, srtcore/core.cpp
1. Incorrect definition of RollNumber's operator==. This didn't make any real problem as neither = nor == were used in the code, but the definition was wrong.
2. Fixed wrong usage of temporary string object when setting thread name.
=> [core] Fixed formal problems detected by clang

.appveyor.yml, .github/workflows/cxx11-macos.yaml, .github/workflows/cxx11-ubuntu.yaml, .github/workflows/cxx11-win.yaml, .travis.yml, CMakeLists.txt, test/filelist.maf, test/test_enforced_encryption.cpp, test/test_epoll.cpp, test/test_ipv6.cpp
Extracted from #1664 due to CI failures on IPv6 tests. More time is required to configure CI tests for it.
IPv6 tests failing on AppVeyor due to platform-specific reasons:
- `TestIPv6.v6_calls_v4`
Travis Linux
- `TestIPv6.v6_calls_v6_mapped`
- `TestIPv6.v6_calls_v6`
=> [tests] Check IPv6 connection and socket address

srtcore/buffer.cpp, srtcore/channel.cpp, srtcore/common.cpp, srtcore/common.h, srtcore/core.cpp, srtcore/core.h, srtcore/crypto.cpp, srtcore/packet.h, srtcore/utilities.h
Gradually fixing compiler warnings listed in #1646 
This PR fixes some of the C4267 warnings: 'var' conversion from 'size_t' to 'type' possible loss of data.
Roughly -70 C4267 warnings
=> [core] Minor compiler warning fixes (conversion loss of data)

apps/transmitmedia.cpp
`srt-live-transmit` now shows a warning message if there is no host provided for UDP target.
Although it is a valid URI, it could be a good hint if there was an intent to actually send to some remote IP instead.
Addresses #1656 
Example output:
```shell
./srt-live-transmit srt://:4200 udp://:4201
Media path: 'srt://:4200' --> 'udp://:4201'
WARN Host for UDP target is not provided. Will send to localhost:4201.
```
=> [apps] Show warning if UDP target is without host

docs/API.md
Changes:
1. General formatting of API.md (1st commit)
2. Removed a note regarding IPv6 usage (2nd commit):
> Please note that the use of SRT with `AF_INET6` has not been fully tested; 
use at your own risk.
Addresses #691.
=> [docs] Removed a warning regarding IPv6 usage

test/test_connection_timeout.cpp
The fix is just by putting the creation and closing of the socket actions inside the loop - so that the socket, after getting connection failure is not reused.
=> [test] Fixed connection timeout test to not reuse broken socket

srtcore/core.cpp, srtcore/core.h, srtcore/group.cpp, srtcore/group.h
- Renamed `m_tsTmpActiveTime` to `m_tsTmpActiveSince`;
- Minor refactoring of `CUDTGroup::sendBackup_CheckIdleTime(..)` to improve readability.
=> [core] Minor refactoring of CheckRunningStability

srtcore/core.cpp, srtcore/sync.h
`CSync::wait_until` is now mapped to `CV::wait_until` instead of `wait_for`.
When C++11 sync is enabled, it will reduce the number of time conversions.
- C++11 sync (Windows -> Windows localhost): effective latency **[120ms; 135ms]**
- POSIX sync (Windows -> Windows localhost:) effective latency **[120ms; 136ms]**
_A work within #1674 to reduce changes when integrating the new receiver buffer._
=> [core] CSync::wait_until is now mapped to CV::wait_until

srtcore/api.cpp, srtcore/api.h, srtcore/core.cpp, srtcore/group.cpp, srtcore/group.h
This changes the field `m_IncludedIter` so that it contains the pointer to the member data, instead of the iterator in the list that holds it. Due to that the "NULL iterator" implemented by an empty static list can be also replaced by NULL.
This involves also renaming the group pointer and group member data pointer to `m_GroupOf` and `m_GroupMemberData` resp.
=> [core] Refactored member pointer: now raw pointer to socket data

srtcore/fec.cpp, srtcore/fec.h, srtcore/packetfilter.cpp, srtcore/packetfilter_api.h, test/test_fec_rebuilding.cpp
Involved PRs (need to be retested):
* #1594 
* #894 
General description:
The procedures concerning extreme conditions, like lots of lost packets in a row, resulting in a necessity of removal of some existing parts. There were two general false presumptions:
* At least 2 series of matrices were supposed to exist. In result the removal of one series were presuming that there exist always the next series. The problem is that the groups for incoming packets are created dynamically, as packets come in, while with a lots of packets lost in a row this could result in having lots of packet sequence range not covered by existing FEC groups. For example: the distance between the group base and the incoming packet is 10x the matrix size, however the previously received packet was from series 2. …
=> [core] Fixed miscalculations on extreme loss conditions in FEC

srtcore/sync_posix.cpp
Fixes #915 
Changes in POSIX version of thread local error storage:
1. The `CThreadError` constructor now allocates the first object, that is, allocates the object for the thread that has run the initialization of the global objects in SRT (most likely main application thread, which will be most likely used to report errors). This version runs without exception protection, but it is believed that it is acceptable if a memory allocation error crashes the application here.
2. The memory allocation if requested in another there, where it wasn't preallocated with the global variable, will be allocated without throwing an exception. NULL will be accepted.
3. The NULL is now allowed to be returned by `get()` and if so, a fallback object that defines the error as memory allocation will be used. …
=> [core] Fixes potential exception slipup on memory allocation error

srtcore/api.cpp, srtcore/buffer.cpp, srtcore/core.cpp, srtcore/fec.cpp, srtcore/packet.cpp, srtcore/packet.h, srtcore/queue.cpp, srtcore/queue.h, srtcore/window.h
Another small portion of minor warnings fixes (C4267): conversion from 'size_t' to 'type' with possible loss of data.
Addresses #1646
=> [core] Minor warnings fixes (C4267): type conversion with possible loss of data

srtcore/srt.h
Add missing SRT_API marker to the function's declaration. Fixes
undefined reference when linking to libsrt on Windows.
=> [core] fix dllexport of srt_rejectreason_str()

.travis.yml
SonarCloud complains about an outdated Java RT used.
- [Building Java 11+ projects on Travis CI](https://www.deps.co/guides/travis-ci-latest-java/)
- [Building a Java project](https://docs.travis-ci.com/user/languages/java/)
=> [build] Use Java 11 in Travis

srtcore/group.cpp, srtcore/group.h
This PR contains a minor refactoring around a backup link activation in `CUDTGroup::sendBackup(..)`:
1. Introduced function `CUDTGroup::sendBackup_IsActivationNeeded(..)` to hold a logic of whether backup link activation is needed. This also reduces the size of an overgrown `sendBackup` function.
2. `CUDTGroup::sendBackup_CheckNeedActivate(..)` renamed to `sendBackup_TryActivateIdleLink(..)`.
=> [core] Refactoring backup link activation

srtcore/api.cpp
In listener mode, open the socket created for a connecting caller only after its accept hook has been run. This gives the hook an opportunity to set some 'pre' options (like SRTO_RCVBUF) on the socket before it gets passed to srt_accept().
=> [core] Run the accept hook before opening caller's socket

CMakeLists.txt
Fixes #1592 
The first versioned link for the *.so file is now with major and minor version.
=> [build] Made SRT versioned SO named with major and minor

srtcore/group.cpp, srtcore/group.h
Reducing the size of the `sendBackup(..)` function. Moving the code that qualifies member link states to a separate function.
Behavior is not changed.
=> [core] Main-backup: added QualifyMemberStates function

srtcore/list.cpp, test/test_list.cpp
In runtime, the maximum number of sequence numbers that may be considered lost is limited by the flight span (limited by flow window).
The actual number of items in the sender's loss list may **probably** be a bit more in the case when sending moved forward, but not all sequences previously reported as lost were retransmitted. Still, most of the operations ensure the loss list is properly updated. For example, `CUDT::checkNeedDrop` also removes dropped sequence numbers, and `m_iSndLastAck` ensures old numbers are not added to the list when processing a NAK report.
Anyway, the size of the loss list is set to twice the size of the flow window just in case there would be more elements to store.
`m_pSndLossList = new CSndLossList(m_iFlowWindowSize * 2);` - …
=> [core] CSndLossList limits the maximum offset

srtcore/api.cpp, srtcore/api.h
Fixes #1734 
The `m_pAcceptSocket` field seems to not be used for anything. Sockets were added to it and removed from it under some circumstances, but that's about all.
Refax: Also the `m_pQueuedSockets` field has been turned into `m_QueuedSockets` and turned into a solid object instead of pointer. There has never been any reason to make this object dynamically allocated and deallocated and it has only increased entropy.
=> [core][MAINT] Removed unused and swelling m_pAcceptSockets field + refax

test/test_list.cpp
- Enabled a previously disabled test: now passes.
- Added `TEST_F(CSndLossListTest, InsertPositiveOffsetTooFar)`
Addresses #1000
=> [tests] Enabled some CSndLossList::insert tests

scripts/build-windows.ps1
CMake complaints about CMake version 2.8.8 requirement of GTest.
Versions below 2.8.12 will soon become deprecated.
Extracted from #1731
=> [build] Fixed PowerShell script to not fail on CMake warning.

srtcore/group.cpp, srtcore/group.h
List of changes:
- `vector<gli_t> idlers` -> `idleLinks`
- `vector<SRTSOCKET> pending` -> `pendingSockets`
- `vector<gli_t> sendable` -> `activeLinks`
- `vector<Sendstate> sendstates` not used in the backup mode, removed.
- `vector<gli_t> unstable` - `unstableLinks`
- `uint16_t max_sendable_weight` -> `maxActiveWeight`
=> [core] Main-backup: renaming member link arrays

examples/test-c-client-bonding.c, examples/test-c-server-bonding.c
This adds a possibility of using non-blocking mode in bonding examples, when last argument is `n`.
=> [MAINT] Added non-blocking option for bonding examples

CMakeLists.txt, examples/example-client-nonblock.c
Pretty straightforward as `srt_cleanup()` is better to be called on every return.
=> [apps] Created an example for non-blocking client

srtcore/core.cpp
Socket ID is needed to distinguish a socket that reports packet drop.
=> [core] Added socket ID to RCV-DROP log message
