Haivision/srt

.appveyor.yml, CMakeLists.txt
This adds a CI script for windows. [It's already working](https://ci.appveyor.com/project/GuapoTaco/srt/build/1.0.12), you'll just have to login to Appveyor and enable it for this repository. It's free for open source repositories like this one.
=> Add Appveyor CI for windows

.travis.yml, CMakeLists.txt
The CI has failed since #35 has been merged, this should fix it.
=> Fix CI to use the new CMakeLists.txt

apps/stransmit.cpp, common/socketoptions.cpp, common/socketoptions.hpp, srtcore/core.cpp, srtcore/csrtcc.cpp
Also some cosmetics, and removed obsolete TSBPDMAXLAG also from socketoptions.
=> Changing defaults tsbpdmode=true latency=120

haicrypt/CMakeLists.txt, srtcore/CMakeLists.txt
This makes sure DLLs are installed to the bin directory
=> Install DLLs on windows

README.md
=> Update README with Mac build docs

apps/srt-file-transmit.cpp, apps/srt-live-transmit.cpp, common/appcommon.hpp
=> Updated options for handling disabled flushing before closing

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp
=> Refactor: extracting packet's sequence number only

.travis.yml
Hopefully temporary workaround to address #125 based on user feedback from https://github.com/travis-ci/travis-ci/issues/8552. We should follow the progress of this bug report with travis-ci and adjust when final resolution is accepted.
=> Perform brew update in Travis CI to fix #125

srtcore/api.cpp, srtcore/udt.h
Few minor adjustments to allow legacy apps to compile against new SRT code.
=> Minor fixes for backward compatibility with legacy applications

CMakeLists.txt, common/platform_sys.h, configure-data.tcl, srtcore/api.h
- fixes for gnutls recognition for Mac
- fixes for MinGW (cross-compiler on Linux)
- other minor fixes
=> Added build improvements from 'master' branch.

srtcore/api.cpp, srtcore/core.cpp
Also for most "impossible" situations.
=> Added more logs around rejection

common/netinet_any.h
=> Added const & and explicit getter for sockaddr_any to return sockaddr*

common/transmitmedia.cpp
Hi, this includes the DROP packets in the printed statistics.
Plus a more readable print outs.
=> Stransmit new stats

srtcore/core.cpp
These should drop Error-level logs in case when:
- TLPKTDROP caused a packet to be dropped
- when delivering the stream to the application by the receiver
- when sending a stream and the packet is decided to be no longer retransmitted
- packet decryption failed at the receiver
- packet encryption failed at the sender
These logs were added during the research of a problems with sending an encrypted stream. These logs should never appear during a normal work; just for a case when errors from decrypting packet could appear one after another for every packet, it's printed only once per 100 seen events.
=> Added more logs in places where transmission problems are detected

srtcore/srt_compat.c
Fix windows build breakage introduced in PR #285
=> Fix windows build

docs/API.md
Expanded delimiter row to reflect total number of columns.
=> Fixed API Options table format

CMakeLists.txt, apps/uriparser.cpp, apps/verbose.cpp, apps/verbose.hpp, srtcore/srt.h, testing/srt-test-relay.cpp, testing/srt-test-relay.maf, testing/testmedia.cpp, testing/testmedia.hpp, testing/testmediabase.hpp
Added a relay bidirectional application. Added relay classes in testmedia. Reused epoll direction enum. Added multiple ? handling in uriparser. Added possibility for verbose locking.
=> Added a bidirectional transmission testing application.

srtcore/core.cpp
This fixes a problem mentioned in #342.
=> Added removeConnector to exe path where connection is no longer to be processed.

apps/transmitmedia.cpp
This pull request adds igmpv3 ssm to srt
=> - add the source parameter to allow for igmpv3 ssm

scripts/srt.pc.in
=> Fixed a 64-bit installation problem for library path

CMakeLists.txt
applying this patch cross compiling from linux works
=> cmake: fix linking with MinGW

srtcore/platform_sys.h
=> Fix MINGW build.

haicrypt/hc_openssl_aes.c
=> Enable support for BoringSSL.

common/filelist_win32.maf
Remove stdint.h from windows file list
=> Fix for #453

.travis.yml, CMakeLists.txt
- Fix make errors in MingW32 build
- Add MingW32 build to Travis CI for validation
=> MingW32 build: fix and add to Travis CI  

CMakeLists.txt, cmake_object_lib_support.c
=> Support for CMake Object Library in XCode build.

.appveyor.yml, .travis.yml, CMakeLists.txt, scripts/googletest-download.cmake, scripts/googletest.cmake, srtcore/buffer.cpp, srtcore/buffer.h, test/test_buffer.cpp, test/test_connection_timeout.cpp
Including the test from the issue #468
=> Added Google Test framework

test/test_connection_timeout.cpp
Avoid hang up on srt_epoll_wait().
=> tests: connection timeout test improved.

CMakeLists.txt, scripts/haiUtil.cmake
=> scripts/haiUtil.cmake: Prepend DESTDIR when creating symlinks

docs/gstreamer.md
An example for using SRT with GStreamer, based on the description in #7.
=> [docs] Added an example of using SRT with GStreamer

apps/srt-live-transmit.cpp
=> [apps] Fixed memory leak in stransmit

apps/srt-live-transmit.cpp, testing/srt-test-live.cpp
=> [apps] fixed catching polymorphic type by value

CMakeLists.txt, README.md, docs/stransmit.md
=> [build] Removed stransmit symlink

srtcore/common.h, srtcore/core.cpp, srtcore/smoother.cpp
=> Fixed wrong usage of seqcmp

test/filelist.maf, test/test_seqno.cpp
=> [tests] Added tests for CSeqNo

srtcore/epoll.cpp
fix wrong deadlock condition in CEPoll::wait
=> fix empty condition in CEPoll::wait

docs/SRT-Multiplex.md
Already reviewed by @stevomatthews .
=> Added documentation for srt-multiplex

srtcore/core.cpp
=> Fixed a timestamp of ACKACK control packet.

CMakeLists.txt, configure-data.tcl, test/filelist.maf, test/test_epoll.cpp
Some simple tests for EPoll. The PR also contains a minor change to the CI tests build.
=> Added some tests for the CEPoll

srtcore/core.cpp
=> Added NAKREPORT SRTHS flag as per m_bRcvNakreport field

apps/transmitbase.hpp, apps/transmitmedia.cpp, apps/transmitmedia.hpp, test/test_strict_encription.cpp
Fixing build warnings in apps and tests.
=> Fixing build warnings

apps/apputil.hpp
=> Fixed bug: colon and next arg both eat ARG_ONE argument

srtcore/congctl.cpp
1. Removed goto statement usage.
2. Fixed initialization of m_iDecCount.
3. Fixed warnings.
=> [core] FileCC minor code improvements.

apps/srt-live-transmit.cpp
=> [apps] Fixed timeout mode cancel when target connected

srtcore/buffer.cpp
=> Fixed buffers avg size calculation

srtcore/common.cpp
#711 Visual Studio doesn't support inline asm, but does allow a no-op intrinsic to be added
=> Added a no-op for Windows in BUSY_WAITING mode

apps/srt-tunnel.cpp, srtcore/utilities.h
=> Maintain support for g++ 4.7 with C++11 applications

docs/API.md, docs/AccessControl.md
=> [docs] StreamID moved to a separate document.

README.md
There were already several requests to describe installation paths and uninstall options.
Adding those descriptions to README.md.
Fixes #573
=> [docs] CMake install description

srtcore/channel.cpp, srtcore/channel.h
=> Fixed error reported from bind for valid IN6_ADDR when setting TTL/HOPS or TOS/TCLASS

srtcore/srt_c_api.cpp
Remove specific define block for LINUX
=> srt_c_api: remove duplicate code in srt_epoll_*

docs/API.md, srtcore/core.cpp
Fix linger socket option with SRT recommended OFF default
=> Fix linger socket option with SRT recommended OFF default

.gitignore
Added a `.gitignore` file from this [collection](https://github.com/github/gitignore) for C++.
Added certain folders:
```
_*/
```
```
.vs/
```
=> [build] Added gitignore

srtcore/queue.cpp
CRendezvousQueue::updateConnStatus
=> [core] Reducing cognitive complexity of updateConnStatus

docs/stransmit.md
Very helpful example provided by @maxlovic captured in the documentation to aid POCs and sanity checking
=> Provide smoke test example

docs/stransmit.md
Example for running live transmit app in listener mode, listening on a specific network interface
=> Improve examples

srtcore/fec.cpp, srtcore/fec.h
As per complaints from static checker
=> Fixed passing a constant set by reference

srtcore/epoll.cpp
=> Added initialization to a debug-tracing variable

.travis.yml
Add `-DENABLE_LOGGING=OFF` build options to the Travis build matrix.
=> [build] Travis now has -DENABLE_LOGGING=OFF

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
=> Created issue templates

.travis.yml
Fixed Travis environment variables usage
=> [build] Fixed env in travis

apps/logsupport.cpp, srtcore/congctl.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/srt.h
Added new `cclog` functional area for congestion control logging. Previously was mixed with control functional area.
=> [core] Separated CC log area

docs/API.md
Remove the duplicate description for SRTO_KMPREANNOUNCE
Signed-off-by: Jun Zhao <barryjzhao@tencent.com>
=> docs/API: remove duplicate description for SRTO_KMPREANNOUNCE

apps/apputil.cpp, apps/apputil.hpp, apps/support.maf, testing/srt-test-file.maf, testing/srt-test-live.maf, testing/srt-test-multiplex.maf, testing/srt-test-relay.maf
=> Extracted utilities to a separate file

docs/API.md
=> Removed recommendation for SO_SNDBUF exposed option

srtcore/buffer.cpp
=> [core] Fixed rexmit packet time

srtcore/srt.h
=> Fixed attributes for C++11

srtcore/list.cpp, srtcore/list.h
A subset of changes from #1012 introducing minor refactoring for better code readability.
Review the diff by commits.
- [core] `CSndLossList::insertHead(...)` function added
- [core] Added `CSndLossList::coalesce(...)`
- [core] Added `CSndLossList::updateElement()`
=> Minor refactoring of CSndLossList::insert(...)

srtcore/common.h
=> [core] Fixed an extra null pointer check before delete

README.md, submodules/pthread-win32/STUB
Updated build instructions in readme accordingly.
No point in that hanging pthread submodule STUB.
=> [docs] Deleted pthreads as git submodule

srtcore/common.h, srtcore/core.cpp, srtcore/core.h, srtcore/list.cpp, srtcore/list.h
- data1 -> seqstart;
- data2 -> seqend;
- next -> inext
- prior -> iprior
Plus small const changes to EventVariant
=> Minor renamings to CSndLossList and CRcvLossList

srtcore/packetfilter_api.h
=> Added lacking includes to packetfilter_api.h

testing/srt-test-live.cpp, testing/testmedia.cpp, testing/testmedia.hpp
NOTE: this is actually dependent on #1137 and will compile only after this is merged back from master
=> Application support for socket groups (testing app only)

test/test_enforced_encryption.cpp
Added a CV to notify that the accepting thread is initialized and ready to perform accept.
After that in blocking mode the test will wait for 50ms and close the listener socket to get the return from `srt_accept(..)`.
In some cases, that started to happen in Travis test runs, the creation of thread took longer than 50 ms, and the `srt_accept(..)` was called after the listener socket was already closed.
=> [tests] Fixed enforced ENC blocking mode test

CMakeLists.txt, examples/test-c-client-bonding.c, examples/test-c-server-bonding.c
=> Added test examples for bonding

test/test_connection_timeout.cpp
from 500 +/- 50 ms  to 500 +/- 80 ms
=> [tests] Increased connection timeout tolerance

apps/srt-tunnel.cpp, examples/test-c-server-bonding.c, scripts/tcp-echo-client.tcl, testing/srt-test-live.cpp, testing/srt-test-relay.cpp
- Fixed typos: exitting -> exiting.
=> Minor fixes of typos (exitting -> exiting)

srtcore/handshake.h
=> [core] Changed HS Extension Group value to 8

docs/API-functions.md, docs/statistics.md
- Revised accumulated statistics, 
- Added summary table
This is a subset of PR #1199.
=> [docs] Revised accumulated statistics, added summary table

docs/API.md
=> Added supplement information for packetfilter option

apps/socketoptions.cpp, apps/socketoptions.hpp, apps/transmitmedia.cpp, srtcore/srt_c_api.cpp, testing/testmedia.cpp
=> Fixed rendezvous handling in SRT pre-configure

srtcore/core.cpp, srtcore/core.h
=> Replaced single-pass while with if

srtcore/api.cpp, srtcore/buffer.cpp, srtcore/common.cpp, srtcore/common.h, srtcore/core.cpp, srtcore/core.h, srtcore/packetfilter.cpp, srtcore/packetfilter_api.h, srtcore/srt.h, srtcore/srt_c_api.cpp, testing/testmedia.cpp, testing/testmedia.hpp
1. Renamed priority to weight (including pri -> weight in app support)
2. Added extra check for srt_group_data
3. Extracted packetfilter configuration part to make a universal internal configuration handler for future balancing algorithms.
=> BALANCING GROUPS: pre-refax changes

bvc_srt.lua, scripts/srt-dev.lua
=> filter for wireshark

CMakeLists.txt, examples/suflip.cpp
=> Fixed suflip app as example.

srtcore/core.cpp
=> Added lacking setting back of the size

docs/API-functions.md, srtcore/api.cpp, srtcore/api.h, srtcore/common.cpp, srtcore/core.cpp, srtcore/core.h, srtcore/handshake.cpp, srtcore/handshake.h, srtcore/queue.cpp, srtcore/srt.h, srtcore/srt_c_api.cpp, testing/srt-test-live.cpp, testing/testmedia.cpp, testing/testmedia.hpp
=> Customizable reject reason code

srtcore/buffer.cpp, srtcore/buffer.h
Drift histogram is a developer-only feature.
This PR only affects code under `#ifdef SRT_DEBUG_TSBPD_DRIFT`.
Fixed build.
=> [core] Fixed drift histogram

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp, srtcore/queue.cpp, srtcore/srt.h
Error messages regarding TSBPD wrap period and "No room to store incoming packet" are being reported, e.g. in #1246.
This PR improved log messages to give more hints on the source of errors.
=> [core] Added more info to TSBPD and mem logs

README.md
=> [docs] Added cookbook and RFC links to README

scripts/srt-dev.lua
Fixed the error parsing stream ID and extension fields
=> Fixed some problems about lua dissector

docs/API.md
=> Fixed typos in doc sources

srtcore/api.cpp
One change that was missed from the group status fix #1326.
This sets the error code from the member connection that has failed and the loop isn't interrupted because of this error.
=> Fixed the new error reporting from a member connection

testing/srt-test-live.cpp
Concerns the testing application only.
=> Fixed: exit when media creation failed

srtcore/api.cpp
Binding is one of the activities potentially done for the socket being connected, but it can fail as all others. This failure should not interrupt the loop over defined connections, but just fail this one. For simplification, binding has been moved up to happen before the socket is added to the group and put under a common exception handling to delete a socket prematurely, mark the error, and continue with other defined connections.
=> [core] Fixed error handling for group connections

apps/uriparser.hpp, srtcore/core.cpp, srtcore/srt.h, srtcore/sync.h, srtcore/utilities.h
@elfring Please review and propose further fixes if needed.
Fixes #1101
=> Further fixes for violation of reserved identifiers

srtcore/buffer.cpp
Applied clang format on buffer.cpp to prepare for upcoming changes to the buffer's avg statistics (#1272).
=> [core] Clang format on buffer.cpp

srtcore/core.cpp
Fixes #1345
The problem: in the procedure where the sequence should be updated before dispatching collected packets from the receiver buffer, the call to `overrideSndSeqNo` was under `ENABLE_HEAVY_LOGGING` conditional.
=> Fixed bug in fixing seq on activation in rel mode

srtcore/netinet_any.h
Added get_addr.
Made len prepared for filling.
Added portable slen_t.
=> Improvement in sockaddr_any required for communication with more system functions

apps/transmitmedia.cpp
=> Fixed IPv6 handling in srt-live-transmit

test/test_many_connections.cpp
Weird behavior was observed on CI when running this test, so the following check was added:
The `srt_accept` call shall either block forever or always succeed, and the only reason for it to fail is when the listener socket is closed. The check was added to see that the listener socket survived up to the moment when it should be closed.
=> Added more checks for torturing test

srtcore/buffer.cpp
=> Added null-check for buffer extraction procedure

srtcore/buffer.cpp, srtcore/buffer.h, srtcore/core.cpp
Warning: Result may overflow before it is converted to a 64-bit integer.
=> [core] Fixed static check warning.

srtcore/api.cpp, srtcore/core.cpp, srtcore/core.h
=> Set the remote address in the group member data for an accepted member socket

CONTRIBUTING.md, README.md, docs/Developers.md
Addressed the first item of #1442
=> [docs] Created the Developer's guide

srtcore/api.cpp, srtcore/api.h
Fixes https://github.com/Haivision/srt/issues/1396
=> Fixed bug: merged update/add_usock. usock didn't regard the groups.

testing/srt-test-live.cpp
The `-v` option was getting normally the 1 or 2 argument to declare it should use stdout or stderr. This option allows also to specify the file, as long as the argument starts from `./` so that it declares explicitly that it designates a file.
=> [devel] Added verbose to file option

srtcore/api.cpp
This will still add the socket to the group when you don't need to set address buffer.
=> [BUG] Not adding socket to group when address buffer is not set

docs/API-functions.md, docs/socket-groups.md, srtcore/api.cpp, srtcore/core.h, srtcore/group.cpp, srtcore/group.h, srtcore/srt.h
=> Changed priority rule to higher preferred. Set uint16_t as weight type.

docs/APISocketOptions.md, srtcore/core.cpp, srtcore/core.h
=> [MAINT] Set default stability timeout to 80ms

docs/API-functions.md
=> [docs] Added lacking description for grpdata field in SRT_MSGCTRL

.github/workflows/cxx11-macos.yaml, .github/workflows/cxx11-ubuntu.yaml, .github/workflows/cxx11-win.yaml, .travis.yml, test/filelist.maf, test/test_bonding.cpp
A unit test `TEST(Bonding, SRTConnectGroup)` addresses issue #1432
=> [tests] Added test for srt_group_connect

README.md
=> [docs] Added LGTM badges

docs/API-functions.md
Submitted on behalf of @stevomatthews 
This PR reworks the [API-functions.md](https://github.com/maxsharabayko/srt/blob/docs/api-functions-rework/docs/API-functions.md) document.
The goal is to have better navigation, a smoother working experience, and a consistent formatting.
=> [docs] Reworked API functions document

srtcore/group.cpp
Extracting some minor refactoring from a feature branch with runtime link stability threshold.
=> [core] Minor refactoring of backup CheckIdleTime

srtcore/api.h, srtcore/core.cpp, srtcore/core.h, srtcore/handshake.cpp, srtcore/handshake.h
=> [core] Added handshake data check to prevent rogue handshakes

srtcore/group.cpp
`m_RcvBaseSeqNo` must be updated only when a packet is read.
However, it could have been updated also when only checked.
=> [core] Fixed faulty packet drop by a group.

srtcore/fec.cpp, srtcore/fec.h
=> [core] Aligned NOTDONE and SUCCESS result of hanging as acceptable

srtcore/group.cpp, srtcore/sync.cpp
Wrong formatting of sub-seconds after PR #1766 
Also removed unused variable.
=> [core] Fixed FormatTime subseconds

srtcore/core.cpp
Fixing an issue introduced in PR #1776.
Socket option with post-action.
=> [core] Fixed post-action for socket options

README.md
Updated the `txt` link to the RFC.
=> [docs] Updated the link to the RFC

apps/apputil.cpp
- byteAvailSndBuf
- msSndBuf
- byteAvailRcvBuf
- msRcvBuf
- msRcvTsbPdDelay (RCVLATENCYms in srt-live-transmit v1.4.2)
Fixes #1908
=> [apps] Added CSV and JSON stats

srtcore/buffer.h
- Applied clang-format on buffer.h.
- Fixed Doxygen comments alignment
=> [core] Applied clang-format on buffer.h.

haicrypt/cryspr-mbedtls.h
Ref. https://github.com/ARMmbed/mbedtls/issues/1215
=> Fix build with mbedtls older than 428cc52a73.

docs/features/bonding-main-backup.md
=> [docs] Corrections to the main backup doc

README.md
Small edits to the "requirements" section in the readme. Mainly updates the old requirement for `pthreads`.
=> [docs] Edits for the 'requirements' in ReadMe.md

apps/apputil.hpp, apps/logsupport.cpp, apps/logsupport.hpp, apps/verbose.hpp, testing/srt-test-live.cpp, testing/srt-test-relay.cpp, testing/srt-test-relay.maf, testing/testactivemedia.cpp, testing/testactivemedia.hpp, testing/testmedia.cpp, testing/testmedia.hpp, testing/testmediabase.hpp
Reusable components moved to shared files:
* FA Parser to apputils
* Active Source/Target components developed for srt-test-realy moved to testactivemedia.
=> [devel] Refactored app support components to make them more reusable

srtcore/api.cpp, srtcore/buffer.cpp, srtcore/channel.cpp, srtcore/core.cpp, srtcore/crypto.cpp, srtcore/epoll.cpp, srtcore/fec.cpp, srtcore/group.cpp, srtcore/logging.h, srtcore/sync.h, srtcore/utilities.h, test/test_buffer.cpp, test/test_epoll.cpp, test/test_fec_rebuilding.cpp, test/test_ipv6.cpp, test/test_listen_callback.cpp, test/test_seqno.cpp, test/test_socket_options.cpp, test/test_sync.cpp, test/test_utilities.cpp, testing/testmedia.cpp
1. Fix unused-variable warning
2. Fix -Wsign-compare
=> Fix build warning

srtcore/core.cpp, srtcore/crypto.h
Remove local static SRTDATA_MAXSIZE since there is another one in
global namespace.
=> [core] Replace hacky static_assert by SRT_STATIC_ASSERT

srtcore/epoll.cpp, srtcore/utilities.h
=> [core] Fix FTBFS on Debian kfreebsd

srtcore/api.cpp, test/test_socket_options.cpp
Taken from #2083 to run CI separately.
=> Fixed minor warnings

docs/API/API-functions.md
=> [docs] Improved a note about srt_recv(..) and payload size

srtcore/core.cpp
The new receiver buffer (introduced in PR #1964) does not require packets to be acknowledged before they can be read, hence the epoll read-readiness notification in `CUDT::sendCtrlAck()` must be done only if reading is actually available.
Otherwise, the reading thread (application) can read further than the current ack, and reset the read-readiness state. While the library-internal thread will send ACK afterwards, acknowledging new packets and assuming the read-ready state of the receiver buffer has changed.
**Affected configuration:** edge-triggered polling, with `SRTO_TSBPD=OFF`.
**Affected SRT versions:** development (v1.4.5).
Fixes #2179.
=> [core] Fixed read-ready epoll event in stream (file) mode.

apps/transmitmedia.cpp, testing/testmedia.cpp
=> Added support for adapter parameter in caller mode

srtcore/buffer_rcv.cpp
Fixed the crash mentioned in https://github.com/Haivision/srt/pull/2223#issue-1098910115
=> [core] replace ++ with incPos() in getTimespan_ms()

srtcore/buffer_rcv.cpp, srtcore/buffer_rcv.h
Fix https://github.com/Haivision/srt/pull/2207#issuecomment-1002916763
=> [core] fix CRcvBufferNew::dropMessage()

test/test_file_transmission.cpp
=> [tests] Use std::random_device in Transmission.FileUpload

srtcore/utilities.h
Taken from https://sources.debian.org/src/srt/1.4.2-2/debian/patches/ftbfs_kfreebsd.patch/
Cudos to @florianernstfor sharing. See #2253.
Fixes #2253.
=> [build] Fix build on Debian

srtcore/core.cpp
There is two bugs:
* `m_bPeerRexmitFlag` will not be updated if `m_bTsbPd` is false in `updateSrtRcvSettings()`.
* If `(m_bTsbPd && gp->getBufferTimeBase())` is true, `updateSrtRcvSettings()` will not be called in `synchronizeWithGroup()`, thus `m_bPeerRexmitFlag` will not be updated.
=> [core] fix `CRcvBufferNew::m_bPeerRexmitFlag` may not be updated

apps/srt-live-transmit.cpp, apps/srt-tunnel.cpp, apps/transmitbase.hpp, test/test_enforced_encryption.cpp, test/test_sync.cpp, testing/srt-test-live.cpp, testing/srt-test-relay.cpp
Fix https://github.com/Haivision/srt/pull/2264#issuecomment-1098023860
=> Replace `volatile` with `atomic`.

haicrypt/cryspr-config.h, haicrypt/haicrypt_log.cpp, srtcore/logging.h
Fixes #2276 
Also added missing `DummyProxy& vform(..)` function.
=> [core] Fixed ENABLE_HAICRYPT_LOGGING

README.md, docs/API/API-functions.md, docs/API/API.md, docs/API/statistics.md, docs/README.md, docs/features/bonding-main-backup.md, docs/features/handshake.md, srtcore/tsbpd_time.h
Changed the name from RFC to Internet Draft plus updated the links.
=> [docs] Changed the name from RFC to Internet Draft plus updated the links

haicrypt/hcrypt_sa.c
Using parentheses to clarify the code.
Fixes #2377.
=> [core] Fixed suspicious (HCRYPT_CTX_F_ENCRYPT & ctx->flags ? ..).

srtcore/core.cpp
=> [core] Cookie contest log msg downgraded to Debug

haicrypt/cryspr.c
Some minor refactoring of the `crysprFallback_MsEncrypt(..)` function.
- Reduced code nesting.
- Better reuse common code around `CRYSPR_HAS_AESCTR`.
=> Refactor crysprFallback_MsEncrypt

srtcore/core.h, srtcore/group.cpp
=> [core] Removed unused struct FByOldestActive.

srtcore/packet.cpp, srtcore/packet.h
=> [core] Applied clang-format on CPacket.

srtcore/group.cpp
=> [core] Removed unused struct HaveState

srtcore/channel.cpp
=> [core] remove MSG_TRUNC logging

docs/build/build-options.md
- Fixed the version to 1.5.1.
- Did some minor changes to the build options summary table.
=> [docs] Fixed version to 1.5.1 and did minor changes to build options summary table

srtcore/list.cpp, srtcore/list.h, test/filelist.maf, test/test_losslist_rcv.cpp, test/test_losslist_snd.cpp
A couple of tests to follow up on #2463.
Currently failing until the fix in #2463 is merged to master.
=> [tests] Added a couple of tests on RCV loss list.

srtcore/api.cpp, srtcore/core.cpp, srtcore/core.h
We have many connections at the same time, with `CONID()`, we can grep related logs easily.
=> [core] Improved logs of core.cpp with CONID()

srtcore/core.cpp
https://github.com/Haivision/srt/pull/2465#issuecomment-1259604982 and https://github.com/Haivision/srt/pull/2465#issuecomment-1259496409
=> [core] Replaced m_iRcvLastSkipAck with m_iRcvLastAck in logs.

srtcore/core.cpp
The retransmission flag has to be supplied, otherwise, a packet might be falsely considered a filter packet.
=> [core] Fixed message seqno check.

examples/test-c-client.c, examples/test-c-server.c
Fixes #2571
Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>
=> [examples] add wait 1 sec until receiver completes.

docs/API/API-socket-options.md
=> [DOC] Fixed invalid link 2-srt_km_state

haicrypt/cryspr.c, srtcore/core.cpp
=> [MAINT] Removed duplicate lines

docs/API/API-socket-options.md
=> [docs] Added SRTO_PBKEYLEN negotiation table.

docs/API/API-functions.md, docs/API/API-socket-options.md, docs/build/build-options.md, srtcore/srt.h
Minor updates to AEAD documentation plus changed v1.6.0 to 1.5.2 in some files.
=> [docs] Minor updates to AEAD documentation plus changed v1.6.0 to 1.5.2 in some files

testing/testmedia.cpp
=> Fixed conditional IP_ADD_SOURCE_MEMBERSHIP in testmedia

srtcore/core.cpp, srtcore/socketconfig.h
=> Fixed: properly handled strings with NUL characters inside

srtcore/core.cpp, test/test_socket_options.cpp
- Added missing getter for the SRTO_MAXREXMITBW socket option.
- Added unit tests for the SRTO_MAXREXMITBW socket option.
=> Added missing getter for the SRTO_MAXREXMITBW socket option.

srtcore/socketconfig.cpp
=> [core] Removed settable ability for SRTO_VERSION

srtcore/api.cpp, srtcore/api.h, srtcore/cache.h, srtcore/core.cpp, srtcore/group.cpp
Minor changes:
- Added missing `SRT_ATTR_GUARDED_BY(m_GlobControlLock)`.
- Removed unused `m_MultiplexerLock`.
=> [core] Added missing SRT_ATTR_GUARDED_BY(m_GlobControlLock).

srtcore/core.h, srtcore/srt_attr_defs.h
Just minor changes in comments dedicated to thread safety analyzers.
=> [core] Added some SRT_ATTR_EXCLUDES to CUDT.

srtcore/cache.cpp, srtcore/cache.h
Applied clang-format on cache.h and cache.cpp.
=> Applied clang-format on cache.h and cache.cpp.

srtcore/queue.cpp, srtcore/queue.h, srtcore/sync.h
Addresses issue #2973 partially.
=> [core] Made CSndQueue::m_counter atomic.

srtcore/common.cpp, test/test_fec_rebuilding.cpp
=> [BUG] Fixed nonchecked empty config for packetfilter

test/test_socket_options.cpp
=> [tests] Added NUL character unit test for StreamID socket opt.

docs/build/build-macOS.md
Fixes #3051 by enhancing the build procedure for macOS.
=> Complete documentation for building SRT on macOS

srtcore/core.cpp
Fixes #3131
Catches the case when the handshake response has come without the packetfilter extension, while it was configured on the agent:
* On caller, if the caller has configured packetfilter, and listener responded without it, reject the connection: this should never happen in case when the listener is in the version that supports packetfilter, while allowing the connection could cause confusion during transmission and some silent runtime errors
* On listener, if the listener configured packetfilter, but the caller did not request it, allow the connection without packetfilter
=> [core] Late-rejection when listener responds with no packet filter

srtcore/socketconfig.h, srtcore/srt.h
=> [API] Set up length limits for STREAMID and PACKETFILTER in the API

test/test_bonding.cpp
A second attempt to fix often randomly failing ConnectNonBlocking.
The problem:
The test states that when you use non-blocking mode and do `srt_connect()` and then immediately try to send, sending should fail. This wasn't the case many times because the sending after connecting was executed so late that in the meantime in the accepting thread the connection was successfully added to the queued sockets, even if the `srt_accept()` call didn't extract it yet.
The fix: the listener socket is bound, but the `srt_listen()` call is withheld until the main thread passes the call to connect and send.
=> [test] Fixing ConnectNonBlocking: delay listen to prevent connection from being established too early

srtcore/core.cpp
Fixes #3208
The previous version was checking the substraction result if it has set the 31th bit.
However, this bit could be just as well set if the result of the 64-bit subtraction is positive. Only since the 32 bit would be all bits set or clear.
=> [core] Fixed invalid cookie contest calculation
